online_sample_time: 0.002  #touch采样时间间隔
online_generate_traj_interval: 0.001 #生成轨迹间隔
online_N_step_P: 5  #计算位置-取VP点的采样点间隔--->每5个采样点取一个xyz向量  范围<=5
online_N_step_Q: 25 #计算姿态-取VQ的采样点间隔--->每25个采样点取一个abc向量
online_N_interp_P: 10 #//NinterpP_ = ((N_step_P_*Tsample_)/GEN_TN_);
online_N_interp_Q: 50 #//NinterpQ_ = ((N_step_Q_*Tsample_)/GEN_TN_);
online_trj_ratio_xyz: 1.0 #机械臂移动距离与touch移动距离的比例系数,    即机械臂移动距离=K*touch移动距离
online_trj_ratio_abc: 1.0 #机械臂移动距离与touch移动角度的比例系数,    即机械臂轴转动角度=K*touch轴转动角度
online_receive_Tmatrix_buff_len: 1000  #运控接收来自Touch T矩阵数据的缓存数量








