name: group_application_1000
model_id: 
    operation_value: 1000
    default_value: 1000
    upper_limit_value: 0 
    lower_limit_value: 0
    unit: None
    attr: 1
    validity: 0
target_reached_count_max:
    operation_value: 10
    default_value: 10
    upper_limit_value: 1000
    lower_limit_value: 1
    unit: None
    attr: 3
    validity: 1
coupling_numerator_5to6:
    operation_value: 0
    default_value: 0
    upper_limit_value: 1000
    lower_limit_value: 1
    unit: None
    attr: 3
    validity: 2
coupling_denominator_5to6:
    operation_value: 1
    default_value: 1
    upper_limit_value: 1000
    lower_limit_value: 1
    unit: None
    attr: 3
    validity: 2
coupling_direction_5to6:
    operation_value: 0
    default_value: 0
    upper_limit_value: 1
    lower_limit_value: 0
    unit: None
    attr: 3
    validity: 2
