servo:
    param_length: 5120
    stored_length: 4864
    stored_param:
        - 3
        - 0
        - 1
        - 0
        - -1509949440
        - 1509949440
        - 0
        - 0
        - 1
        - 50331648
        - 150000
        - 250
        - 0
        - 0
        - 0
        - 0
        - 33554432
        - 1677722
        - 58720256
        - 1342177280
        - 5000
        - 16777216
        - 5000
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 419430400
        - 0
        - 0
        - 0
        - 3355443
        - 50
        - 1000
        - 5000
        - 0
        - 150
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 20
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 8
        - 0
        - 0
        - 5000
        - 5000
        - 1000
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 750
        - 91100282
        - 0
        - 0
        - 0
        - 0
        - 10
        - 5
        - 49302
        - 0
        - 6088139
        - 2008413
        - 0
        - 2
        - 0
        - 0
        - 8388608
        - 0
        - 0
        - 16777216
        - 0
        - 0
        - 0
        - 58720256
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 6000000
        - 0
        - 40000000
        - 167772
        - 0
        - 100
        - 15
        - 4501357
        - 79642
        - 100
        - 1677722
        - 167772
        - 1
        - 5
        - 10
        - 20
        - 1
        - 5
        - 10
        - 20
        - 1
        - 1
        - 16777216
        - 50
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 40000000
        - 167772
        - 0
        - 100
        - 2
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 3
        - 0
        - 1
        - 0
        - -2030043136
        - 2030043136
        - 0
        - 0
        - 1
        - 50331648
        - 150000
        - 250
        - 0
        - 0
        - 0
        - 0
        - 33554432
        - 1677722
        - 58720256
        - 1342177280
        - 5000
        - 16777216
        - 5000
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 503316480
        - 0
        - 0
        - 0
        - 16777216
        - 50
        - 1000
        - 5000
        - 0
        - 250
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 20
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 8
        - 0
        - 0
        - 5000
        - 5000
        - 1000
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 600
        - 72142028
        - 0
        - 0
        - 0
        - 0
        - 15
        - 5
        - 49302
        - 0
        - 6144002
        - 2008413
        - 0
        - 2
        - 0
        - 0
        - 6543114
        - 0
        - 0
        - 16777216
        - 0
        - 0
        - 0
        - 58720256
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 6000000
        - 0
        - 25000000
        - 167772
        - 0
        - 100
        - 20
        - 4662097
        - 95845
        - 200
        - 1677722
        - 16777
        - 1
        - 5
        - 10
        - 20
        - 1
        - 5
        - 10
        - 20
        - 1
        - 1
        - 16777216
        - 50
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 25000000
        - 167772
        - 0
        - 100
        - 4
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 3
        - 0
        - 1
        - 0
        - -1342177280
        - 1342177280
        - 0
        - 0
        - 1
        - 50331648
        - 150000
        - 250
        - 0
        - 0
        - 0
        - 0
        - 33554432
        - 1677722
        - 58720256
        - 1342177280
        - 5000
        - 16777216
        - 5000
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 419430400
        - 0
        - 0
        - 0
        - 16777216
        - 20
        - 1000
        - 5000
        - 0
        - 100
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 20
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 8
        - 0
        - 0
        - 5000
        - 5000
        - 1000
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 400
        - 46137344
        - 0
        - 0
        - 0
        - 0
        - 20
        - 5
        - 49302
        - 0
        - 6387891
        - 2008413
        - 0
        - 2
        - 0
        - 0
        - 6710886
        - 0
        - 0
        - 16777216
        - 0
        - 0
        - 0
        - 58720256
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 6000000
        - 0
        - 28615093
        - 167772
        - 0
        - 100
        - 15
        - 6356654
        - 229294
        - 300
        - 1677722
        - 1342177
        - 1
        - 5
        - 10
        - 20
        - 1
        - 5
        - 10
        - 20
        - 1
        - 1
        - 16777216
        - 50
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 28000000
        - 167772
        - 0
        - 100
        - 3
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 3
        - 0
        - 1
        - 0
        - -905969664
        - 905969664
        - 0
        - 0
        - 1
        - 50331648
        - 150000
        - 250
        - 0
        - 0
        - 0
        - 0
        - 33554432
        - 1677722
        - 58720256
        - 1342177280
        - 5000
        - 16777216
        - 5000
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 503316480
        - 0
        - 0
        - 0
        - 16777216
        - 50
        - 1000
        - 5000
        - 0
        - 250
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 20
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 8
        - 0
        - 0
        - 5000
        - 5000
        - 1000
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 200
        - 29360128
        - 0
        - 0
        - 0
        - 0
        - 40
        - 5
        - 49302
        - 0
        - 5058577
        - 2257390
        - 0
        - 2
        - 0
        - 0
        - 6543114
        - 0
        - 0
        - 16777216
        - 0
        - 0
        - 0
        - 58720256
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 6000000
        - 0
        - 31244189
        - 167772
        - 0
        - 100
        - 10
        - 5754698
        - 241264
        - 350
        - 1677722
        - 1342177
        - 1
        - 5
        - 10
        - 20
        - 1
        - 5
        - 10
        - 20
        - 1
        - 1
        - 16777216
        - 50
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 30000000
        - 167772
        - 0
        - 100
        - 2
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 3
        - 0
        - 1
        - 0
        - -1258291200
        - 1258291200
        - 0
        - 0
        - 1
        - 50331648
        - 150000
        - 250
        - 0
        - 0
        - 0
        - 0
        - 33554432
        - 1677722
        - 58720256
        - 1342177280
        - 5000
        - 16777216
        - 5000
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 503316480
        - 0
        - 0
        - 0
        - 16777216
        - 50
        - 1000
        - 5000
        - 0
        - 250
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 20
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 8
        - 0
        - 0
        - 5000
        - 5000
        - 1000
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 100
        - 28521267
        - 0
        - 0
        - 0
        - 0
        - 40
        - 5
        - 49302
        - 0
        - 2587406
        - 1947552
        - 0
        - 2
        - 1000000
        - 1
        - 4194304
        - 279620
        - 0
        - 16777216
        - 0
        - 0
        - 0
        - 58720256
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 6000000
        - 0
        - 33554432
        - 167772
        - 0
        - 50
        - 8
        - 9215773
        - 341498
        - 400
        - 1677722
        - 1342177
        - 1
        - 5
        - 10
        - 20
        - 1
        - 5
        - 10
        - 20
        - 1
        - 1
        - 16777216
        - 50
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 33554432
        - 167772
        - 0
        - 50
        - 2
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 3
        - 0
        - 1
        - 0
        - -721420288
        - 721420288
        - 0
        - 0
        - 1
        - 50331648
        - 150000
        - 250
        - 0
        - 0
        - 0
        - 0
        - 33554432
        - 1677722
        - 58720256
        - 1342177280
        - 5000
        - 16777216
        - 5000
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 503316480
        - 0
        - 0
        - 0
        - 16777216
        - 50
        - 1000
        - 5000
        - 0
        - 250
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 20
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 8
        - 0
        - 0
        - 5000
        - 5000
        - 1000
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 100
        - 28521267
        - 0
        - 0
        - 0
        - 0
        - 40
        - 5
        - 49302
        - 0
        - 2587406
        - 1947552
        - 0
        - 2
        - 1000000
        - 1
        - 4194304
        - 279620
        - 0
        - 16777216
        - 0
        - 0
        - 0
        - 58720256
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 6000000
        - 0
        - 33554432
        - 167772
        - 0
        - 50
        - 8
        - 9215773
        - 341498
        - 450
        - 1677722
        - 1342177
        - 1
        - 5
        - 10
        - 20
        - 1
        - 5
        - 10
        - 20
        - 1
        - 1
        - 16777216
        - 50
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 33554432
        - 167772
        - 0
        - 100
        - 2
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
    stored_start: 256
    version: PUMA-20190703-00

#END