/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.7-dev at Tue Aug 28 15:30:36 2018. */

#include "axis_group_info.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t MessageType_AxisInfo_fields[3] = {
    PB_FIELD(  1, INT32   , REQUIRED, STATIC  , FIRST, MessageType_AxisInfo, axis_id, axis_id, 0),
    PB_FIELD(  2, INT32   , REQUIRED, STATIC  , OTHER, MessageType_AxisInfo, axis_type, axis_id, 0),
    PB_LAST_FIELD
};

const pb_field_t MessageType_AxisGroupInfo_fields[6] = {
    PB_FIELD(  1, INT32   , REQUIRED, STATIC  , FIRST, MessageType_AxisGroupInfo, group_id, group_id, 0),
    PB_FIELD(  2, INT32   , REQUIRED, STATIC  , OTHER, MessageType_AxisGroupInfo, group_type, group_id, 0),
    PB_FIELD(  3, STRING  , REQUIRED, STATIC  , OTHER, MessageType_AxisGroupInfo, group_name, group_type, 0),
    PB_FIELD(  4, INT32   , REQUIRED, STATIC  , OTHER, MessageType_AxisGroupInfo, axis_number, group_name, 0),
    PB_FIELD(  5, MESSAGE , REPEATED, STATIC  , OTHER, MessageType_AxisGroupInfo, axis_info_list, axis_number, &MessageType_AxisInfo_fields),
    PB_LAST_FIELD
};

const pb_field_t MessageType_AxisGroupInfoList_fields[2] = {
    PB_FIELD(  1, MESSAGE , REPEATED, STATIC  , FIRST, MessageType_AxisGroupInfoList, info_list, info_list, &MessageType_AxisGroupInfo_fields),
    PB_LAST_FIELD
};


/* Check that field information fits in pb_field_t */
#if !defined(PB_FIELD_32BIT)
/* If you get an error here, it means that you need to define PB_FIELD_32BIT
 * compile-time option. You can do that in pb.h or on compiler command line.
 * 
 * The reason you need to do this is that some of your messages contain tag
 * numbers or field sizes that are larger than what can fit in 8 or 16 bit
 * field descriptors.
 */
PB_STATIC_ASSERT((pb_membersize(MessageType_AxisGroupInfo, axis_info_list[0]) < 65536 && pb_membersize(MessageType_AxisGroupInfoList, info_list[0]) < 65536), YOU_MUST_DEFINE_PB_FIELD_32BIT_FOR_MESSAGES_MessageType_AxisInfo_MessageType_AxisGroupInfo_MessageType_AxisGroupInfoList)
#endif

#if !defined(PB_FIELD_16BIT) && !defined(PB_FIELD_32BIT)
/* If you get an error here, it means that you need to define PB_FIELD_16BIT
 * compile-time option. You can do that in pb.h or on compiler command line.
 * 
 * The reason you need to do this is that some of your messages contain tag
 * numbers or field sizes that are larger than what can fit in the default
 * 8 bit descriptors.
 */
PB_STATIC_ASSERT((pb_membersize(MessageType_AxisGroupInfo, axis_info_list[0]) < 256 && pb_membersize(MessageType_AxisGroupInfoList, info_list[0]) < 256), YOU_MUST_DEFINE_PB_FIELD_16BIT_FOR_MESSAGES_MessageType_AxisInfo_MessageType_AxisGroupInfo_MessageType_AxisGroupInfoList)
#endif


/* @@protoc_insertion_point(eof) */
