/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.7-dev at Fri Nov 16 10:39:17 2018. */

#include "io_device_info.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t MessageType_IoDeviceInfo_fields[7] = {
    PB_FIELD(  1, STRING  , REQUIRED, STATIC  , FIRST, MessageType_IoDeviceInfo, device_type, device_type, 0),
    PB_FIELD(  2, STRING  , REQUIRED, STATIC  , OTHER, MessageType_IoDeviceInfo, comm_type, device_type, 0),
    PB_FIELD(  3, INT32   , REQUIRED, STATIC  , OTHER, MessageType_IoDeviceInfo, device_index, comm_type, 0),
    PB_FIELD(  4, INT32   , REQUIRED, STATIC  , OTHER, MessageType_IoDeviceInfo, address, device_index, 0),
    PB_FIELD(  5, INT32   , REQUIRED, STATIC  , OTHER, MessageType_IoDeviceInfo, input_num, address, 0),
    PB_FIELD(  6, INT32   , REQUIRED, STATIC  , OTHER, MessageType_IoDeviceInfo, output_num, input_num, 0),
    PB_LAST_FIELD
};


/* Check that field information fits in pb_field_t */
#if !defined(PB_FIELD_16BIT) && !defined(PB_FIELD_32BIT)
#error Field descriptor for MessageType_IoDeviceInfo.comm_type is too large. Define PB_FIELD_16BIT to fix this.
#endif


/* @@protoc_insertion_point(eof) */
