/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.7-dev at Thu Dec 27 18:11:17 2018. */

#include "modbus_server_start_info.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t MessageType_ModbusServerStartInfo_fields[4] = {
    PB_FIELD(  1, STRING  , OPTIONAL, STATIC  , FIRST, MessageType_ModbusServerStartInfo, ip, ip, 0),
    PB_FIELD(  2, STRING  , REQUIRED, STATIC  , OTHER, MessageType_ModbusServerStartInfo, name, ip, 0),
    PB_FIELD(  3, INT32   , REQUIRED, STATIC  , OTHER, MessageType_ModbusServerStartInfo, response_delay, name, 0),
    PB_LAST_FIELD
};


/* @@protoc_insertion_point(eof) */
