/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.7-dev at Mon Dec  3 15:24:30 2018. */

#include "modbus_server_function.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif




/* @@protoc_insertion_point(eof) */
