/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.7-dev at Fri Dec  7 10:47:08 2018. */

#include "modbus_start_mode.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t MessageType_ModbusStartMode_fields[2] = {
    PB_FIELD(  1, UENUM   , REQUIRED, STATIC  , FIRST, MessageType_ModbusStartMode, start_mode, start_mode, 0),
    PB_LAST_FIELD
};


/* @@protoc_insertion_point(eof) */
