/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.7-dev at Fri Dec 28 10:08:34 2018. */

#include "modbus_reg_info.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t MessageType_ModbusRegInfo_fields[4] = {
    PB_FIELD(  1, INT32   , REQUIRED, STATIC  , FIRST, MessageType_ModbusRegInfo, address, address, 0),
    PB_FIELD(  2, INT32   , REQUIRED, STATIC  , OTHER, MessageType_ModbusRegInfo, number, address, 0),
    PB_FIELD(  3, UINT32  , REPEATED, STATIC  , OTHER, MessageType_ModbusRegInfo, value, number, 0),
    PB_LAST_FIELD
};


/* @@protoc_insertion_point(eof) */
