/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.7-dev at Wed Jan  2 15:26:38 2019. */

#include "modbus_client_start_info.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t MessageType_ModbusClientStartInfo_fields[7] = {
    PB_FIELD(  1, INT32   , REQUIRED, STATIC  , FIRST, MessageType_ModbusClientStartInfo, id, id, 0),
    PB_FIELD(  2, STRING  , REQUIRED, STATIC  , OTHER, MessageType_ModbusClientStartInfo, name, id, 0),
    PB_FIELD(  3, STRING  , REQUIRED, STATIC  , OTHER, MessageType_ModbusClientStartInfo, ip, name, 0),
    PB_FIELD(  4, INT32   , REQUIRED, STATIC  , OTHER, MessageType_ModbusClientStartInfo, port, ip, 0),
    PB_FIELD(  5, INT32   , REQUIRED, STATIC  , OTHER, MessageType_ModbusClientStartInfo, scan_rate, port, 0),
    PB_FIELD(  6, INT32   , REQUIRED, STATIC  , OTHER, MessageType_ModbusClientStartInfo, response_timeout, scan_rate, 0),
    PB_LAST_FIELD
};


/* @@protoc_insertion_point(eof) */
