/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.7-dev at Fri Dec 28 10:08:34 2018. */

#include "modbus_function.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t MessageType_ModbusFunctionAddrInfo_fields[3] = {
    PB_FIELD(  1, INT32   , REQUIRED, STATIC  , FIRST, MessageType_ModbusFunctionAddrInfo, address, address, 0),
    PB_FIELD(  2, INT32   , REQUIRED, STATIC  , OTHER, MessageType_ModbusFunctionAddrInfo, number, address, 0),
    PB_LAST_FIELD
};

const pb_field_t MessageType_ModbusAllFucntionAddrInfo_fields[5] = {
    PB_FIELD(  1, MESSAGE , REQUIRED, STATIC  , FIRST, MessageType_ModbusAllFucntionAddrInfo, coil, coil, &MessageType_ModbusFunctionAddrInfo_fields),
    PB_FIELD(  2, MESSAGE , REQUIRED, STATIC  , OTHER, MessageType_ModbusAllFucntionAddrInfo, discrepte_input, coil, &MessageType_ModbusFunctionAddrInfo_fields),
    PB_FIELD(  3, MESSAGE , REQUIRED, STATIC  , OTHER, MessageType_ModbusAllFucntionAddrInfo, holding_reg, discrepte_input, &MessageType_ModbusFunctionAddrInfo_fields),
    PB_FIELD(  4, MESSAGE , REQUIRED, STATIC  , OTHER, MessageType_ModbusAllFucntionAddrInfo, input_reg, holding_reg, &MessageType_ModbusFunctionAddrInfo_fields),
    PB_LAST_FIELD
};

const pb_field_t MessageType_ModbusFunctionInfo_fields[3] = {
    PB_FIELD(  1, UENUM   , REQUIRED, STATIC  , FIRST, MessageType_ModbusFunctionInfo, func_type, func_type, 0),
    PB_FIELD(  2, MESSAGE , REQUIRED, STATIC  , OTHER, MessageType_ModbusFunctionInfo, func_addr_info, func_type, &MessageType_ModbusFunctionAddrInfo_fields),
    PB_LAST_FIELD
};


/* Check that field information fits in pb_field_t */
#if !defined(PB_FIELD_32BIT)
/* If you get an error here, it means that you need to define PB_FIELD_32BIT
 * compile-time option. You can do that in pb.h or on compiler command line.
 * 
 * The reason you need to do this is that some of your messages contain tag
 * numbers or field sizes that are larger than what can fit in 8 or 16 bit
 * field descriptors.
 */
PB_STATIC_ASSERT((pb_membersize(MessageType_ModbusAllFucntionAddrInfo, coil) < 65536 && pb_membersize(MessageType_ModbusAllFucntionAddrInfo, discrepte_input) < 65536 && pb_membersize(MessageType_ModbusAllFucntionAddrInfo, holding_reg) < 65536 && pb_membersize(MessageType_ModbusAllFucntionAddrInfo, input_reg) < 65536 && pb_membersize(MessageType_ModbusFunctionInfo, func_addr_info) < 65536), YOU_MUST_DEFINE_PB_FIELD_32BIT_FOR_MESSAGES_MessageType_ModbusFunctionAddrInfo_MessageType_ModbusAllFucntionAddrInfo_MessageType_ModbusFunctionInfo)
#endif

#if !defined(PB_FIELD_16BIT) && !defined(PB_FIELD_32BIT)
/* If you get an error here, it means that you need to define PB_FIELD_16BIT
 * compile-time option. You can do that in pb.h or on compiler command line.
 * 
 * The reason you need to do this is that some of your messages contain tag
 * numbers or field sizes that are larger than what can fit in the default
 * 8 bit descriptors.
 */
PB_STATIC_ASSERT((pb_membersize(MessageType_ModbusAllFucntionAddrInfo, coil) < 256 && pb_membersize(MessageType_ModbusAllFucntionAddrInfo, discrepte_input) < 256 && pb_membersize(MessageType_ModbusAllFucntionAddrInfo, holding_reg) < 256 && pb_membersize(MessageType_ModbusAllFucntionAddrInfo, input_reg) < 256 && pb_membersize(MessageType_ModbusFunctionInfo, func_addr_info) < 256), YOU_MUST_DEFINE_PB_FIELD_16BIT_FOR_MESSAGES_MessageType_ModbusFunctionAddrInfo_MessageType_ModbusAllFucntionAddrInfo_MessageType_ModbusFunctionInfo)
#endif


/* @@protoc_insertion_point(eof) */
