/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.7-dev at Fri Dec  7 10:47:09 2018. */

#include "modbus_status_info.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t MessageType_ModbusStatusInfo_fields[5] = {
    PB_FIELD(  1, INT32   , REQUIRED, STATIC  , FIRST, MessageType_ModbusStatusInfo, id, id, 0),
    PB_FIELD(  2, INT32   , REQUIRED, STATIC  , OTHER, MessageType_ModbusStatusInfo, address, id, 0),
    PB_FIELD(  3, INT32   , REQUIRED, STATIC  , OTHER, MessageType_ModbusStatusInfo, number, address, 0),
    PB_FIELD(  4, BOOL    , REPEATED, STATIC  , OTHER, MessageType_ModbusStatusInfo, value, number, 0),
    PB_LAST_FIELD
};

const pb_field_t MessageType_ModbusStatusAddrInfo_fields[4] = {
    PB_FIELD(  1, INT32   , REQUIRED, STATIC  , FIRST, MessageType_ModbusStatusAddrInfo, id, id, 0),
    PB_FIELD(  2, INT32   , REQUIRED, STATIC  , OTHER, MessageType_ModbusStatusAddrInfo, address, id, 0),
    PB_FIELD(  3, INT32   , REQUIRED, STATIC  , OTHER, MessageType_ModbusStatusAddrInfo, number, address, 0),
    PB_LAST_FIELD
};

const pb_field_t MessageType_ModbusStatusValueList_fields[2] = {
    PB_FIELD(  1, BOOL    , REPEATED, STATIC  , FIRST, MessageType_ModbusStatusValueList, value, value, 0),
    PB_LAST_FIELD
};


/* Check that field information fits in pb_field_t */
#if !defined(PB_FIELD_16BIT) && !defined(PB_FIELD_32BIT)
#error Field descriptor for MessageType_ModbusStatusValueList.value is too large. Define PB_FIELD_16BIT to fix this.
#endif


/* @@protoc_insertion_point(eof) */
