/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.7-dev at Mon Jul 30 15:41:17 2018. */

#include "pose_euler.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t MessageType_PoseEuler_fields[7] = {
    PB_FIELD(  1, DOUBLE  , REQUIRED, STATIC  , FIRST, MessageType_PoseEuler, x, x, 0),
    PB_FIELD(  2, DOUBLE  , REQUIRED, STATIC  , OTHER, MessageType_PoseEuler, y, x, 0),
    PB_FIELD(  3, DOUBLE  , REQUIRED, STATIC  , OTHER, MessageType_PoseEuler, z, y, 0),
    PB_FIELD(  4, DOUBLE  , REQUIRED, STATIC  , OTHER, MessageType_PoseEuler, a, z, 0),
    PB_FIELD(  5, DOUBLE  , REQUIRED, STATIC  , OTHER, MessageType_PoseEuler, b, a, 0),
    PB_FIELD(  6, DOUBLE  , REQUIRED, STATIC  , OTHER, MessageType_PoseEuler, c, b, 0),
    PB_LAST_FIELD
};


/* On some platforms (such as AVR), double is really float.
 * These are not directly supported by nanopb, but see example_avr_double.
 * To get rid of this error, remove any double fields from your .proto.
 */
PB_STATIC_ASSERT(sizeof(double) == 8, DOUBLE_MUST_BE_8_BYTES)

/* @@protoc_insertion_point(eof) */
