/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.7-dev at Thu Jul 11 16:20:58 2019. */

#include "posture.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t MessageType_Posture_fields[6] = {
    PB_FIELD(  1, INT32   , REQUIRED, STATIC  , FIRST, MessageType_Posture, wrist_flip, wrist_flip, 0),
    PB_FIELD(  2, INT32   , REQUIRED, STATIC  , OTHER, MessageType_Posture, arm_up_down, wrist_flip, 0),
    PB_FIELD(  3, INT32   , REQUIRED, STATIC  , OTHER, MessageType_Posture, arm_back_front, arm_up_down, 0),
    PB_FIELD(  4, INT32   , REQUIRED, STATIC  , OTHER, MessageType_Posture, arm_left_right, arm_back_front, 0),
    PB_FIELD(  5, MESSAGE , REQUIRED, STATIC  , OTHER, MessageType_Posture, turn_cycle, arm_left_right, &MessageType_Int32List_fields),
    PB_LAST_FIELD
};


/* Check that field information fits in pb_field_t */
#if !defined(PB_FIELD_32BIT)
/* If you get an error here, it means that you need to define PB_FIELD_32BIT
 * compile-time option. You can do that in pb.h or on compiler command line.
 * 
 * The reason you need to do this is that some of your messages contain tag
 * numbers or field sizes that are larger than what can fit in 8 or 16 bit
 * field descriptors.
 */
PB_STATIC_ASSERT((pb_membersize(MessageType_Posture, turn_cycle) < 65536), YOU_MUST_DEFINE_PB_FIELD_32BIT_FOR_MESSAGES_MessageType_Posture)
#endif

#if !defined(PB_FIELD_16BIT) && !defined(PB_FIELD_32BIT)
/* If you get an error here, it means that you need to define PB_FIELD_16BIT
 * compile-time option. You can do that in pb.h or on compiler command line.
 * 
 * The reason you need to do this is that some of your messages contain tag
 * numbers or field sizes that are larger than what can fit in the default
 * 8 bit descriptors.
 */
PB_STATIC_ASSERT((pb_membersize(MessageType_Posture, turn_cycle) < 256), YOU_MUST_DEFINE_PB_FIELD_16BIT_FOR_MESSAGES_MessageType_Posture)
#endif


/* @@protoc_insertion_point(eof) */
