/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.7-dev at Mon Jul 30 15:41:17 2018. */

#include "register_sr.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t MessageType_RegisterSR_fields[4] = {
    PB_FIELD(  1, STRING  , REQUIRED, STATIC  , FIRST, MessageType_RegisterSR, value, value, 0),
    PB_FIELD(  2, INT32   , REQUIRED, STATIC  , OTHER, MessageType_RegisterSR, id, value, 0),
    PB_FIELD(  3, STRING  , REQUIRED, STATIC  , OTHER, MessageType_RegisterSR, comment, id, 0),
    PB_LAST_FIELD
};


/* @@protoc_insertion_point(eof) */
