/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.7-dev at Mon Jul 30 15:41:17 2018. */

#include "register_pr.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t MessageType_RegisterPR_fields[6] = {
    PB_FIELD(  1, MESSAGE , OPTIONAL, STATIC  , FIRST, MessageType_RegisterPR, pose, pose, &MessageType_PoseEuler_fields),
    PB_FIELD(  2, MESSAGE , OPTIONAL, STATIC  , OTHER, MessageType_RegisterPR, joint, pose, &MessageType_JointList_fields),
    PB_FIELD(  3, INT32   , REQUIRED, STATIC  , OTHER, MessageType_RegisterPR, type, joint, 0),
    PB_FIELD(  4, INT32   , REQUIRED, STATIC  , OTHER, MessageType_RegisterPR, id, type, 0),
    PB_FIELD(  5, STRING  , REQUIRED, STATIC  , OTHER, MessageType_RegisterPR, comment, id, 0),
    PB_LAST_FIELD
};


/* Check that field information fits in pb_field_t */
#if !defined(PB_FIELD_32BIT)
/* If you get an error here, it means that you need to define PB_FIELD_32BIT
 * compile-time option. You can do that in pb.h or on compiler command line.
 * 
 * The reason you need to do this is that some of your messages contain tag
 * numbers or field sizes that are larger than what can fit in 8 or 16 bit
 * field descriptors.
 */
PB_STATIC_ASSERT((pb_membersize(MessageType_RegisterPR, pose) < 65536 && pb_membersize(MessageType_RegisterPR, joint) < 65536), YOU_MUST_DEFINE_PB_FIELD_32BIT_FOR_MESSAGES_MessageType_RegisterPR)
#endif

#if !defined(PB_FIELD_16BIT) && !defined(PB_FIELD_32BIT)
/* If you get an error here, it means that you need to define PB_FIELD_16BIT
 * compile-time option. You can do that in pb.h or on compiler command line.
 * 
 * The reason you need to do this is that some of your messages contain tag
 * numbers or field sizes that are larger than what can fit in the default
 * 8 bit descriptors.
 */
PB_STATIC_ASSERT((pb_membersize(MessageType_RegisterPR, pose) < 256 && pb_membersize(MessageType_RegisterPR, joint) < 256), YOU_MUST_DEFINE_PB_FIELD_16BIT_FOR_MESSAGES_MessageType_RegisterPR)
#endif


/* @@protoc_insertion_point(eof) */
