/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.7-dev at Tue Jun  4 17:12:47 2019. */

#include "tool_frame.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t MessageType_ToolInfo_fields[6] = {
    PB_FIELD(  1, INT32   , REQUIRED, STATIC  , FIRST, MessageType_ToolInfo, id, id, 0),
    PB_FIELD(  2, STRING  , REQUIRED, STATIC  , OTHER, MessageType_ToolInfo, name, id, 0),
    PB_FIELD(  3, STRING  , REQUIRED, STATIC  , OTHER, MessageType_ToolInfo, comment, name, 0),
    PB_FIELD(  4, INT32   , REQUIRED, STATIC  , OTHER, MessageType_ToolInfo, group_id, comment, 0),
    PB_FIELD(  5, MESSAGE , REQUIRED, STATIC  , OTHER, MessageType_ToolInfo, data, group_id, &MessageType_DoubleList_fields),
    PB_LAST_FIELD
};

const pb_field_t MessageType_ToolSummaryInfo_fields[5] = {
    PB_FIELD(  1, INT32   , REQUIRED, STATIC  , FIRST, MessageType_ToolSummaryInfo, id, id, 0),
    PB_FIELD(  2, STRING  , REQUIRED, STATIC  , OTHER, MessageType_ToolSummaryInfo, name, id, 0),
    PB_FIELD(  3, STRING  , REQUIRED, STATIC  , OTHER, MessageType_ToolSummaryInfo, comment, name, 0),
    PB_FIELD(  4, INT32   , REQUIRED, STATIC  , OTHER, MessageType_ToolSummaryInfo, group_id, comment, 0),
    PB_LAST_FIELD
};

const pb_field_t MessageType_ToolSummaryList_fields[2] = {
    PB_FIELD(  1, MESSAGE , REPEATED, STATIC  , FIRST, MessageType_ToolSummaryList, tool_summary_info, tool_summary_info, &MessageType_ToolSummaryInfo_fields),
    PB_LAST_FIELD
};


/* Check that field information fits in pb_field_t */
#if !defined(PB_FIELD_32BIT)
/* If you get an error here, it means that you need to define PB_FIELD_32BIT
 * compile-time option. You can do that in pb.h or on compiler command line.
 * 
 * The reason you need to do this is that some of your messages contain tag
 * numbers or field sizes that are larger than what can fit in 8 or 16 bit
 * field descriptors.
 */
PB_STATIC_ASSERT((pb_membersize(MessageType_ToolInfo, data) < 65536 && pb_membersize(MessageType_ToolSummaryList, tool_summary_info[0]) < 65536), YOU_MUST_DEFINE_PB_FIELD_32BIT_FOR_MESSAGES_MessageType_ToolInfo_MessageType_ToolSummaryInfo_MessageType_ToolSummaryList)
#endif

#if !defined(PB_FIELD_16BIT) && !defined(PB_FIELD_32BIT)
#error Field descriptor for MessageType_ToolSummaryInfo.comment is too large. Define PB_FIELD_16BIT to fix this.
#endif


/* @@protoc_insertion_point(eof) */
