log_level: 1
install_path: /root/install
config_path: /root/install/share/configuration
runtime_path: /root/install/share/runtime
backup_install_path: /rtm_install/rtm_install.tgz
backup_config_path: /rtm_install/rtm_config.tgz
backup_runtime_path: /rtm_install/rtm_runtime.tgz
restore_install_path: /rtm_restore/rtm_install.tgz
restore_config_path: /rtm_restore/rtm_config.tgz
restore_runtime_path: /rtm_install/rtm_runtime.tgz
password: rtm_2048
#END
