dio_all:
    emltFlag: 1
di[0]:
    emltFlag: 1
    value: 0
di[1]:
    emltFlag: 1
    value: 0
di[2]:
    emltFlag: 1
    value: 0
di[2]:
    emltFlag: 1
    value: 0
di[2]:
    emltFlag: 1
    value: 0
di[2]:
    emltFlag: 1
    value: 0
di[2]:
    emltFlag: 1
    value: 0
di[2]:
    emltFlag: 1
    value: 0
di[2]:
    emltFlag: 1
    value: 0
di[2]:
    emltFlag: 1
    value: 0
di[2]:
    emltFlag: 1
    value: 0
di[2]:
    emltFlag: 1
    value: 0
di[2]:
    emltFlag: 1
    value: 0
di[2]:
    emltFlag: 1
    value: 0
di[2]:
    emltFlag: 1
    value: 0
di[2]:
    emltFlag: 1
    value: 0
di[2]:
    emltFlag: 1
    value: 0
di[2]:
    emltFlag: 1
    value: 0
di[2]:
    emltFlag: 1
    value: 0

