name:
  first:
    sdc:
      - 3.3
      - 1.5
      - 2.01
    sdd: 533.45324
    sda:
      - 1
      - 2
      - 3
      - 4
    new:
      - Jone
      - Dave
      - Tom
  Tome:
    school: Tongji
    age: 20
    male: 1
    tall: 1.75
  second: 45
arm_group:
  cartesian_velocity_max: 4.0
  cartesian_velocity_min: 0.001
  joint_fifo_length_max: 100.0
  cartesian_acceleration_min: 0.001
  cycle_time_max: 0.05
  cartesian_acceleration_max: 16.0
  cycle_time_min: 0.0005
  cycle_time: 0.001
  cartesian_velocity_scaling_factor_min: 0.01
  cartesian_velocity_scaling_factor_max: 1.0
  cartesian_acceleration_scaling_factor_min: 0.01
  cartesian_acceleration_scaling_factor_max: 1.0
  jump_threshold_scaling_factor_min: 0.01
  jump_threshold_scaling_factor_max: 1.0
  test:
    - 0.1
    - 3.2
    - 0.8
kinematics_limit:
  j1:
    home: 0.00
    upper: 3.1416
    lower: -3.1416
    omega_max: 5.5851
    alpha_max: 6.9813
  j2:
    upper: 1.309
    lower: -2.2689
    omega_max: 6.2832
    home: 0.0
    alpha_max: 7.8504
  j3:
    omega_max: 6.9813
    lower: -3.1416
    upper: 3.2289
    home: 0.0
    alpha_max: 13.9626
  j4:
    lower: -3.3161
    upper: 3.3161
    omega_max: 6.2832
    home: 0.0
    alpha_max: 12.5664
  j5:
    lower: -2.2
    upper: 2.2
    omega_max: 4.1888
    home: 0.0
    alpha_max: 10.4720
  j6:
    lower: -6.2832
    upper: 6.2832
    omega_max: 12.5664
    home: 0.0
    alpha_max: 31.4159