/* Automatically generated nanopb header */
/* Generated by nanopb-0.3.7 at Thu Sep 19 11:38:03 2019. */

#ifndef PB_REQUESTMESSAGETYPE_REQUEST_PUBLISH_TOPIC_PB_H_INCLUDED
#define PB_REQUESTMESSAGETYPE_REQUEST_PUBLISH_TOPIC_PB_H_INCLUDED
#include <pb.h>

#include "protocol/request_header.pb.h"

#include "protocol/comm.pb.h"

#include "message_type/publish_topic.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Struct definitions */
typedef struct _RequestMessageType_Topic {
    Request_Header header;
    Comm_Property property;
    MessageType_Topic data;
/* @@protoc_insertion_point(struct:RequestMessageType_Topic) */
} RequestMessageType_Topic;

/* Default values for struct fields */

/* Initializer values for message structs */
#define RequestMessageType_Topic_init_default    {Request_Header_init_default, Comm_Property_init_default, MessageType_Topic_init_default}
#define RequestMessageType_Topic_init_zero       {Request_Header_init_zero, Comm_Property_init_zero, MessageType_Topic_init_zero}

/* Field tags (for use in manual encoding/decoding) */
#define RequestMessageType_Topic_header_tag      1
#define RequestMessageType_Topic_property_tag    2
#define RequestMessageType_Topic_data_tag        3

/* Struct field encoding specification for nanopb */
extern const pb_field_t RequestMessageType_Topic_fields[4];

/* Maximum encoded size of messages (where known) */
#define RequestMessageType_Topic_size            1461

/* Message IDs (where set with "msgid" option) */
#ifdef PB_MSGID

#define REQUEST_PUBLISH_TOPIC_MESSAGES \


#endif

#ifdef __cplusplus
} /* extern "C" */
#endif
/* @@protoc_insertion_point(eof) */

#endif
