/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.7 at Sun Sep 29 18:11:45 2019. */

#include "request_header.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t Request_Header_fields[2] = {
    PB_FIELD(  1, UINT64  , REQUIRED, STATIC  , FIRST, Request_Header, time_stamp, time_stamp, 0),
    PB_LAST_FIELD
};


/* @@protoc_insertion_point(eof) */
