#include "dynamic_alg_rtm_param.h"
#include "common_file_path.h"
#include <string>

using namespace basic_alg;

DynamicAlgRTMParam::DynamicAlgRTMParam():
    file_path_(DYNAMICS_DIR)
{
}

DynamicAlgRTMParam::~DynamicAlgRTMParam()
{

}

bool DynamicAlgRTMParam::loadParam()
{
    file_path_0kg_param_ = file_path_ + DYNAMIC_PARAM_0KG_FILE;
    if (!yaml_help_.loadParamFile(file_path_0kg_param_.c_str())
        || !yaml_help_.getParam("motor_power", motor_power_[PARAM_0KG])
        || !yaml_help_.getParam("motor_torque", motor_torque_[PARAM_0KG])
        || !yaml_help_.getParam("gear_ratio", gear_ratio_[PARAM_0KG])

        || !yaml_help_.getParam("link_0/ZZR", ZZR1[PARAM_0KG])
        || !yaml_help_.getParam("link_0/FS", FS1[PARAM_0KG])
        || !yaml_help_.getParam("link_0/FV", FV1[PARAM_0KG])

        || !yaml_help_.getParam("link_1/XXR", XXR2[PARAM_0KG])
        || !yaml_help_.getParam("link_1/XY", XY2[PARAM_0KG])
        || !yaml_help_.getParam("link_1/XZR", XZR2[PARAM_0KG])
        || !yaml_help_.getParam("link_1/YZ", YZ2[PARAM_0KG])
        || !yaml_help_.getParam("link_1/ZZR", ZZR2[PARAM_0KG])
        || !yaml_help_.getParam("link_1/MXR", MXR2[PARAM_0KG])
        || !yaml_help_.getParam("link_1/MY", MY2[PARAM_0KG])
        || !yaml_help_.getParam("link_1/FS", FS2[PARAM_0KG])
        || !yaml_help_.getParam("link_1/FV", FV2[PARAM_0KG])
        
        || !yaml_help_.getParam("link_2/XXR", XXR3[PARAM_0KG])
        || !yaml_help_.getParam("link_2/XYR", XYR3[PARAM_0KG])
        || !yaml_help_.getParam("link_2/XZ", XZ3[PARAM_0KG])
        || !yaml_help_.getParam("link_2/YZ", YZ3[PARAM_0KG])
        || !yaml_help_.getParam("link_2/ZZR", ZZR3[PARAM_0KG])
        || !yaml_help_.getParam("link_2/MXR", MXR3[PARAM_0KG])
        || !yaml_help_.getParam("link_2/MYR", MYR3[PARAM_0KG])
        || !yaml_help_.getParam("link_2/Im", Im3[PARAM_0KG])
        || !yaml_help_.getParam("link_2/FS", FS3[PARAM_0KG])
        || !yaml_help_.getParam("link_2/FV", FV3[PARAM_0KG])
        
        || !yaml_help_.getParam("link_3/XXR", XXR4[PARAM_0KG])
        || !yaml_help_.getParam("link_3/XY", XY4[PARAM_0KG])
        || !yaml_help_.getParam("link_3/XZ", XZ4[PARAM_0KG])
        || !yaml_help_.getParam("link_3/YZ", YZ4[PARAM_0KG])
        || !yaml_help_.getParam("link_3/ZZR", ZZR4[PARAM_0KG])
        || !yaml_help_.getParam("link_3/MX", MX4[PARAM_0KG])
        || !yaml_help_.getParam("link_3/MYR", MYR4[PARAM_0KG])
        || !yaml_help_.getParam("link_3/Im", Im4[PARAM_0KG])
        || !yaml_help_.getParam("link_3/FS", FS4[PARAM_0KG])
        || !yaml_help_.getParam("link_3/FV", FV4[PARAM_0KG])
        
        || !yaml_help_.getParam("link_4/XXR", XXR5[PARAM_0KG])
        || !yaml_help_.getParam("link_4/XY", XY5[PARAM_0KG])
        || !yaml_help_.getParam("link_4/XZ", XZ5[PARAM_0KG])
        || !yaml_help_.getParam("link_4/YZ", YZ5[PARAM_0KG])
        || !yaml_help_.getParam("link_4/ZZR", ZZR5[PARAM_0KG])
        || !yaml_help_.getParam("link_4/MX", MX5[PARAM_0KG])
        || !yaml_help_.getParam("link_4/MYR", MYR5[PARAM_0KG])
        || !yaml_help_.getParam("link_4/Im", Im5[PARAM_0KG])
        || !yaml_help_.getParam("link_4/FS", FS5[PARAM_0KG])
        || !yaml_help_.getParam("link_4/FV", FV5[PARAM_0KG])
        
        || !yaml_help_.getParam("link_5/XXR", XXR6[PARAM_0KG])
        || !yaml_help_.getParam("link_5/XY", XY6[PARAM_0KG])
        || !yaml_help_.getParam("link_5/XZ", XZ6[PARAM_0KG])
        || !yaml_help_.getParam("link_5/YZ", YZ6[PARAM_0KG])
        || !yaml_help_.getParam("link_5/ZZ", ZZ6[PARAM_0KG])
        || !yaml_help_.getParam("link_5/MX", MX6[PARAM_0KG])
        || !yaml_help_.getParam("link_5/MY", MY6[PARAM_0KG])
        || !yaml_help_.getParam("link_5/Im", Im6[PARAM_0KG])
        || !yaml_help_.getParam("link_5/FS", FS6[PARAM_0KG])
        || !yaml_help_.getParam("link_5/FV", FV6[PARAM_0KG]))
    {
        return false;
    }

    file_path_1kg_param_ = file_path_ + DYNAMIC_PARAM_1KG_FILE;
    if (!yaml_help_.loadParamFile(file_path_1kg_param_.c_str())
        || !yaml_help_.getParam("motor_power", motor_power_[PARAM_1KG])
        || !yaml_help_.getParam("motor_torque", motor_torque_[PARAM_1KG])
        || !yaml_help_.getParam("gear_ratio", gear_ratio_[PARAM_1KG])

        || !yaml_help_.getParam("link_0/ZZR", ZZR1[PARAM_1KG])
        || !yaml_help_.getParam("link_0/FS", FS1[PARAM_1KG])
        || !yaml_help_.getParam("link_0/FV", FV1[PARAM_1KG])

        || !yaml_help_.getParam("link_1/XXR", XXR2[PARAM_1KG])
        || !yaml_help_.getParam("link_1/XY", XY2[PARAM_1KG])
        || !yaml_help_.getParam("link_1/XZR", XZR2[PARAM_1KG])
        || !yaml_help_.getParam("link_1/YZ", YZ2[PARAM_1KG])
        || !yaml_help_.getParam("link_1/ZZR", ZZR2[PARAM_1KG])
        || !yaml_help_.getParam("link_1/MXR", MXR2[PARAM_1KG])
        || !yaml_help_.getParam("link_1/MY", MY2[PARAM_1KG])
        || !yaml_help_.getParam("link_1/FS", FS2[PARAM_1KG])
        || !yaml_help_.getParam("link_1/FV", FV2[PARAM_1KG])
        
        || !yaml_help_.getParam("link_2/XXR", XXR3[PARAM_1KG])
        || !yaml_help_.getParam("link_2/XYR", XYR3[PARAM_1KG])
        || !yaml_help_.getParam("link_2/XZ", XZ3[PARAM_1KG])
        || !yaml_help_.getParam("link_2/YZ", YZ3[PARAM_1KG])
        || !yaml_help_.getParam("link_2/ZZR", ZZR3[PARAM_1KG])
        || !yaml_help_.getParam("link_2/MXR", MXR3[PARAM_1KG])
        || !yaml_help_.getParam("link_2/MYR", MYR3[PARAM_1KG])
        || !yaml_help_.getParam("link_2/Im", Im3[PARAM_1KG])
        || !yaml_help_.getParam("link_2/FS", FS3[PARAM_1KG])
        || !yaml_help_.getParam("link_2/FV", FV3[PARAM_1KG])
        
        || !yaml_help_.getParam("link_3/XXR", XXR4[PARAM_1KG])
        || !yaml_help_.getParam("link_3/XY", XY4[PARAM_1KG])
        || !yaml_help_.getParam("link_3/XZ", XZ4[PARAM_1KG])
        || !yaml_help_.getParam("link_3/YZ", YZ4[PARAM_1KG])
        || !yaml_help_.getParam("link_3/ZZR", ZZR4[PARAM_1KG])
        || !yaml_help_.getParam("link_3/MX", MX4[PARAM_1KG])
        || !yaml_help_.getParam("link_3/MYR", MYR4[PARAM_1KG])
        || !yaml_help_.getParam("link_3/Im", Im4[PARAM_1KG])
        || !yaml_help_.getParam("link_3/FS", FS4[PARAM_1KG])
        || !yaml_help_.getParam("link_3/FV", FV4[PARAM_1KG])
        
        || !yaml_help_.getParam("link_4/XXR", XXR5[PARAM_1KG])
        || !yaml_help_.getParam("link_4/XY", XY5[PARAM_1KG])
        || !yaml_help_.getParam("link_4/XZ", XZ5[PARAM_1KG])
        || !yaml_help_.getParam("link_4/YZ", YZ5[PARAM_1KG])
        || !yaml_help_.getParam("link_4/ZZR", ZZR5[PARAM_1KG])
        || !yaml_help_.getParam("link_4/MX", MX5[PARAM_1KG])
        || !yaml_help_.getParam("link_4/MYR", MYR5[PARAM_1KG])
        || !yaml_help_.getParam("link_4/Im", Im5[PARAM_1KG])
        || !yaml_help_.getParam("link_4/FS", FS5[PARAM_1KG])
        || !yaml_help_.getParam("link_4/FV", FV5[PARAM_1KG])
        
        || !yaml_help_.getParam("link_5/XXR", XXR6[PARAM_1KG])
        || !yaml_help_.getParam("link_5/XY", XY6[PARAM_1KG])
        || !yaml_help_.getParam("link_5/XZ", XZ6[PARAM_1KG])
        || !yaml_help_.getParam("link_5/YZ", YZ6[PARAM_1KG])
        || !yaml_help_.getParam("link_5/ZZ", ZZ6[PARAM_1KG])
        || !yaml_help_.getParam("link_5/MX", MX6[PARAM_1KG])
        || !yaml_help_.getParam("link_5/MY", MY6[PARAM_1KG])
        || !yaml_help_.getParam("link_5/Im", Im6[PARAM_1KG])
        || !yaml_help_.getParam("link_5/FS", FS6[PARAM_1KG])
        || !yaml_help_.getParam("link_5/FV", FV6[PARAM_1KG]))
    {
        return false;
    }

    file_path_3p5kg_param_ = file_path_ + DYNAMIC_PARAM_3p5KG_FILE;
    if (!yaml_help_.loadParamFile(file_path_3p5kg_param_.c_str())
        || !yaml_help_.getParam("motor_power", motor_power_[PARAM_3p5KG])
        || !yaml_help_.getParam("motor_torque", motor_torque_[PARAM_3p5KG])
        || !yaml_help_.getParam("gear_ratio", gear_ratio_[PARAM_3p5KG])

        || !yaml_help_.getParam("link_0/ZZR", ZZR1[PARAM_3p5KG])
        || !yaml_help_.getParam("link_0/FS", FS1[PARAM_3p5KG])
        || !yaml_help_.getParam("link_0/FV", FV1[PARAM_3p5KG])

        || !yaml_help_.getParam("link_1/XXR", XXR2[PARAM_3p5KG])
        || !yaml_help_.getParam("link_1/XY", XY2[PARAM_3p5KG])
        || !yaml_help_.getParam("link_1/XZR", XZR2[PARAM_3p5KG])
        || !yaml_help_.getParam("link_1/YZ", YZ2[PARAM_3p5KG])
        || !yaml_help_.getParam("link_1/ZZR", ZZR2[PARAM_3p5KG])
        || !yaml_help_.getParam("link_1/MXR", MXR2[PARAM_3p5KG])
        || !yaml_help_.getParam("link_1/MY", MY2[PARAM_3p5KG])
        || !yaml_help_.getParam("link_1/FS", FS2[PARAM_3p5KG])
        || !yaml_help_.getParam("link_1/FV", FV2[PARAM_3p5KG])
        
        || !yaml_help_.getParam("link_2/XXR", XXR3[PARAM_3p5KG])
        || !yaml_help_.getParam("link_2/XYR", XYR3[PARAM_3p5KG])
        || !yaml_help_.getParam("link_2/XZ", XZ3[PARAM_3p5KG])
        || !yaml_help_.getParam("link_2/YZ", YZ3[PARAM_3p5KG])
        || !yaml_help_.getParam("link_2/ZZR", ZZR3[PARAM_3p5KG])
        || !yaml_help_.getParam("link_2/MXR", MXR3[PARAM_3p5KG])
        || !yaml_help_.getParam("link_2/MYR", MYR3[PARAM_3p5KG])
        || !yaml_help_.getParam("link_2/Im", Im3[PARAM_3p5KG])
        || !yaml_help_.getParam("link_2/FS", FS3[PARAM_3p5KG])
        || !yaml_help_.getParam("link_2/FV", FV3[PARAM_3p5KG])
        
        || !yaml_help_.getParam("link_3/XXR", XXR4[PARAM_3p5KG])
        || !yaml_help_.getParam("link_3/XY", XY4[PARAM_3p5KG])
        || !yaml_help_.getParam("link_3/XZ", XZ4[PARAM_3p5KG])
        || !yaml_help_.getParam("link_3/YZ", YZ4[PARAM_3p5KG])
        || !yaml_help_.getParam("link_3/ZZR", ZZR4[PARAM_3p5KG])
        || !yaml_help_.getParam("link_3/MX", MX4[PARAM_3p5KG])
        || !yaml_help_.getParam("link_3/MYR", MYR4[PARAM_3p5KG])
        || !yaml_help_.getParam("link_3/Im", Im4[PARAM_3p5KG])
        || !yaml_help_.getParam("link_3/FS", FS4[PARAM_3p5KG])
        || !yaml_help_.getParam("link_3/FV", FV4[PARAM_3p5KG])
        
        || !yaml_help_.getParam("link_4/XXR", XXR5[PARAM_3p5KG])
        || !yaml_help_.getParam("link_4/XY", XY5[PARAM_3p5KG])
        || !yaml_help_.getParam("link_4/XZ", XZ5[PARAM_3p5KG])
        || !yaml_help_.getParam("link_4/YZ", YZ5[PARAM_3p5KG])
        || !yaml_help_.getParam("link_4/ZZR", ZZR5[PARAM_3p5KG])
        || !yaml_help_.getParam("link_4/MX", MX5[PARAM_3p5KG])
        || !yaml_help_.getParam("link_4/MYR", MYR5[PARAM_3p5KG])
        || !yaml_help_.getParam("link_4/Im", Im5[PARAM_3p5KG])
        || !yaml_help_.getParam("link_4/FS", FS5[PARAM_3p5KG])
        || !yaml_help_.getParam("link_4/FV", FV5[PARAM_3p5KG])
        
        || !yaml_help_.getParam("link_5/XXR", XXR6[PARAM_3p5KG])
        || !yaml_help_.getParam("link_5/XY", XY6[PARAM_3p5KG])
        || !yaml_help_.getParam("link_5/XZ", XZ6[PARAM_3p5KG])
        || !yaml_help_.getParam("link_5/YZ", YZ6[PARAM_3p5KG])
        || !yaml_help_.getParam("link_5/ZZ", ZZ6[PARAM_3p5KG])
        || !yaml_help_.getParam("link_5/MX", MX6[PARAM_3p5KG])
        || !yaml_help_.getParam("link_5/MY", MY6[PARAM_3p5KG])
        || !yaml_help_.getParam("link_5/Im", Im6[PARAM_3p5KG])
        || !yaml_help_.getParam("link_5/FS", FS6[PARAM_3p5KG])
        || !yaml_help_.getParam("link_5/FV", FV6[PARAM_3p5KG]))
    {
        return false;
    }

    file_path_7kg_param_ = file_path_ + DYNAMIC_PARAM_7KG_FILE;
    if (!yaml_help_.loadParamFile(file_path_7kg_param_.c_str())
        || !yaml_help_.getParam("motor_power", motor_power_[PARAM_7KG])
        || !yaml_help_.getParam("motor_torque", motor_torque_[PARAM_7KG])
        || !yaml_help_.getParam("gear_ratio", gear_ratio_[PARAM_7KG])

        || !yaml_help_.getParam("link_0/ZZR", ZZR1[PARAM_7KG])
        || !yaml_help_.getParam("link_0/FS", FS1[PARAM_7KG])
        || !yaml_help_.getParam("link_0/FV", FV1[PARAM_7KG])

        || !yaml_help_.getParam("link_1/XXR", XXR2[PARAM_7KG])
        || !yaml_help_.getParam("link_1/XY", XY2[PARAM_7KG])
        || !yaml_help_.getParam("link_1/XZR", XZR2[PARAM_7KG])
        || !yaml_help_.getParam("link_1/YZ", YZ2[PARAM_7KG])
        || !yaml_help_.getParam("link_1/ZZR", ZZR2[PARAM_7KG])
        || !yaml_help_.getParam("link_1/MXR", MXR2[PARAM_7KG])
        || !yaml_help_.getParam("link_1/MY", MY2[PARAM_7KG])
        || !yaml_help_.getParam("link_1/FS", FS2[PARAM_7KG])
        || !yaml_help_.getParam("link_1/FV", FV2[PARAM_7KG])
        
        || !yaml_help_.getParam("link_2/XXR", XXR3[PARAM_7KG])
        || !yaml_help_.getParam("link_2/XYR", XYR3[PARAM_7KG])
        || !yaml_help_.getParam("link_2/XZ", XZ3[PARAM_7KG])
        || !yaml_help_.getParam("link_2/YZ", YZ3[PARAM_7KG])
        || !yaml_help_.getParam("link_2/ZZR", ZZR3[PARAM_7KG])
        || !yaml_help_.getParam("link_2/MXR", MXR3[PARAM_7KG])
        || !yaml_help_.getParam("link_2/MYR", MYR3[PARAM_7KG])
        || !yaml_help_.getParam("link_2/Im", Im3[PARAM_7KG])
        || !yaml_help_.getParam("link_2/FS", FS3[PARAM_7KG])
        || !yaml_help_.getParam("link_2/FV", FV3[PARAM_7KG])
        
        || !yaml_help_.getParam("link_3/XXR", XXR4[PARAM_7KG])
        || !yaml_help_.getParam("link_3/XY", XY4[PARAM_7KG])
        || !yaml_help_.getParam("link_3/XZ", XZ4[PARAM_7KG])
        || !yaml_help_.getParam("link_3/YZ", YZ4[PARAM_7KG])
        || !yaml_help_.getParam("link_3/ZZR", ZZR4[PARAM_7KG])
        || !yaml_help_.getParam("link_3/MX", MX4[PARAM_7KG])
        || !yaml_help_.getParam("link_3/MYR", MYR4[PARAM_7KG])
        || !yaml_help_.getParam("link_3/Im", Im4[PARAM_7KG])
        || !yaml_help_.getParam("link_3/FS", FS4[PARAM_7KG])
        || !yaml_help_.getParam("link_3/FV", FV4[PARAM_7KG])
        
        || !yaml_help_.getParam("link_4/XXR", XXR5[PARAM_7KG])
        || !yaml_help_.getParam("link_4/XY", XY5[PARAM_7KG])
        || !yaml_help_.getParam("link_4/XZ", XZ5[PARAM_7KG])
        || !yaml_help_.getParam("link_4/YZ", YZ5[PARAM_7KG])
        || !yaml_help_.getParam("link_4/ZZR", ZZR5[PARAM_7KG])
        || !yaml_help_.getParam("link_4/MX", MX5[PARAM_7KG])
        || !yaml_help_.getParam("link_4/MYR", MYR5[PARAM_7KG])
        || !yaml_help_.getParam("link_4/Im", Im5[PARAM_7KG])
        || !yaml_help_.getParam("link_4/FS", FS5[PARAM_7KG])
        || !yaml_help_.getParam("link_4/FV", FV5[PARAM_7KG])
        
        || !yaml_help_.getParam("link_5/XXR", XXR6[PARAM_7KG])
        || !yaml_help_.getParam("link_5/XY", XY6[PARAM_7KG])
        || !yaml_help_.getParam("link_5/XZ", XZ6[PARAM_7KG])
        || !yaml_help_.getParam("link_5/YZ", YZ6[PARAM_7KG])
        || !yaml_help_.getParam("link_5/ZZ", ZZ6[PARAM_7KG])
        || !yaml_help_.getParam("link_5/MX", MX6[PARAM_7KG])
        || !yaml_help_.getParam("link_5/MY", MY6[PARAM_7KG])
        || !yaml_help_.getParam("link_5/Im", Im6[PARAM_7KG])
        || !yaml_help_.getParam("link_5/FS", FS6[PARAM_7KG])
        || !yaml_help_.getParam("link_5/FV", FV6[PARAM_7KG]))
    {
        return false;
    }

    return true;
}

bool DynamicAlgRTMParam::saveParam()
{
    if(!yaml_help_.setParam("motor_power", motor_power_[PARAM_0KG])
        || !yaml_help_.setParam("motor_torque", motor_torque_[PARAM_0KG])
        || !yaml_help_.setParam("gear_ratio", gear_ratio_[PARAM_0KG])

        || !yaml_help_.setParam("link_0/ZZR", ZZR1[PARAM_0KG])
        || !yaml_help_.setParam("link_0/FS", FS1[PARAM_0KG])
        || !yaml_help_.setParam("link_0/FV", FV1[PARAM_0KG])

        || !yaml_help_.setParam("link_1/XXR", XXR2[PARAM_0KG])
        || !yaml_help_.setParam("link_1/XY", XY2[PARAM_0KG])
        || !yaml_help_.setParam("link_1/XZR", XZR2[PARAM_0KG])
        || !yaml_help_.setParam("link_1/YZ", YZ2[PARAM_0KG])
        || !yaml_help_.setParam("link_1/ZZR", ZZR2[PARAM_0KG])
        || !yaml_help_.setParam("link_1/MXR", MXR2[PARAM_0KG])
        || !yaml_help_.setParam("link_1/MY", MY2[PARAM_0KG])
        || !yaml_help_.setParam("link_1/FS", FS2[PARAM_0KG])
        || !yaml_help_.setParam("link_1/FV", FV2[PARAM_0KG])
        
        || !yaml_help_.setParam("link_2/XXR", XXR3[PARAM_0KG])
        || !yaml_help_.setParam("link_2/XYR", XYR3[PARAM_0KG])
        || !yaml_help_.setParam("link_2/XZ", XZ3[PARAM_0KG])
        || !yaml_help_.setParam("link_2/YZ", YZ3[PARAM_0KG])
        || !yaml_help_.setParam("link_2/ZZR", ZZR3[PARAM_0KG])
        || !yaml_help_.setParam("link_2/MXR", MXR3[PARAM_0KG])
        || !yaml_help_.setParam("link_2/MYR", MYR3[PARAM_0KG])
        || !yaml_help_.setParam("link_2/Im", Im3[PARAM_0KG])
        || !yaml_help_.setParam("link_2/FS", FS3[PARAM_0KG])
        || !yaml_help_.setParam("link_2/FV", FV3[PARAM_0KG])
        
        || !yaml_help_.setParam("link_3/XXR", XXR4[PARAM_0KG])
        || !yaml_help_.setParam("link_3/XY", XY4[PARAM_0KG])
        || !yaml_help_.setParam("link_3/XZ", XZ4[PARAM_0KG])
        || !yaml_help_.setParam("link_3/YZ", YZ4[PARAM_0KG])
        || !yaml_help_.setParam("link_3/ZZR", ZZR4[PARAM_0KG])
        || !yaml_help_.setParam("link_3/MX", MX4[PARAM_0KG])
        || !yaml_help_.setParam("link_3/MYR", MYR4[PARAM_0KG])
        || !yaml_help_.setParam("link_3/Im", Im4[PARAM_0KG])
        || !yaml_help_.setParam("link_3/FS", FS4[PARAM_0KG])
        || !yaml_help_.setParam("link_3/FV", FV4[PARAM_0KG])
        
        || !yaml_help_.setParam("link_4/XXR", XXR5[PARAM_0KG])
        || !yaml_help_.setParam("link_4/XY", XY5[PARAM_0KG])
        || !yaml_help_.setParam("link_4/XZ", XZ5[PARAM_0KG])
        || !yaml_help_.setParam("link_4/YZ", YZ5[PARAM_0KG])
        || !yaml_help_.setParam("link_4/ZZR", ZZR5[PARAM_0KG])
        || !yaml_help_.setParam("link_4/MX", MX5[PARAM_0KG])
        || !yaml_help_.setParam("link_4/MYR", MYR5[PARAM_0KG])
        || !yaml_help_.setParam("link_4/Im", Im5[PARAM_0KG])
        || !yaml_help_.setParam("link_4/FS", FS5[PARAM_0KG])
        || !yaml_help_.setParam("link_4/FV", FV5[PARAM_0KG])
        
        || !yaml_help_.setParam("link_5/XXR", XXR6[PARAM_0KG])
        || !yaml_help_.setParam("link_5/XY", XY6[PARAM_0KG])
        || !yaml_help_.setParam("link_5/XZ", XZ6[PARAM_0KG])
        || !yaml_help_.setParam("link_5/YZ", YZ6[PARAM_0KG])
        || !yaml_help_.setParam("link_5/ZZ", ZZ6[PARAM_0KG])
        || !yaml_help_.setParam("link_5/MX", MX6[PARAM_0KG])
        || !yaml_help_.setParam("link_5/MYR", MY6[PARAM_0KG])
        || !yaml_help_.setParam("link_5/Im", Im6[PARAM_0KG])
        || !yaml_help_.setParam("link_5/FS", FS6[PARAM_0KG])
        || !yaml_help_.setParam("link_5/FV", FV6[PARAM_0KG])

        || !yaml_help_.dumpParamFile(file_path_0kg_param_.c_str()))
    {
        return false;
    }

    if(!yaml_help_.setParam("motor_power", motor_power_[PARAM_1KG])
        || !yaml_help_.setParam("motor_torque", motor_torque_[PARAM_1KG])
        || !yaml_help_.setParam("gear_ratio", gear_ratio_[PARAM_1KG])

        || !yaml_help_.setParam("link_0/ZZR", ZZR1[PARAM_1KG])
        || !yaml_help_.setParam("link_0/FS", FS1[PARAM_1KG])
        || !yaml_help_.setParam("link_0/FV", FV1[PARAM_1KG])

        || !yaml_help_.setParam("link_1/XXR", XXR2[PARAM_1KG])
        || !yaml_help_.setParam("link_1/XY", XY2[PARAM_1KG])
        || !yaml_help_.setParam("link_1/XZR", XZR2[PARAM_1KG])
        || !yaml_help_.setParam("link_1/YZ", YZ2[PARAM_1KG])
        || !yaml_help_.setParam("link_1/ZZR", ZZR2[PARAM_1KG])
        || !yaml_help_.setParam("link_1/MXR", MXR2[PARAM_1KG])
        || !yaml_help_.setParam("link_1/MY", MY2[PARAM_1KG])
        || !yaml_help_.setParam("link_1/FS", FS2[PARAM_1KG])
        || !yaml_help_.setParam("link_1/FV", FV2[PARAM_1KG])
        
        || !yaml_help_.setParam("link_2/XXR", XXR3[PARAM_1KG])
        || !yaml_help_.setParam("link_2/XYR", XYR3[PARAM_1KG])
        || !yaml_help_.setParam("link_2/XZ", XZ3[PARAM_1KG])
        || !yaml_help_.setParam("link_2/YZ", YZ3[PARAM_1KG])
        || !yaml_help_.setParam("link_2/ZZR", ZZR3[PARAM_1KG])
        || !yaml_help_.setParam("link_2/MXR", MXR3[PARAM_1KG])
        || !yaml_help_.setParam("link_2/MYR", MYR3[PARAM_1KG])
        || !yaml_help_.setParam("link_2/Im", Im3[PARAM_1KG])
        || !yaml_help_.setParam("link_2/FS", FS3[PARAM_1KG])
        || !yaml_help_.setParam("link_2/FV", FV3[PARAM_1KG])
        
        || !yaml_help_.setParam("link_3/XXR", XXR4[PARAM_1KG])
        || !yaml_help_.setParam("link_3/XY", XY4[PARAM_1KG])
        || !yaml_help_.setParam("link_3/XZ", XZ4[PARAM_1KG])
        || !yaml_help_.setParam("link_3/YZ", YZ4[PARAM_1KG])
        || !yaml_help_.setParam("link_3/ZZR", ZZR4[PARAM_1KG])
        || !yaml_help_.setParam("link_3/MX", MX4[PARAM_1KG])
        || !yaml_help_.setParam("link_3/MYR", MYR4[PARAM_1KG])
        || !yaml_help_.setParam("link_3/Im", Im4[PARAM_1KG])
        || !yaml_help_.setParam("link_3/FS", FS4[PARAM_1KG])
        || !yaml_help_.setParam("link_3/FV", FV4[PARAM_1KG])
        
        || !yaml_help_.setParam("link_4/XXR", XXR5[PARAM_1KG])
        || !yaml_help_.setParam("link_4/XY", XY5[PARAM_1KG])
        || !yaml_help_.setParam("link_4/XZ", XZ5[PARAM_1KG])
        || !yaml_help_.setParam("link_4/YZ", YZ5[PARAM_1KG])
        || !yaml_help_.setParam("link_4/ZZR", ZZR5[PARAM_1KG])
        || !yaml_help_.setParam("link_4/MX", MX5[PARAM_1KG])
        || !yaml_help_.setParam("link_4/MYR", MYR5[PARAM_1KG])
        || !yaml_help_.setParam("link_4/Im", Im5[PARAM_1KG])
        || !yaml_help_.setParam("link_4/FS", FS5[PARAM_1KG])
        || !yaml_help_.setParam("link_4/FV", FV5[PARAM_1KG])
        
        || !yaml_help_.setParam("link_5/XXR", XXR6[PARAM_1KG])
        || !yaml_help_.setParam("link_5/XY", XY6[PARAM_1KG])
        || !yaml_help_.setParam("link_5/XZ", XZ6[PARAM_1KG])
        || !yaml_help_.setParam("link_5/YZ", YZ6[PARAM_1KG])
        || !yaml_help_.setParam("link_5/ZZ", ZZ6[PARAM_1KG])
        || !yaml_help_.setParam("link_5/MX", MX6[PARAM_1KG])
        || !yaml_help_.setParam("link_5/MYR", MY6[PARAM_1KG])
        || !yaml_help_.setParam("link_5/Im", Im6[PARAM_1KG])
        || !yaml_help_.setParam("link_5/FS", FS6[PARAM_1KG])
        || !yaml_help_.setParam("link_5/FV", FV6[PARAM_1KG])

        || !yaml_help_.dumpParamFile(file_path_1kg_param_.c_str()))
    {
        return false;
    }

    if(!yaml_help_.setParam("motor_power", motor_power_[PARAM_3p5KG])
        || !yaml_help_.setParam("motor_torque", motor_torque_[PARAM_3p5KG])
        || !yaml_help_.setParam("gear_ratio", gear_ratio_[PARAM_3p5KG])

        || !yaml_help_.setParam("link_0/ZZR", ZZR1[PARAM_3p5KG])
        || !yaml_help_.setParam("link_0/FS", FS1[PARAM_3p5KG])
        || !yaml_help_.setParam("link_0/FV", FV1[PARAM_3p5KG])

        || !yaml_help_.setParam("link_1/XXR", XXR2[PARAM_3p5KG])
        || !yaml_help_.setParam("link_1/XY", XY2[PARAM_3p5KG])
        || !yaml_help_.setParam("link_1/XZR", XZR2[PARAM_3p5KG])
        || !yaml_help_.setParam("link_1/YZ", YZ2[PARAM_3p5KG])
        || !yaml_help_.setParam("link_1/ZZR", ZZR2[PARAM_3p5KG])
        || !yaml_help_.setParam("link_1/MXR", MXR2[PARAM_3p5KG])
        || !yaml_help_.setParam("link_1/MY", MY2[PARAM_3p5KG])
        || !yaml_help_.setParam("link_1/FS", FS2[PARAM_3p5KG])
        || !yaml_help_.setParam("link_1/FV", FV2[PARAM_3p5KG])
        
        || !yaml_help_.setParam("link_2/XXR", XXR3[PARAM_3p5KG])
        || !yaml_help_.setParam("link_2/XYR", XYR3[PARAM_3p5KG])
        || !yaml_help_.setParam("link_2/XZ", XZ3[PARAM_3p5KG])
        || !yaml_help_.setParam("link_2/YZ", YZ3[PARAM_3p5KG])
        || !yaml_help_.setParam("link_2/ZZR", ZZR3[PARAM_3p5KG])
        || !yaml_help_.setParam("link_2/MXR", MXR3[PARAM_3p5KG])
        || !yaml_help_.setParam("link_2/MYR", MYR3[PARAM_3p5KG])
        || !yaml_help_.setParam("link_2/Im", Im3[PARAM_3p5KG])
        || !yaml_help_.setParam("link_2/FS", FS3[PARAM_3p5KG])
        || !yaml_help_.setParam("link_2/FV", FV3[PARAM_3p5KG])
        
        || !yaml_help_.setParam("link_3/XXR", XXR4[PARAM_3p5KG])
        || !yaml_help_.setParam("link_3/XY", XY4[PARAM_3p5KG])
        || !yaml_help_.setParam("link_3/XZ", XZ4[PARAM_3p5KG])
        || !yaml_help_.setParam("link_3/YZ", YZ4[PARAM_3p5KG])
        || !yaml_help_.setParam("link_3/ZZR", ZZR4[PARAM_3p5KG])
        || !yaml_help_.setParam("link_3/MX", MX4[PARAM_3p5KG])
        || !yaml_help_.setParam("link_3/MYR", MYR4[PARAM_3p5KG])
        || !yaml_help_.setParam("link_3/Im", Im4[PARAM_3p5KG])
        || !yaml_help_.setParam("link_3/FS", FS4[PARAM_3p5KG])
        || !yaml_help_.setParam("link_3/FV", FV4[PARAM_3p5KG])
        
        || !yaml_help_.setParam("link_4/XXR", XXR5[PARAM_3p5KG])
        || !yaml_help_.setParam("link_4/XY", XY5[PARAM_3p5KG])
        || !yaml_help_.setParam("link_4/XZ", XZ5[PARAM_3p5KG])
        || !yaml_help_.setParam("link_4/YZ", YZ5[PARAM_3p5KG])
        || !yaml_help_.setParam("link_4/ZZR", ZZR5[PARAM_3p5KG])
        || !yaml_help_.setParam("link_4/MX", MX5[PARAM_3p5KG])
        || !yaml_help_.setParam("link_4/MYR", MYR5[PARAM_3p5KG])
        || !yaml_help_.setParam("link_4/Im", Im5[PARAM_3p5KG])
        || !yaml_help_.setParam("link_4/FS", FS5[PARAM_3p5KG])
        || !yaml_help_.setParam("link_4/FV", FV5[PARAM_3p5KG])
        
        || !yaml_help_.setParam("link_5/XXR", XXR6[PARAM_3p5KG])
        || !yaml_help_.setParam("link_5/XY", XY6[PARAM_3p5KG])
        || !yaml_help_.setParam("link_5/XZ", XZ6[PARAM_3p5KG])
        || !yaml_help_.setParam("link_5/YZ", YZ6[PARAM_3p5KG])
        || !yaml_help_.setParam("link_5/ZZ", ZZ6[PARAM_3p5KG])
        || !yaml_help_.setParam("link_5/MX", MX6[PARAM_3p5KG])
        || !yaml_help_.setParam("link_5/MYR", MY6[PARAM_3p5KG])
        || !yaml_help_.setParam("link_5/Im", Im6[PARAM_3p5KG])
        || !yaml_help_.setParam("link_5/FS", FS6[PARAM_3p5KG])
        || !yaml_help_.setParam("link_5/FV", FV6[PARAM_3p5KG])

        || !yaml_help_.dumpParamFile(file_path_3p5kg_param_.c_str()))
    {
        return false;
    }

    if(!yaml_help_.setParam("motor_power", motor_power_[PARAM_7KG])
        || !yaml_help_.setParam("motor_torque", motor_torque_[PARAM_7KG])
        || !yaml_help_.setParam("gear_ratio", gear_ratio_[PARAM_7KG])

        || !yaml_help_.setParam("link_0/ZZR", ZZR1[PARAM_7KG])
        || !yaml_help_.setParam("link_0/FS", FS1[PARAM_7KG])
        || !yaml_help_.setParam("link_0/FV", FV1[PARAM_7KG])

        || !yaml_help_.setParam("link_1/XXR", XXR2[PARAM_7KG])
        || !yaml_help_.setParam("link_1/XY", XY2[PARAM_7KG])
        || !yaml_help_.setParam("link_1/XZR", XZR2[PARAM_7KG])
        || !yaml_help_.setParam("link_1/YZ", YZ2[PARAM_7KG])
        || !yaml_help_.setParam("link_1/ZZR", ZZR2[PARAM_7KG])
        || !yaml_help_.setParam("link_1/MXR", MXR2[PARAM_7KG])
        || !yaml_help_.setParam("link_1/MY", MY2[PARAM_7KG])
        || !yaml_help_.setParam("link_1/FS", FS2[PARAM_7KG])
        || !yaml_help_.setParam("link_1/FV", FV2[PARAM_7KG])
        
        || !yaml_help_.setParam("link_2/XXR", XXR3[PARAM_7KG])
        || !yaml_help_.setParam("link_2/XYR", XYR3[PARAM_7KG])
        || !yaml_help_.setParam("link_2/XZ", XZ3[PARAM_7KG])
        || !yaml_help_.setParam("link_2/YZ", YZ3[PARAM_7KG])
        || !yaml_help_.setParam("link_2/ZZR", ZZR3[PARAM_7KG])
        || !yaml_help_.setParam("link_2/MXR", MXR3[PARAM_7KG])
        || !yaml_help_.setParam("link_2/MYR", MYR3[PARAM_7KG])
        || !yaml_help_.setParam("link_2/Im", Im3[PARAM_7KG])
        || !yaml_help_.setParam("link_2/FS", FS3[PARAM_7KG])
        || !yaml_help_.setParam("link_2/FV", FV3[PARAM_7KG])
        
        || !yaml_help_.setParam("link_3/XXR", XXR4[PARAM_7KG])
        || !yaml_help_.setParam("link_3/XY", XY4[PARAM_7KG])
        || !yaml_help_.setParam("link_3/XZ", XZ4[PARAM_7KG])
        || !yaml_help_.setParam("link_3/YZ", YZ4[PARAM_7KG])
        || !yaml_help_.setParam("link_3/ZZR", ZZR4[PARAM_7KG])
        || !yaml_help_.setParam("link_3/MX", MX4[PARAM_7KG])
        || !yaml_help_.setParam("link_3/MYR", MYR4[PARAM_7KG])
        || !yaml_help_.setParam("link_3/Im", Im4[PARAM_7KG])
        || !yaml_help_.setParam("link_3/FS", FS4[PARAM_7KG])
        || !yaml_help_.setParam("link_3/FV", FV4[PARAM_7KG])
        
        || !yaml_help_.setParam("link_4/XXR", XXR5[PARAM_7KG])
        || !yaml_help_.setParam("link_4/XY", XY5[PARAM_7KG])
        || !yaml_help_.setParam("link_4/XZ", XZ5[PARAM_7KG])
        || !yaml_help_.setParam("link_4/YZ", YZ5[PARAM_7KG])
        || !yaml_help_.setParam("link_4/ZZR", ZZR5[PARAM_7KG])
        || !yaml_help_.setParam("link_4/MX", MX5[PARAM_7KG])
        || !yaml_help_.setParam("link_4/MYR", MYR5[PARAM_7KG])
        || !yaml_help_.setParam("link_4/Im", Im5[PARAM_7KG])
        || !yaml_help_.setParam("link_4/FS", FS5[PARAM_7KG])
        || !yaml_help_.setParam("link_4/FV", FV5[PARAM_7KG])
        
        || !yaml_help_.setParam("link_5/XXR", XXR6[PARAM_7KG])
        || !yaml_help_.setParam("link_5/XY", XY6[PARAM_7KG])
        || !yaml_help_.setParam("link_5/XZ", XZ6[PARAM_7KG])
        || !yaml_help_.setParam("link_5/YZ", YZ6[PARAM_7KG])
        || !yaml_help_.setParam("link_5/ZZ", ZZ6[PARAM_7KG])
        || !yaml_help_.setParam("link_5/MX", MX6[PARAM_7KG])
        || !yaml_help_.setParam("link_5/MYR", MY6[PARAM_7KG])
        || !yaml_help_.setParam("link_5/Im", Im6[PARAM_7KG])
        || !yaml_help_.setParam("link_5/FS", FS6[PARAM_7KG])
        || !yaml_help_.setParam("link_5/FV", FV6[PARAM_7KG])

        || !yaml_help_.dumpParamFile(file_path_7kg_param_.c_str()))
    {
        return false;
    }

    return true;
}

