/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.7-dev at Mon Apr 23 15:38:44 2018. */

#include "version.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t base_types_VersionInfo_fields[3] = {
    PB_FIELD(  1, INT32   , REQUIRED, STATIC  , FIRST, base_types_VersionInfo, major, major, 0),
    PB_FIELD(  2, INT32   , REQUIRED, STATIC  , OTHER, base_types_VersionInfo, minor, major, 0),
    PB_LAST_FIELD
};


/* @@protoc_insertion_point(eof) */
