/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.7 at Thu Sep 19 13:40:59 2019. */

#include "response_uint64_group_status_bool.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t ResponseMessageType_Uint64_GroupStatus_Bool_fields[6] = {
    PB_FIELD(  1, MESSAGE , REQUIRED, STATIC  , FIRST, ResponseMessageType_Uint64_GroupStatus_Bool, header, header, &Response_Header_fields),
    PB_FIELD(  2, MESSAGE , REQUIRED, STATIC  , OTHER, ResponseMessageType_Uint64_GroupStatus_Bool, property, header, &Comm_Property_fields),
    PB_FIELD(  3, MESSAGE , REQUIRED, STATIC  , OTHER, ResponseMessageType_Uint64_GroupStatus_Bool, error_code, property, &MessageType_Uint64_fields),
    PB_FIELD(  4, UENUM   , REQUIRED, STATIC  , OTHER, ResponseMessageType_Uint64_GroupStatus_Bool, data1, error_code, 0),
    PB_FIELD(  5, MESSAGE , REQUIRED, STATIC  , OTHER, ResponseMessageType_Uint64_GroupStatus_Bool, data2, data1, &MessageType_Bool_fields),
    PB_LAST_FIELD
};


/* Check that field information fits in pb_field_t */
#if !defined(PB_FIELD_32BIT)
/* If you get an error here, it means that you need to define PB_FIELD_32BIT
 * compile-time option. You can do that in pb.h or on compiler command line.
 * 
 * The reason you need to do this is that some of your messages contain tag
 * numbers or field sizes that are larger than what can fit in 8 or 16 bit
 * field descriptors.
 */
PB_STATIC_ASSERT((pb_membersize(ResponseMessageType_Uint64_GroupStatus_Bool, header) < 65536 && pb_membersize(ResponseMessageType_Uint64_GroupStatus_Bool, property) < 65536 && pb_membersize(ResponseMessageType_Uint64_GroupStatus_Bool, error_code) < 65536 && pb_membersize(ResponseMessageType_Uint64_GroupStatus_Bool, data2) < 65536), YOU_MUST_DEFINE_PB_FIELD_32BIT_FOR_MESSAGES_ResponseMessageType_Uint64_GroupStatus_Bool)
#endif

#if !defined(PB_FIELD_16BIT) && !defined(PB_FIELD_32BIT)
/* If you get an error here, it means that you need to define PB_FIELD_16BIT
 * compile-time option. You can do that in pb.h or on compiler command line.
 * 
 * The reason you need to do this is that some of your messages contain tag
 * numbers or field sizes that are larger than what can fit in the default
 * 8 bit descriptors.
 */
PB_STATIC_ASSERT((pb_membersize(ResponseMessageType_Uint64_GroupStatus_Bool, header) < 256 && pb_membersize(ResponseMessageType_Uint64_GroupStatus_Bool, property) < 256 && pb_membersize(ResponseMessageType_Uint64_GroupStatus_Bool, error_code) < 256 && pb_membersize(ResponseMessageType_Uint64_GroupStatus_Bool, data2) < 256), YOU_MUST_DEFINE_PB_FIELD_16BIT_FOR_MESSAGES_ResponseMessageType_Uint64_GroupStatus_Bool)
#endif


/* @@protoc_insertion_point(eof) */
