dio_all:
    emltFlag: 1
di[0]:
    emltFlag: 1
    value: 0
di[1]:
    emltFlag: 1
    value: 0
di[2]:
    emltFlag: 1
    value: 0
di[3]:
    emltFlag: 1
    value: 0
di[4]:
    emltFlag: 1
    value: 0
di[5]:
    emltFlag: 1
    value: 0
di[6]:
    emltFlag: 1
    value: 0
di[7]:
    emltFlag: 1
    value: 0
do[0]:
    emltFlag: 1
    value: 0
do[1]:
    emltFlag: 1
    value: 0
do[2]:
    emltFlag: 1
    value: 0
do[3]:
    emltFlag: 1
    value: 0
do[4]:
    emltFlag: 1
    value: 0
do[5]:
    emltFlag: 1
    value: 0
do[6]:
    emltFlag: 1
    value: 0
do[7]:
    emltFlag: 1
    value: 0
uio_all:
    emltFlag: 1
ui[0]:
    emltFlag: 1
    value: 0
ui[1]:
    emltFlag: 1
    value: 0
ui[2]:
    emltFlag: 1
    value: 0
ui[3]:
    emltFlag: 1
    value: 0
ui[4]:
    emltFlag: 1
    value: 0
ui[5]:
    emltFlag: 1
    value: 0
ui[6]:
    emltFlag: 1
    value: 0
ui[7]:
    emltFlag: 1
    value: 0
uo[0]:
    emltFlag: 1
    value: 0
uo[1]:
    emltFlag: 1
    value: 0
uo[2]:
    emltFlag: 1
    value: 0
uo[3]:
    emltFlag: 1
    value: 0
uo[4]:
    emltFlag: 1
    value: 0
uo[5]:
    emltFlag: 1
    value: 0
uo[6]:
    emltFlag: 1
    value: 0
uo[7]:
    emltFlag: 1
    value: 0
