PR1:
    id: 1
    is_valid: false
    name: default
    comment: default
    group_id: -1
    pos_type: 0
    pos1: 0.0
    pos2: 0.0 
    pos3: 0.0 
    pos4: 0.0 
    pos5: 0.0 
    pos6: 0.0 
    pos7: 0.0 
    pos8: 0.0 
    pos9: 0.0 
    posture1: 1
    posture2: 1
    posture3: -1
    posture4: 0
PR2:
    id: 2
    is_valid: false
    name: default
    comment: default
    group_id: -1
    pos_type: 0
    pos1: 0.0
    pos2: 0.0 
    pos3: 0.0 
    pos4: 0.0 
    pos5: 0.0 
    pos6: 0.0 
    pos7: 0.0 
    pos8: 0.0 
    pos9: 0.0 
    posture1: 1
    posture2: 1
    posture3: -1
    posture4: 0
PR3:
    id: 3
    is_valid: false
    name: default
    comment: default
    group_id: -1
    pos_type: 0
    pos1: 0.0
    pos2: 0.0 
    pos3: 0.0 
    pos4: 0.0 
    pos5: 0.0 
    pos6: 0.0 
    pos7: 0.0 
    pos8: 0.0 
    pos9: 0.0 
    posture1: 1
    posture2: 1
    posture3: -1
    posture4: 0
PR4:
    id: 4
    is_valid: false
    name: default
    comment: default
    group_id: -1
    pos_type: 0
    pos1: 0.0
    pos2: 0.0 
    pos3: 0.0 
    pos4: 0.0 
    pos5: 0.0 
    pos6: 0.0 
    pos7: 0.0 
    pos8: 0.0 
    pos9: 0.0 
    posture1: 1
    posture2: 1
    posture3: -1
    posture4: 0
PR5:
    id: 5
    is_valid: false
    name: default
    comment: default
    group_id: -1
    pos_type: 0
    pos1: 0.0
    pos2: 0.0 
    pos3: 0.0 
    pos4: 0.0 
    pos5: 0.0 
    pos6: 0.0 
    pos7: 0.0 
    pos8: 0.0 
    pos9: 0.0 
    posture1: 1
    posture2: 1
    posture3: -1
    posture4: 0
PR6:
    id: 6
    is_valid: false
    name: default
    comment: default
    group_id: -1
    pos_type: 0
    pos1: 0.0
    pos2: 0.0 
    pos3: 0.0 
    pos4: 0.0 
    pos5: 0.0 
    pos6: 0.0 
    pos7: 0.0 
    pos8: 0.0 
    pos9: 0.0 
    posture1: 1
    posture2: 1
    posture3: -1
    posture4: 0
PR7:
    id: 7
    is_valid: false
    name: default
    comment: default
    group_id: -1
    pos_type: 0
    pos1: 0.0
    pos2: 0.0 
    pos3: 0.0 
    pos4: 0.0 
    pos5: 0.0 
    pos6: 0.0 
    pos7: 0.0 
    pos8: 0.0 
    pos9: 0.0 
    posture1: 1
    posture2: 1
    posture3: -1
    posture4: 0
PR8:
    id: 8
    is_valid: false
    name: default
    comment: default
    group_id: -1
    pos_type: 0
    pos1: 0.0
    pos2: 0.0 
    pos3: 0.0 
    pos4: 0.0 
    pos5: 0.0 
    pos6: 0.0 
    pos7: 0.0 
    pos8: 0.0 
    pos9: 0.0 
    posture1: 1
    posture2: 1
    posture3: -1
    posture4: 0
PR9:
    id: 9
    is_valid: false
    name: default
    comment: default
    group_id: -1
    pos_type: 0
    pos1: 0.0
    pos2: 0.0 
    pos3: 0.0 
    pos4: 0.0 
    pos5: 0.0 
    pos6: 0.0 
    pos7: 0.0 
    pos8: 0.0 
    pos9: 0.0 
    posture1: 1
    posture2: 1
    posture3: -1
    posture4: 0
PR10:
    id: 10
    is_valid: false
    name: default
    comment: default
    group_id: -1
    pos_type: 0
    pos1: 0.0
    pos2: 0.0 
    pos3: 0.0 
    pos4: 0.0 
    pos5: 0.0 
    pos6: 0.0 
    pos7: 0.0 
    pos8: 0.0 
    pos9: 0.0 
    posture1: 1
    posture2: 1
    posture3: -1
    posture4: 0
PR11:
    id: 11
    is_valid: false
    name: default
    comment: default
    group_id: -1
    pos_type: 0
    pos1: 0.0
    pos2: 0.0 
    pos3: 0.0 
    pos4: 0.0 
    pos5: 0.0 
    pos6: 0.0 
    pos7: 0.0 
    pos8: 0.0 
    pos9: 0.0 
    posture1: 1
    posture2: 1
    posture3: -1
    posture4: 0
PR12:
    id: 12
    is_valid: false
    name: default
    comment: default
    group_id: -1
    pos_type: 0
    pos1: 0.0
    pos2: 0.0 
    pos3: 0.0 
    pos4: 0.0 
    pos5: 0.0 
    pos6: 0.0 
    pos7: 0.0 
    pos8: 0.0 
    pos9: 0.0 
    posture1: 1
    posture2: 1
    posture3: -1
    posture4: 0
PR13:
    id: 13
    is_valid: false
    name: default
    comment: default
    group_id: -1
    pos_type: 0
    pos1: 0.0
    pos2: 0.0 
    pos3: 0.0 
    pos4: 0.0 
    pos5: 0.0 
    pos6: 0.0 
    pos7: 0.0 
    pos8: 0.0 
    pos9: 0.0 
    posture1: 1
    posture2: 1
    posture3: -1
    posture4: 0
PR14:
    id: 14
    is_valid: false
    name: default
    comment: default
    group_id: -1
    pos_type: 0
    pos1: 0.0
    pos2: 0.0 
    pos3: 0.0 
    pos4: 0.0 
    pos5: 0.0 
    pos6: 0.0 
    pos7: 0.0 
    pos8: 0.0 
    pos9: 0.0 
    posture1: 1
    posture2: 1
    posture3: -1
    posture4: 0
PR15:
    id: 15
    is_valid: false
    name: default
    comment: default
    group_id: -1
    pos_type: 0
    pos1: 0.0
    pos2: 0.0 
    pos3: 0.0 
    pos4: 0.0 
    pos5: 0.0 
    pos6: 0.0 
    pos7: 0.0 
    pos8: 0.0 
    pos9: 0.0 
    posture1: 1
    posture2: 1
    posture3: -1
    posture4: 0
PR16:
    id: 16
    is_valid: false
    name: default
    comment: default
    group_id: -1
    pos_type: 0
    pos1: 0.0
    pos2: 0.0 
    pos3: 0.0 
    pos4: 0.0 
    pos5: 0.0 
    pos6: 0.0 
    pos7: 0.0 
    pos8: 0.0 
    pos9: 0.0 
    posture1: 1
    posture2: 1
    posture3: -1
    posture4: 0
PR17:
    id: 17
    is_valid: false
    name: default
    comment: default
    group_id: -1
    pos_type: 0
    pos1: 0.0
    pos2: 0.0 
    pos3: 0.0 
    pos4: 0.0 
    pos5: 0.0 
    pos6: 0.0 
    pos7: 0.0 
    pos8: 0.0 
    pos9: 0.0 
    posture1: 1
    posture2: 1
    posture3: -1
    posture4: 0
PR18:
    id: 18
    is_valid: false
    name: default
    comment: default
    group_id: -1
    pos_type: 0
    pos1: 0.0
    pos2: 0.0 
    pos3: 0.0 
    pos4: 0.0 
    pos5: 0.0 
    pos6: 0.0 
    pos7: 0.0 
    pos8: 0.0 
    pos9: 0.0 
    posture1: 1
    posture2: 1
    posture3: -1
    posture4: 0
PR19:
    id: 19
    is_valid: false
    name: default
    comment: default
    group_id: -1
    pos_type: 0
    pos1: 0.0
    pos2: 0.0 
    pos3: 0.0 
    pos4: 0.0 
    pos5: 0.0 
    pos6: 0.0 
    pos7: 0.0 
    pos8: 0.0 
    pos9: 0.0 
    posture1: 1
    posture2: 1
    posture3: -1
    posture4: 0
PR20:
    id: 20
    is_valid: false
    name: default
    comment: default
    group_id: -1
    pos_type: 0
    pos1: 0.0
    pos2: 0.0 
    pos3: 0.0 
    pos4: 0.0 
    pos5: 0.0 
    pos6: 0.0 
    pos7: 0.0 
    pos8: 0.0 
    pos9: 0.0 
    posture1: 1
    posture2: 1
    posture3: -1
    posture4: 0
PR21:
    id: 21
    is_valid: false
    name: default
    comment: default
    group_id: -1
    pos_type: 0
    pos1: 0.0
    pos2: 0.0 
    pos3: 0.0 
    pos4: 0.0 
    pos5: 0.0 
    pos6: 0.0 
    pos7: 0.0 
    pos8: 0.0 
    pos9: 0.0 
    posture1: 1
    posture2: 1
    posture3: -1
    posture4: 0
PR22:
    id: 22
    is_valid: false
    name: default
    comment: default
    group_id: -1
    pos_type: 0
    pos1: 0.0
    pos2: 0.0 
    pos3: 0.0 
    pos4: 0.0 
    pos5: 0.0 
    pos6: 0.0 
    pos7: 0.0 
    pos8: 0.0 
    pos9: 0.0 
    posture1: 1
    posture2: 1
    posture3: -1
    posture4: 0
PR23:
    id: 23
    is_valid: false
    name: default
    comment: default
    group_id: -1
    pos_type: 0
    pos1: 0.0
    pos2: 0.0 
    pos3: 0.0 
    pos4: 0.0 
    pos5: 0.0 
    pos6: 0.0 
    pos7: 0.0 
    pos8: 0.0 
    pos9: 0.0 
    posture1: 1
    posture2: 1
    posture3: -1
    posture4: 0
PR24:
    id: 24
    is_valid: false
    name: default
    comment: default
    group_id: -1
    pos_type: 0
    pos1: 0.0
    pos2: 0.0 
    pos3: 0.0 
    pos4: 0.0 
    pos5: 0.0 
    pos6: 0.0 
    pos7: 0.0 
    pos8: 0.0 
    pos9: 0.0 
    posture1: 1
    posture2: 1
    posture3: -1
    posture4: 0
PR25:
    id: 25
    is_valid: false
    name: default
    comment: default
    group_id: -1
    pos_type: 0
    pos1: 0.0
    pos2: 0.0 
    pos3: 0.0 
    pos4: 0.0 
    pos5: 0.0 
    pos6: 0.0 
    pos7: 0.0 
    pos8: 0.0 
    pos9: 0.0 
    posture1: 1
    posture2: 1
    posture3: -1
    posture4: 0
PR26:
    id: 26
    is_valid: false
    name: default
    comment: default
    group_id: -1
    pos_type: 0
    pos1: 0.0
    pos2: 0.0 
    pos3: 0.0 
    pos4: 0.0 
    pos5: 0.0 
    pos6: 0.0 
    pos7: 0.0 
    pos8: 0.0 
    pos9: 0.0 
    posture1: 1
    posture2: 1
    posture3: -1
    posture4: 0
PR27:
    id: 27
    is_valid: false
    name: default
    comment: default
    group_id: -1
    pos_type: 0
    pos1: 0.0
    pos2: 0.0 
    pos3: 0.0 
    pos4: 0.0 
    pos5: 0.0 
    pos6: 0.0 
    pos7: 0.0 
    pos8: 0.0 
    pos9: 0.0 
    posture1: 1
    posture2: 1
    posture3: -1
    posture4: 0
PR28:
    id: 28
    is_valid: false
    name: default
    comment: default
    group_id: -1
    pos_type: 0
    pos1: 0.0
    pos2: 0.0 
    pos3: 0.0 
    pos4: 0.0 
    pos5: 0.0 
    pos6: 0.0 
    pos7: 0.0 
    pos8: 0.0 
    pos9: 0.0 
    posture1: 1
    posture2: 1
    posture3: -1
    posture4: 0
PR29:
    id: 29
    is_valid: false
    name: default
    comment: default
    group_id: -1
    pos_type: 0
    pos1: 0.0
    pos2: 0.0 
    pos3: 0.0 
    pos4: 0.0 
    pos5: 0.0 
    pos6: 0.0 
    pos7: 0.0 
    pos8: 0.0 
    pos9: 0.0 
    posture1: 1
    posture2: 1
    posture3: -1
    posture4: 0
PR30:
    id: 30
    is_valid: false
    name: default
    comment: default
    group_id: -1
    pos_type: 0
    pos1: 0.0
    pos2: 0.0 
    pos3: 0.0 
    pos4: 0.0 
    pos5: 0.0 
    pos6: 0.0 
    pos7: 0.0 
    pos8: 0.0 
    pos9: 0.0 
    posture1: 1
    posture2: 1
    posture3: -1
    posture4: 0
#END
