PR1:
    id: 1
    is_valid: false
    name: default
    comment: default
    group_id: -1
    pos_type: 0
    pos1: 0.0
    pos2: 0.0 
    pos3: 0.0 
    pos4: 0.0 
    pos5: 0.0 
    pos6: 0.0 
    pos7: 0.0 
    pos8: 0.0 
    pos9: 0.0 
    posture1: false
    posture2: false
    posture3: false
    posture4: false
PR2:
    id: 2
    is_valid: false
    name: default
    comment: default
    group_id: -1
    pos_type: 0
    pos1: 0.0
    pos2: 0.0 
    pos3: 0.0 
    pos4: 0.0 
    pos5: 0.0 
    pos6: 0.0 
    pos7: 0.0 
    pos8: 0.0 
    pos9: 0.0 
    posture1: false
    posture2: false
    posture3: false
    posture4: false
PR3:
    id: 3
    is_valid: false
    name: default
    comment: default
    group_id: -1
    pos_type: 0
    pos1: 0.0
    pos2: 0.0 
    pos3: 0.0 
    pos4: 0.0 
    pos5: 0.0 
    pos6: 0.0 
    pos7: 0.0 
    pos8: 0.0 
    pos9: 0.0 
    posture1: false
    posture2: false
    posture3: false
    posture4: false
PR4:
    id: 4
    is_valid: false
    name: default
    comment: default
    group_id: -1
    pos_type: 0
    pos1: 0.0
    pos2: 0.0 
    pos3: 0.0 
    pos4: 0.0 
    pos5: 0.0 
    pos6: 0.0 
    pos7: 0.0 
    pos8: 0.0 
    pos9: 0.0 
    posture1: false
    posture2: false
    posture3: false
    posture4: false
PR5:
    id: 5
    is_valid: false
    name: default
    comment: default
    group_id: -1
    pos_type: 0
    pos1: 0.0
    pos2: 0.0 
    pos3: 0.0 
    pos4: 0.0 
    pos5: 0.0 
    pos6: 0.0 
    pos7: 0.0 
    pos8: 0.0 
    pos9: 0.0 
    posture1: false
    posture2: false
    posture3: false
    posture4: false
PR6:
    id: 6
    is_valid: false
    name: default
    comment: default
    group_id: -1
    pos_type: 0
    pos1: 0.0
    pos2: 0.0 
    pos3: 0.0 
    pos4: 0.0 
    pos5: 0.0 
    pos6: 0.0 
    pos7: 0.0 
    pos8: 0.0 
    pos9: 0.0 
    posture1: false
    posture2: false
    posture3: false
    posture4: false
PR7:
    id: 7
    is_valid: false
    name: default
    comment: default
    group_id: -1
    pos_type: 0
    pos1: 0.0
    pos2: 0.0 
    pos3: 0.0 
    pos4: 0.0 
    pos5: 0.0 
    pos6: 0.0 
    pos7: 0.0 
    pos8: 0.0 
    pos9: 0.0 
    posture1: false
    posture2: false
    posture3: false
    posture4: false
PR8:
    id: 8
    is_valid: false
    name: default
    comment: default
    group_id: -1
    pos_type: 0
    pos1: 0.0
    pos2: 0.0 
    pos3: 0.0 
    pos4: 0.0 
    pos5: 0.0 
    pos6: 0.0 
    pos7: 0.0 
    pos8: 0.0 
    pos9: 0.0 
    posture1: false
    posture2: false
    posture3: false
    posture4: false
PR9:
    id: 9
    is_valid: false
    name: default
    comment: default
    group_id: -1
    pos_type: 0
    pos1: 0.0
    pos2: 0.0 
    pos3: 0.0 
    pos4: 0.0 
    pos5: 0.0 
    pos6: 0.0 
    pos7: 0.0 
    pos8: 0.0 
    pos9: 0.0 
    posture1: false
    posture2: false
    posture3: false
    posture4: false
PR10:
    id: 10
    is_valid: false
    name: default
    comment: default
    group_id: -1
    pos_type: 0
    pos1: 0.0
    pos2: 0.0 
    pos3: 0.0 
    pos4: 0.0 
    pos5: 0.0 
    pos6: 0.0 
    pos7: 0.0 
    pos8: 0.0 
    pos9: 0.0 
    posture1: false
    posture2: false
    posture3: false
    posture4: false
#END
