R1:
    id: 1
    is_valid: false
    name: default
    comment: default
    value: 0.0
R2:
    id: 2
    is_valid: false
    name: default
    comment: default
    value: 0.0
R3:
    id: 3
    is_valid: false
    name: default
    comment: default
    value: 0.0
R4:
    id: 4
    is_valid: false
    name: default
    comment: default
    value: 0.0
R5:
    id: 5
    is_valid: false
    name: default
    comment: default
    value: 0.0
R6:
    id: 6
    is_valid: false
    name: default
    comment: default
    value: 0.0
R7:
    id: 7
    is_valid: false
    name: default
    comment: default
    value: 0.0
R8:
    id: 8
    is_valid: false
    name: default
    comment: default
    value: 0.0
R9:
    id: 9
    is_valid: false
    name: default
    comment: default
    value: 0.0
R10:
    id: 10
    is_valid: false
    name: default
    comment: default
    value: 0.0
R11:
    id: 11
    is_valid: false
    name: default
    comment: default
    value: 0.0
R12:
    id: 12
    is_valid: false
    name: default
    comment: default
    value: 0.0
R13:
    id: 13
    is_valid: false
    name: default
    comment: default
    value: 0.0
R14:
    id: 14
    is_valid: false
    name: default
    comment: default
    value: 0.0
R15:
    id: 15
    is_valid: false
    name: default
    comment: default
    value: 0.0
R16:
    id: 16
    is_valid: false
    name: default
    comment: default
    value: 0.0
R17:
    id: 17
    is_valid: false
    name: default
    comment: default
    value: 0.0
R18:
    id: 18
    is_valid: false
    name: default
    comment: default
    value: 0.0
R19:
    id: 19
    is_valid: false
    name: default
    comment: default
    value: 0.0
R20:
    id: 20
    is_valid: false
    name: default
    comment: default
    value: 0.0
R21:
    id: 21
    is_valid: false
    name: default
    comment: default
    value: 0.0
R22:
    id: 22
    is_valid: false
    name: default
    comment: default
    value: 0.0
R23:
    id: 23
    is_valid: false
    name: default
    comment: default
    value: 0.0
R24:
    id: 24
    is_valid: false
    name: default
    comment: default
    value: 0.0
R25:
    id: 25
    is_valid: false
    name: default
    comment: default
    value: 0.0
R26:
    id: 26
    is_valid: false
    name: default
    comment: default
    value: 0.0
R27:
    id: 27
    is_valid: false
    name: default
    comment: default
    value: 0.0
R28:
    id: 28
    is_valid: false
    name: default
    comment: default
    value: 0.0
R29:
    id: 29
    is_valid: false
    name: default
    comment: default
    value: 0.0
R30:
    id: 30
    is_valid: false
    name: default
    comment: default
    value: 0.0
#END
