log_level: 1
reg_info_dir: share/runtime/robot/reg/ 
pr_reg_file_name: pr_reg.yaml
hr_reg_file_name: hr_reg.yaml
mr_reg_file_name: mr_reg.yaml
sr_reg_file_name: sr_reg.yaml
r_reg_file_name: r_reg.yaml
pr_reg_number: 100
hr_reg_number: 10
mr_reg_number: 100
sr_reg_number: 100
r_reg_number: 100
pr_value_limit: 99999999.999
hr_value_limit: 99999999.999
mr_value_limit: 99999999 
sr_value_limit: 255
r_value_limit: 99999999.999 
name_length_limit: 32
comment_length_limit: 128
sr_value_length_limit: 254
#END
