/* Automatically generated nanopb header */
/* Generated by nanopb-0.3.7-dev at Wed Sep 12 13:42:17 2018. */

#ifndef PB_REQUESTMESSAGETYPE_REQUEST_FILE_PB_H_INCLUDED
#define PB_REQUESTMESSAGETYPE_REQUEST_FILE_PB_H_INCLUDED
#include <pb.h>

#include "protocal/request_header.pb.h"

#include "protocal/comm.pb.h"

#include "message_type/file.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Struct definitions */
typedef struct _RequestMessageType_File {
    Request_Header header;
    Comm_Property property;
    MessageType_File data;
/* @@protoc_insertion_point(struct:RequestMessageType_File) */
} RequestMessageType_File;

/* Default values for struct fields */

/* Initializer values for message structs */
#define RequestMessageType_File_init_default     {Request_Header_init_default, Comm_Property_init_default, MessageType_File_init_default}
#define RequestMessageType_File_init_zero        {Request_Header_init_zero, Comm_Property_init_zero, MessageType_File_init_zero}

/* Field tags (for use in manual encoding/decoding) */
#define RequestMessageType_File_header_tag       1
#define RequestMessageType_File_property_tag     2
#define RequestMessageType_File_data_tag         3

/* Struct field encoding specification for nanopb */
extern const pb_field_t RequestMessageType_File_fields[4];

/* Maximum encoded size of messages (where known) */
#define RequestMessageType_File_size             51052

/* Message IDs (where set with "msgid" option) */
#ifdef PB_MSGID

#define REQUEST_FILE_MESSAGES \


#endif

#ifdef __cplusplus
} /* extern "C" */
#endif
/* @@protoc_insertion_point(eof) */

#endif
