/* Automatically generated nanopb header */
/* Generated by nanopb-0.3.7 at Thu Sep 19 11:38:03 2019. */

#ifndef PB_REQUESTMESSAGETYPE_REQUEST_BASE_PB_H_INCLUDED
#define PB_REQUESTMESSAGETYPE_REQUEST_BASE_PB_H_INCLUDED
#include <pb.h>

#include "protocol/request_header.pb.h"

#include "protocol/comm.pb.h"

#include "message_type/base.pb.h"
#include "message_type/trans_matrix_list.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Struct definitions */
typedef struct _RequestMessageType_Bool {
    Request_Header header;
    Comm_Property property;
    MessageType_Bool data;
/* @@protoc_insertion_point(struct:RequestMessageType_Bool) */
} RequestMessageType_Bool;

typedef struct _RequestMessageType_BoolList {
    Request_Header header;
    Comm_Property property;
    MessageType_BoolList data;
/* @@protoc_insertion_point(struct:RequestMessageType_BoolList) */
} RequestMessageType_BoolList;

typedef struct _RequestMessageType_Bytes {
    Request_Header header;
    Comm_Property property;
    MessageType_Bytes data;
/* @@protoc_insertion_point(struct:RequestMessageType_Bytes) */
} RequestMessageType_Bytes;

typedef struct _RequestMessageType_Double {
    Request_Header header;
    Comm_Property property;
    MessageType_Double data;
/* @@protoc_insertion_point(struct:RequestMessageType_Double) */
} RequestMessageType_Double;

typedef struct _RequestMessageType_DoubleList {
    Request_Header header;
    Comm_Property property;
    MessageType_DoubleList data;
/* @@protoc_insertion_point(struct:RequestMessageType_DoubleList) */
} RequestMessageType_DoubleList;

typedef struct _RequestMessageType_Float {
    Request_Header header;
    Comm_Property property;
    MessageType_Float data;
/* @@protoc_insertion_point(struct:RequestMessageType_Float) */
} RequestMessageType_Float;

typedef struct _RequestMessageType_FloatList {
    Request_Header header;
    Comm_Property property;
    MessageType_FloatList data;
/* @@protoc_insertion_point(struct:RequestMessageType_FloatList) */
} RequestMessageType_FloatList;

typedef struct _RequestMessageType_Int32 {
    Request_Header header;
    Comm_Property property;
    MessageType_Int32 data;
/* @@protoc_insertion_point(struct:RequestMessageType_Int32) */
} RequestMessageType_Int32;

typedef struct _RequestMessageType_Int32List {
    Request_Header header;
    Comm_Property property;
    MessageType_Int32List data;
/* @@protoc_insertion_point(struct:RequestMessageType_Int32List) */
} RequestMessageType_Int32List;

typedef struct _RequestMessageType_Int64 {
    Request_Header header;
    Comm_Property property;
    MessageType_Int64 data;
/* @@protoc_insertion_point(struct:RequestMessageType_Int64) */
} RequestMessageType_Int64;

typedef struct _RequestMessageType_Int64List {
    Request_Header header;
    Comm_Property property;
    MessageType_Int64List data;
/* @@protoc_insertion_point(struct:RequestMessageType_Int64List) */
} RequestMessageType_Int64List;

typedef struct _RequestMessageType_String {
    Request_Header header;
    Comm_Property property;
    MessageType_String data;
/* @@protoc_insertion_point(struct:RequestMessageType_String) */
} RequestMessageType_String;

typedef struct _RequestMessageType_Uint32 {
    Request_Header header;
    Comm_Property property;
    MessageType_Uint32 data;
/* @@protoc_insertion_point(struct:RequestMessageType_Uint32) */
} RequestMessageType_Uint32;

typedef struct _RequestMessageType_Uint32List {
    Request_Header header;
    Comm_Property property;
    MessageType_Uint32List data;
/* @@protoc_insertion_point(struct:RequestMessageType_Uint32List) */
} RequestMessageType_Uint32List;

typedef struct _RequestMessageType_Uint64 {
    Request_Header header;
    Comm_Property property;
    MessageType_Uint64 data;
/* @@protoc_insertion_point(struct:RequestMessageType_Uint64) */
} RequestMessageType_Uint64;

typedef struct _RequestMessageType_Uint64List {
    Request_Header header;
    Comm_Property property;
    MessageType_Uint64List data;
/* @@protoc_insertion_point(struct:RequestMessageType_Uint64List) */
} RequestMessageType_Uint64List;

typedef struct _RequestMessageType_Void {
    Request_Header header;
    Comm_Property property;
/* @@protoc_insertion_point(struct:RequestMessageType_Void) */
} RequestMessageType_Void;

/* Default values for struct fields */

/* Initializer values for message structs */
#define RequestMessageType_Bool_init_default     {Request_Header_init_default, Comm_Property_init_default, MessageType_Bool_init_default}
#define RequestMessageType_Int32_init_default    {Request_Header_init_default, Comm_Property_init_default, MessageType_Int32_init_default}
#define RequestMessageType_Uint32_init_default   {Request_Header_init_default, Comm_Property_init_default, MessageType_Uint32_init_default}
#define RequestMessageType_Int64_init_default    {Request_Header_init_default, Comm_Property_init_default, MessageType_Int64_init_default}
#define RequestMessageType_Uint64_init_default   {Request_Header_init_default, Comm_Property_init_default, MessageType_Uint64_init_default}
#define RequestMessageType_Double_init_default   {Request_Header_init_default, Comm_Property_init_default, MessageType_Double_init_default}
#define RequestMessageType_Float_init_default    {Request_Header_init_default, Comm_Property_init_default, MessageType_Float_init_default}
#define RequestMessageType_Bytes_init_default    {Request_Header_init_default, Comm_Property_init_default, MessageType_Bytes_init_default}
#define RequestMessageType_String_init_default   {Request_Header_init_default, Comm_Property_init_default, MessageType_String_init_default}
#define RequestMessageType_Void_init_default     {Request_Header_init_default, Comm_Property_init_default}
#define RequestMessageType_BoolList_init_default {Request_Header_init_default, Comm_Property_init_default, MessageType_BoolList_init_default}
#define RequestMessageType_Int32List_init_default {Request_Header_init_default, Comm_Property_init_default, MessageType_Int32List_init_default}
#define RequestMessageType_Uint32List_init_default {Request_Header_init_default, Comm_Property_init_default, MessageType_Uint32List_init_default}
#define RequestMessageType_Int64List_init_default {Request_Header_init_default, Comm_Property_init_default, MessageType_Int64List_init_default}
#define RequestMessageType_Uint64List_init_default {Request_Header_init_default, Comm_Property_init_default, MessageType_Uint64List_init_default}
#define RequestMessageType_DoubleList_init_default {Request_Header_init_default, Comm_Property_init_default, MessageType_DoubleList_init_default}
#define RequestMessageType_FloatList_init_default {Request_Header_init_default, Comm_Property_init_default, MessageType_FloatList_init_default}
#define RequestMessageType_Bool_init_zero        {Request_Header_init_zero, Comm_Property_init_zero, MessageType_Bool_init_zero}
#define RequestMessageType_Int32_init_zero       {Request_Header_init_zero, Comm_Property_init_zero, MessageType_Int32_init_zero}
#define RequestMessageType_Uint32_init_zero      {Request_Header_init_zero, Comm_Property_init_zero, MessageType_Uint32_init_zero}
#define RequestMessageType_Int64_init_zero       {Request_Header_init_zero, Comm_Property_init_zero, MessageType_Int64_init_zero}
#define RequestMessageType_Uint64_init_zero      {Request_Header_init_zero, Comm_Property_init_zero, MessageType_Uint64_init_zero}
#define RequestMessageType_Double_init_zero      {Request_Header_init_zero, Comm_Property_init_zero, MessageType_Double_init_zero}
#define RequestMessageType_Float_init_zero       {Request_Header_init_zero, Comm_Property_init_zero, MessageType_Float_init_zero}
#define RequestMessageType_Bytes_init_zero       {Request_Header_init_zero, Comm_Property_init_zero, MessageType_Bytes_init_zero}
#define RequestMessageType_String_init_zero      {Request_Header_init_zero, Comm_Property_init_zero, MessageType_String_init_zero}
#define RequestMessageType_Void_init_zero        {Request_Header_init_zero, Comm_Property_init_zero}
#define RequestMessageType_BoolList_init_zero    {Request_Header_init_zero, Comm_Property_init_zero, MessageType_BoolList_init_zero}
#define RequestMessageType_Int32List_init_zero   {Request_Header_init_zero, Comm_Property_init_zero, MessageType_Int32List_init_zero}
#define RequestMessageType_Uint32List_init_zero  {Request_Header_init_zero, Comm_Property_init_zero, MessageType_Uint32List_init_zero}
#define RequestMessageType_Int64List_init_zero   {Request_Header_init_zero, Comm_Property_init_zero, MessageType_Int64List_init_zero}
#define RequestMessageType_Uint64List_init_zero  {Request_Header_init_zero, Comm_Property_init_zero, MessageType_Uint64List_init_zero}
#define RequestMessageType_DoubleList_init_zero  {Request_Header_init_zero, Comm_Property_init_zero, MessageType_DoubleList_init_zero}
#define RequestMessageType_FloatList_init_zero   {Request_Header_init_zero, Comm_Property_init_zero, MessageType_FloatList_init_zero}


/* Field tags (for use in manual encoding/decoding) */
#define RequestMessageType_Bool_header_tag       1
#define RequestMessageType_Bool_property_tag     2
#define RequestMessageType_Bool_data_tag         3
#define RequestMessageType_BoolList_header_tag   1
#define RequestMessageType_BoolList_property_tag 2
#define RequestMessageType_BoolList_data_tag     3
#define RequestMessageType_Bytes_header_tag      1
#define RequestMessageType_Bytes_property_tag    2
#define RequestMessageType_Bytes_data_tag        3
#define RequestMessageType_Double_header_tag     1
#define RequestMessageType_Double_property_tag   2
#define RequestMessageType_Double_data_tag       3
#define RequestMessageType_DoubleList_header_tag 1
#define RequestMessageType_DoubleList_property_tag 2
#define RequestMessageType_DoubleList_data_tag   3
#define RequestMessageType_Float_header_tag      1
#define RequestMessageType_Float_property_tag    2
#define RequestMessageType_Float_data_tag        3
#define RequestMessageType_FloatList_header_tag  1
#define RequestMessageType_FloatList_property_tag 2
#define RequestMessageType_FloatList_data_tag    3
#define RequestMessageType_Int32_header_tag      1
#define RequestMessageType_Int32_property_tag    2
#define RequestMessageType_Int32_data_tag        3
#define RequestMessageType_Int32List_header_tag  1
#define RequestMessageType_Int32List_property_tag 2
#define RequestMessageType_Int32List_data_tag    3
#define RequestMessageType_Int64_header_tag      1
#define RequestMessageType_Int64_property_tag    2
#define RequestMessageType_Int64_data_tag        3
#define RequestMessageType_Int64List_header_tag  1
#define RequestMessageType_Int64List_property_tag 2
#define RequestMessageType_Int64List_data_tag    3
#define RequestMessageType_String_header_tag     1
#define RequestMessageType_String_property_tag   2
#define RequestMessageType_String_data_tag       3
#define RequestMessageType_Uint32_header_tag     1
#define RequestMessageType_Uint32_property_tag   2
#define RequestMessageType_Uint32_data_tag       3
#define RequestMessageType_Uint32List_header_tag 1
#define RequestMessageType_Uint32List_property_tag 2
#define RequestMessageType_Uint32List_data_tag   3
#define RequestMessageType_Uint64_header_tag     1
#define RequestMessageType_Uint64_property_tag   2
#define RequestMessageType_Uint64_data_tag       3
#define RequestMessageType_Uint64List_header_tag 1
#define RequestMessageType_Uint64List_property_tag 2
#define RequestMessageType_Uint64List_data_tag   3
#define RequestMessageType_Void_header_tag       1
#define RequestMessageType_Void_property_tag     2

/* Struct field encoding specification for nanopb */
extern const pb_field_t RequestMessageType_Bool_fields[4];
extern const pb_field_t RequestMessageType_Int32_fields[4];
extern const pb_field_t RequestMessageType_Uint32_fields[4];
extern const pb_field_t RequestMessageType_Int64_fields[4];
extern const pb_field_t RequestMessageType_Uint64_fields[4];
extern const pb_field_t RequestMessageType_Double_fields[4];
extern const pb_field_t RequestMessageType_Float_fields[4];
extern const pb_field_t RequestMessageType_Bytes_fields[4];
extern const pb_field_t RequestMessageType_String_fields[4];
extern const pb_field_t RequestMessageType_Void_fields[3];
extern const pb_field_t RequestMessageType_BoolList_fields[4];
extern const pb_field_t RequestMessageType_Int32List_fields[4];
extern const pb_field_t RequestMessageType_Uint32List_fields[4];
extern const pb_field_t RequestMessageType_Int64List_fields[4];
extern const pb_field_t RequestMessageType_Uint64List_fields[4];
extern const pb_field_t RequestMessageType_DoubleList_fields[4];
extern const pb_field_t RequestMessageType_FloatList_fields[4];
/* Maximum encoded size of messages (where known) */
#define RequestMessageType_Bool_size             21
#define RequestMessageType_Int32_size            30
#define RequestMessageType_Uint32_size           25
#define RequestMessageType_Int64_size            30
#define RequestMessageType_Uint64_size           30
#define RequestMessageType_Double_size           28
#define RequestMessageType_Float_size            24
#define RequestMessageType_Bytes_size            65561
#define RequestMessageType_String_size           535
#define RequestMessageType_Void_size             17
#define RequestMessageType_BoolList_size         276
#define RequestMessageType_Int32List_size        1428
#define RequestMessageType_Uint32List_size       788
#define RequestMessageType_Int64List_size        1428
#define RequestMessageType_Uint64List_size       1428
#define RequestMessageType_DoubleList_size       1172
#define RequestMessageType_FloatList_size        660
/* Message IDs (where set with "msgid" option) */
#ifdef PB_MSGID

#define REQUEST_BASE_MESSAGES \


#endif

#ifdef __cplusplus
} /* extern "C" */
#endif
/* @@protoc_insertion_point(eof) */

#endif
