/* Automatically generated nanopb header */
/* Generated by nanopb-0.3.7-dev at Thu Dec 27 18:11:17 2018. */

#ifndef PB_REQUESTMESSAGETYPE_REQUEST_MODBUS_SERVER_START_INFO_PB_H_INCLUDED
#define PB_REQUESTMESSAGETYPE_REQUEST_MODBUS_SERVER_START_INFO_PB_H_INCLUDED
#include <pb.h>

#include "protocal/request_header.pb.h"

#include "protocal/comm.pb.h"

#include "message_type/base.pb.h"

#include "message_type/modbus_server_start_info.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Struct definitions */
typedef struct _RequestMessageType_ModbusServerStartInfo {
    Request_Header header;
    Comm_Property property;
    MessageType_ModbusServerStartInfo data;
/* @@protoc_insertion_point(struct:RequestMessageType_ModbusServerStartInfo) */
} RequestMessageType_ModbusServerStartInfo;

/* Default values for struct fields */

/* Initializer values for message structs */
#define RequestMessageType_ModbusServerStartInfo_init_default {Request_Header_init_default, Comm_Property_init_default, MessageType_ModbusServerStartInfo_init_default}
#define RequestMessageType_ModbusServerStartInfo_init_zero {Request_Header_init_zero, Comm_Property_init_zero, MessageType_ModbusServerStartInfo_init_zero}

/* Field tags (for use in manual encoding/decoding) */
#define RequestMessageType_ModbusServerStartInfo_header_tag 1
#define RequestMessageType_ModbusServerStartInfo_property_tag 2
#define RequestMessageType_ModbusServerStartInfo_data_tag 3

/* Struct field encoding specification for nanopb */
extern const pb_field_t RequestMessageType_ModbusServerStartInfo_fields[4];

/* Maximum encoded size of messages (where known) */
#define RequestMessageType_ModbusServerStartInfo_size 293

/* Message IDs (where set with "msgid" option) */
#ifdef PB_MSGID

#define REQUEST_MODBUS_SERVER_START_INFO_MESSAGES \


#endif

#ifdef __cplusplus
} /* extern "C" */
#endif
/* @@protoc_insertion_point(eof) */

#endif
