/* Automatically generated nanopb header */
/* Generated by nanopb-0.3.7 at Mon Jul 19 13:49:17 2021. */

#ifndef PB_REQUESTMESSAGETYPE_REQUEST_REG_MR_PB_H_INCLUDED
#define PB_REQUESTMESSAGETYPE_REQUEST_REG_MR_PB_H_INCLUDED
#include <pb.h>

#include "protocol/request_header.pb.h"

#include "protocol/comm.pb.h"

#include "message_type/reg_mr.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Struct definitions */
typedef struct _RequestMessageType_MrRegData {
    Request_Header header;
    Comm_Property property;
    MessageType_MrRegData data;
/* @@protoc_insertion_point(struct:RequestMessageType_MrRegData) */
} RequestMessageType_MrRegData;

/* Default values for struct fields */

/* Initializer values for message structs */
#define RequestMessageType_MrRegData_init_default {Request_Header_init_default, Comm_Property_init_default, MessageType_MrRegData_init_default}
#define RequestMessageType_MrRegData_init_zero   {Request_Header_init_zero, Comm_Property_init_zero, MessageType_MrRegData_init_zero}

/* Field tags (for use in manual encoding/decoding) */
#define RequestMessageType_MrRegData_header_tag  1
#define RequestMessageType_MrRegData_property_tag 2
#define RequestMessageType_MrRegData_data_tag    3

/* Struct field encoding specification for nanopb */
extern const pb_field_t RequestMessageType_MrRegData_fields[4];

/* Maximum encoded size of messages (where known) */
#define RequestMessageType_MrRegData_size        367

/* Message IDs (where set with "msgid" option) */
#ifdef PB_MSGID

#define REQUEST_REG_MR_MESSAGES \


#endif

#ifdef __cplusplus
} /* extern "C" */
#endif
/* @@protoc_insertion_point(eof) */

#endif
