/* Automatically generated nanopb header */
/* Generated by nanopb-0.3.7-dev at Tue Aug 14 16:43:12 2018. */

#ifndef PB_RESPONSEMESSAGETYPE_RESPONSE_DEVICE_INFO_PB_H_INCLUDED
#define PB_RESPONSEMESSAGETYPE_RESPONSE_DEVICE_INFO_PB_H_INCLUDED
#include <pb.h>

#include "protocal/response_header.pb.h"

#include "protocal/comm.pb.h"

#include "message_type/device_info.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Struct definitions */
typedef struct _ResponseMessageType_DeviceInfoList {
    Response_Header header;
    Comm_Property property;
    MessageType_DeviceInfoList data;
/* @@protoc_insertion_point(struct:ResponseMessageType_DeviceInfoList) */
} ResponseMessageType_DeviceInfoList;

/* Default values for struct fields */

/* Initializer values for message structs */
#define ResponseMessageType_DeviceInfoList_init_default {Response_Header_init_default, Comm_Property_init_default, MessageType_DeviceInfoList_init_default}
#define ResponseMessageType_DeviceInfoList_init_zero {Response_Header_init_zero, Comm_Property_init_zero, MessageType_DeviceInfoList_init_zero}

/* Field tags (for use in manual encoding/decoding) */
#define ResponseMessageType_DeviceInfoList_header_tag 1
#define ResponseMessageType_DeviceInfoList_property_tag 2
#define ResponseMessageType_DeviceInfoList_data_tag 3

/* Struct field encoding specification for nanopb */
extern const pb_field_t ResponseMessageType_DeviceInfoList_fields[4];

/* Maximum encoded size of messages (where known) */
#define ResponseMessageType_DeviceInfoList_size  9514

/* Message IDs (where set with "msgid" option) */
#ifdef PB_MSGID

#define RESPONSE_DEVICE_INFO_MESSAGES \


#endif

#ifdef __cplusplus
} /* extern "C" */
#endif
/* @@protoc_insertion_point(eof) */

#endif
