/* Automatically generated nanopb header */
/* Generated by nanopb-0.3.7-dev at Fri Aug 10 13:55:08 2018. */

#ifndef PB_RESPONSEMESSAGETYPE_RESPONSE_REG_BASE_SUMMARY_PB_H_INCLUDED
#define PB_RESPONSEMESSAGETYPE_RESPONSE_REG_BASE_SUMMARY_PB_H_INCLUDED
#include <pb.h>

#include "protocal/request_header.pb.h"

#include "protocal/comm.pb.h"

#include "message_type/reg_base_summary.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Struct definitions */
typedef struct _ResponseMessageType_BaseRegSummaryList {
    Request_Header header;
    Comm_Property property;
    MessageType_BaseRegSummaryList data;
/* @@protoc_insertion_point(struct:ResponseMessageType_BaseRegSummaryList) */
} ResponseMessageType_BaseRegSummaryList;

/* Default values for struct fields */

/* Initializer values for message structs */
#define ResponseMessageType_BaseRegSummaryList_init_default {Request_Header_init_default, Comm_Property_init_default, MessageType_BaseRegSummaryList_init_default}
#define ResponseMessageType_BaseRegSummaryList_init_zero {Request_Header_init_zero, Comm_Property_init_zero, MessageType_BaseRegSummaryList_init_zero}

/* Field tags (for use in manual encoding/decoding) */
#define ResponseMessageType_BaseRegSummaryList_header_tag 1
#define ResponseMessageType_BaseRegSummaryList_property_tag 2
#define ResponseMessageType_BaseRegSummaryList_data_tag 3

/* Struct field encoding specification for nanopb */
extern const pb_field_t ResponseMessageType_BaseRegSummaryList_fields[4];

/* Maximum encoded size of messages (where known) */
#define ResponseMessageType_BaseRegSummaryList_size 314389

/* Message IDs (where set with "msgid" option) */
#ifdef PB_MSGID

#define RESPONSE_REG_BASE_SUMMARY_MESSAGES \


#endif

#ifdef __cplusplus
} /* extern "C" */
#endif
/* @@protoc_insertion_point(eof) */

#endif
