/* Automatically generated nanopb header */
/* Generated by nanopb-0.3.7-dev at Thu Jul 19 16:16:36 2018. */

#ifndef PB_RESPONSEMESSAGETYPE_RESPONSE_BASE_PB_H_INCLUDED
#define PB_RESPONSEMESSAGETYPE_RESPONSE_BASE_PB_H_INCLUDED
#include <pb.h>

#include "protocal/response_header.pb.h"

#include "protocal/comm.pb.h"

#include "message_type/base.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Struct definitions */
typedef struct _ResponseMessageType_Bool {
    Response_Header header;
    Comm_Property property;
    MessageType_Bool data;
/* @@protoc_insertion_point(struct:ResponseMessageType_Bool) */
} ResponseMessageType_Bool;

typedef struct _ResponseMessageType_BoolList {
    Response_Header header;
    Comm_Property property;
    MessageType_Bool data;
/* @@protoc_insertion_point(struct:ResponseMessageType_BoolList) */
} ResponseMessageType_BoolList;

typedef struct _ResponseMessageType_Bytes {
    Response_Header header;
    Comm_Property property;
    MessageType_Bytes data;
/* @@protoc_insertion_point(struct:ResponseMessageType_Bytes) */
} ResponseMessageType_Bytes;

typedef struct _ResponseMessageType_Double {
    Response_Header header;
    Comm_Property property;
    MessageType_Double data;
/* @@protoc_insertion_point(struct:ResponseMessageType_Double) */
} ResponseMessageType_Double;

typedef struct _ResponseMessageType_DoubleList {
    Response_Header header;
    Comm_Property property;
    MessageType_DoubleList data;
/* @@protoc_insertion_point(struct:ResponseMessageType_DoubleList) */
} ResponseMessageType_DoubleList;

typedef struct _ResponseMessageType_Float {
    Response_Header header;
    Comm_Property property;
    MessageType_Float data;
/* @@protoc_insertion_point(struct:ResponseMessageType_Float) */
} ResponseMessageType_Float;

typedef struct _ResponseMessageType_FloatList {
    Response_Header header;
    Comm_Property property;
    MessageType_FloatList data;
/* @@protoc_insertion_point(struct:ResponseMessageType_FloatList) */
} ResponseMessageType_FloatList;

typedef struct _ResponseMessageType_Int32 {
    Response_Header header;
    Comm_Property property;
    MessageType_Int32 data;
/* @@protoc_insertion_point(struct:ResponseMessageType_Int32) */
} ResponseMessageType_Int32;

typedef struct _ResponseMessageType_Int32List {
    Response_Header header;
    Comm_Property property;
    MessageType_Int32List data;
/* @@protoc_insertion_point(struct:ResponseMessageType_Int32List) */
} ResponseMessageType_Int32List;

typedef struct _ResponseMessageType_Int64 {
    Response_Header header;
    Comm_Property property;
    MessageType_Int64 data;
/* @@protoc_insertion_point(struct:ResponseMessageType_Int64) */
} ResponseMessageType_Int64;

typedef struct _ResponseMessageType_Int64List {
    Response_Header header;
    Comm_Property property;
    MessageType_Int64List data;
/* @@protoc_insertion_point(struct:ResponseMessageType_Int64List) */
} ResponseMessageType_Int64List;

typedef struct _ResponseMessageType_String {
    Response_Header header;
    Comm_Property property;
    MessageType_String data;
/* @@protoc_insertion_point(struct:ResponseMessageType_String) */
} ResponseMessageType_String;

typedef struct _ResponseMessageType_UnsignedInt32 {
    Response_Header header;
    Comm_Property property;
    MessageType_UnsignedInt32 data;
/* @@protoc_insertion_point(struct:ResponseMessageType_UnsignedInt32) */
} ResponseMessageType_UnsignedInt32;

typedef struct _ResponseMessageType_UnsignedInt32List {
    Response_Header header;
    Comm_Property property;
    MessageType_UnsignedInt32List data;
/* @@protoc_insertion_point(struct:ResponseMessageType_UnsignedInt32List) */
} ResponseMessageType_UnsignedInt32List;

typedef struct _ResponseMessageType_UnsignedInt64 {
    Response_Header header;
    Comm_Property property;
    MessageType_UnsignedInt64 data;
/* @@protoc_insertion_point(struct:ResponseMessageType_UnsignedInt64) */
} ResponseMessageType_UnsignedInt64;

typedef struct _ResponseMessageType_UnsignedInt64List {
    Response_Header header;
    Comm_Property property;
    MessageType_UnsignedInt64List data;
/* @@protoc_insertion_point(struct:ResponseMessageType_UnsignedInt64List) */
} ResponseMessageType_UnsignedInt64List;

typedef struct _ResponseMessageType_Void {
    Response_Header header;
    Comm_Property property;
/* @@protoc_insertion_point(struct:ResponseMessageType_Void) */
} ResponseMessageType_Void;

/* Default values for struct fields */

/* Initializer values for message structs */
#define ResponseMessageType_Bool_init_default    {Response_Header_init_default, Comm_Property_init_default, MessageType_Bool_init_default}
#define ResponseMessageType_Int32_init_default   {Response_Header_init_default, Comm_Property_init_default, MessageType_Int32_init_default}
#define ResponseMessageType_UnsignedInt32_init_default {Response_Header_init_default, Comm_Property_init_default, MessageType_UnsignedInt32_init_default}
#define ResponseMessageType_Int64_init_default   {Response_Header_init_default, Comm_Property_init_default, MessageType_Int64_init_default}
#define ResponseMessageType_UnsignedInt64_init_default {Response_Header_init_default, Comm_Property_init_default, MessageType_UnsignedInt64_init_default}
#define ResponseMessageType_Double_init_default  {Response_Header_init_default, Comm_Property_init_default, MessageType_Double_init_default}
#define ResponseMessageType_Float_init_default   {Response_Header_init_default, Comm_Property_init_default, MessageType_Float_init_default}
#define ResponseMessageType_Bytes_init_default   {Response_Header_init_default, Comm_Property_init_default, MessageType_Bytes_init_default}
#define ResponseMessageType_String_init_default  {Response_Header_init_default, Comm_Property_init_default, MessageType_String_init_default}
#define ResponseMessageType_Void_init_default    {Response_Header_init_default, Comm_Property_init_default}
#define ResponseMessageType_BoolList_init_default {Response_Header_init_default, Comm_Property_init_default, MessageType_Bool_init_default}
#define ResponseMessageType_Int32List_init_default {Response_Header_init_default, Comm_Property_init_default, MessageType_Int32List_init_default}
#define ResponseMessageType_UnsignedInt32List_init_default {Response_Header_init_default, Comm_Property_init_default, MessageType_UnsignedInt32List_init_default}
#define ResponseMessageType_Int64List_init_default {Response_Header_init_default, Comm_Property_init_default, MessageType_Int64List_init_default}
#define ResponseMessageType_UnsignedInt64List_init_default {Response_Header_init_default, Comm_Property_init_default, MessageType_UnsignedInt64List_init_default}
#define ResponseMessageType_DoubleList_init_default {Response_Header_init_default, Comm_Property_init_default, MessageType_DoubleList_init_default}
#define ResponseMessageType_FloatList_init_default {Response_Header_init_default, Comm_Property_init_default, MessageType_FloatList_init_default}
#define ResponseMessageType_Bool_init_zero       {Response_Header_init_zero, Comm_Property_init_zero, MessageType_Bool_init_zero}
#define ResponseMessageType_Int32_init_zero      {Response_Header_init_zero, Comm_Property_init_zero, MessageType_Int32_init_zero}
#define ResponseMessageType_UnsignedInt32_init_zero {Response_Header_init_zero, Comm_Property_init_zero, MessageType_UnsignedInt32_init_zero}
#define ResponseMessageType_Int64_init_zero      {Response_Header_init_zero, Comm_Property_init_zero, MessageType_Int64_init_zero}
#define ResponseMessageType_UnsignedInt64_init_zero {Response_Header_init_zero, Comm_Property_init_zero, MessageType_UnsignedInt64_init_zero}
#define ResponseMessageType_Double_init_zero     {Response_Header_init_zero, Comm_Property_init_zero, MessageType_Double_init_zero}
#define ResponseMessageType_Float_init_zero      {Response_Header_init_zero, Comm_Property_init_zero, MessageType_Float_init_zero}
#define ResponseMessageType_Bytes_init_zero      {Response_Header_init_zero, Comm_Property_init_zero, MessageType_Bytes_init_zero}
#define ResponseMessageType_String_init_zero     {Response_Header_init_zero, Comm_Property_init_zero, MessageType_String_init_zero}
#define ResponseMessageType_Void_init_zero       {Response_Header_init_zero, Comm_Property_init_zero}
#define ResponseMessageType_BoolList_init_zero   {Response_Header_init_zero, Comm_Property_init_zero, MessageType_Bool_init_zero}
#define ResponseMessageType_Int32List_init_zero  {Response_Header_init_zero, Comm_Property_init_zero, MessageType_Int32List_init_zero}
#define ResponseMessageType_UnsignedInt32List_init_zero {Response_Header_init_zero, Comm_Property_init_zero, MessageType_UnsignedInt32List_init_zero}
#define ResponseMessageType_Int64List_init_zero  {Response_Header_init_zero, Comm_Property_init_zero, MessageType_Int64List_init_zero}
#define ResponseMessageType_UnsignedInt64List_init_zero {Response_Header_init_zero, Comm_Property_init_zero, MessageType_UnsignedInt64List_init_zero}
#define ResponseMessageType_DoubleList_init_zero {Response_Header_init_zero, Comm_Property_init_zero, MessageType_DoubleList_init_zero}
#define ResponseMessageType_FloatList_init_zero  {Response_Header_init_zero, Comm_Property_init_zero, MessageType_FloatList_init_zero}

/* Field tags (for use in manual encoding/decoding) */
#define ResponseMessageType_Bool_header_tag      1
#define ResponseMessageType_Bool_property_tag    2
#define ResponseMessageType_Bool_data_tag        3
#define ResponseMessageType_BoolList_header_tag  1
#define ResponseMessageType_BoolList_property_tag 2
#define ResponseMessageType_BoolList_data_tag    3
#define ResponseMessageType_Bytes_header_tag     1
#define ResponseMessageType_Bytes_property_tag   2
#define ResponseMessageType_Bytes_data_tag       3
#define ResponseMessageType_Double_header_tag    1
#define ResponseMessageType_Double_property_tag  2
#define ResponseMessageType_Double_data_tag      3
#define ResponseMessageType_DoubleList_header_tag 1
#define ResponseMessageType_DoubleList_property_tag 2
#define ResponseMessageType_DoubleList_data_tag  3
#define ResponseMessageType_Float_header_tag     1
#define ResponseMessageType_Float_property_tag   2
#define ResponseMessageType_Float_data_tag       3
#define ResponseMessageType_FloatList_header_tag 1
#define ResponseMessageType_FloatList_property_tag 2
#define ResponseMessageType_FloatList_data_tag   3
#define ResponseMessageType_Int32_header_tag     1
#define ResponseMessageType_Int32_property_tag   2
#define ResponseMessageType_Int32_data_tag       3
#define ResponseMessageType_Int32List_header_tag 1
#define ResponseMessageType_Int32List_property_tag 2
#define ResponseMessageType_Int32List_data_tag   3
#define ResponseMessageType_Int64_header_tag     1
#define ResponseMessageType_Int64_property_tag   2
#define ResponseMessageType_Int64_data_tag       3
#define ResponseMessageType_Int64List_header_tag 1
#define ResponseMessageType_Int64List_property_tag 2
#define ResponseMessageType_Int64List_data_tag   3
#define ResponseMessageType_String_header_tag    1
#define ResponseMessageType_String_property_tag  2
#define ResponseMessageType_String_data_tag      3
#define ResponseMessageType_UnsignedInt32_header_tag 1
#define ResponseMessageType_UnsignedInt32_property_tag 2
#define ResponseMessageType_UnsignedInt32_data_tag 3
#define ResponseMessageType_UnsignedInt32List_header_tag 1
#define ResponseMessageType_UnsignedInt32List_property_tag 2
#define ResponseMessageType_UnsignedInt32List_data_tag 3
#define ResponseMessageType_UnsignedInt64_header_tag 1
#define ResponseMessageType_UnsignedInt64_property_tag 2
#define ResponseMessageType_UnsignedInt64_data_tag 3
#define ResponseMessageType_UnsignedInt64List_header_tag 1
#define ResponseMessageType_UnsignedInt64List_property_tag 2
#define ResponseMessageType_UnsignedInt64List_data_tag 3
#define ResponseMessageType_Void_header_tag      1
#define ResponseMessageType_Void_property_tag    2

/* Struct field encoding specification for nanopb */
extern const pb_field_t ResponseMessageType_Bool_fields[4];
extern const pb_field_t ResponseMessageType_Int32_fields[4];
extern const pb_field_t ResponseMessageType_UnsignedInt32_fields[4];
extern const pb_field_t ResponseMessageType_Int64_fields[4];
extern const pb_field_t ResponseMessageType_UnsignedInt64_fields[4];
extern const pb_field_t ResponseMessageType_Double_fields[4];
extern const pb_field_t ResponseMessageType_Float_fields[4];
extern const pb_field_t ResponseMessageType_Bytes_fields[4];
extern const pb_field_t ResponseMessageType_String_fields[4];
extern const pb_field_t ResponseMessageType_Void_fields[3];
extern const pb_field_t ResponseMessageType_BoolList_fields[4];
extern const pb_field_t ResponseMessageType_Int32List_fields[4];
extern const pb_field_t ResponseMessageType_UnsignedInt32List_fields[4];
extern const pb_field_t ResponseMessageType_Int64List_fields[4];
extern const pb_field_t ResponseMessageType_UnsignedInt64List_fields[4];
extern const pb_field_t ResponseMessageType_DoubleList_fields[4];
extern const pb_field_t ResponseMessageType_FloatList_fields[4];

/* Maximum encoded size of messages (where known) */
#define ResponseMessageType_Bool_size            43
#define ResponseMessageType_Int32_size           52
#define ResponseMessageType_UnsignedInt32_size   47
#define ResponseMessageType_Int64_size           52
#define ResponseMessageType_UnsignedInt64_size   52
#define ResponseMessageType_Double_size          50
#define ResponseMessageType_Float_size           46
#define ResponseMessageType_Bytes_size           1069
#define ResponseMessageType_String_size          1069
#define ResponseMessageType_Void_size            39
#define ResponseMessageType_BoolList_size        43
#define ResponseMessageType_Int32List_size       1450
#define ResponseMessageType_UnsignedInt32List_size 810
#define ResponseMessageType_Int64List_size       1450
#define ResponseMessageType_UnsignedInt64List_size 1450
#define ResponseMessageType_DoubleList_size      1194
#define ResponseMessageType_FloatList_size       682

/* Message IDs (where set with "msgid" option) */
#ifdef PB_MSGID

#define RESPONSE_BASE_MESSAGES \


#endif

#ifdef __cplusplus
} /* extern "C" */
#endif
/* @@protoc_insertion_point(eof) */

#endif
