/* Automatically generated nanopb header */
/* Generated by nanopb-0.3.7-dev at Tue Jul 24 13:50:06 2018. */

#ifndef PB_RESPONSEMESSAGETYPE_RESPONSE_PUBLISH_TABLE_PB_H_INCLUDED
#define PB_RESPONSEMESSAGETYPE_RESPONSE_PUBLISH_TABLE_PB_H_INCLUDED
#include <pb.h>

#include "protocal/response_header.pb.h"

#include "protocal/comm.pb.h"

#include "message_type/publish_table.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Struct definitions */
typedef struct _ResponseMessageType_PublishTable {
    Response_Header header;
    Comm_Property property;
    MessageType_PublishTable data;
/* @@protoc_insertion_point(struct:ResponseMessageType_PublishTable) */
} ResponseMessageType_PublishTable;

/* Default values for struct fields */

/* Initializer values for message structs */
#define ResponseMessageType_PublishTable_init_default {Response_Header_init_default, Comm_Property_init_default, MessageType_PublishTable_init_default}
#define ResponseMessageType_PublishTable_init_zero {Response_Header_init_zero, Comm_Property_init_zero, MessageType_PublishTable_init_zero}

/* Field tags (for use in manual encoding/decoding) */
#define ResponseMessageType_PublishTable_header_tag 1
#define ResponseMessageType_PublishTable_property_tag 2
#define ResponseMessageType_PublishTable_data_tag 3

/* Struct field encoding specification for nanopb */
extern const pb_field_t ResponseMessageType_PublishTable_fields[4];

/* Maximum encoded size of messages (where known) */
#define ResponseMessageType_PublishTable_size    (813 + 128*MessageType_PublishTableElement_size)

/* Message IDs (where set with "msgid" option) */
#ifdef PB_MSGID

#define RESPONSE_PUBLISH_TABLE_MESSAGES \


#endif

#ifdef __cplusplus
} /* extern "C" */
#endif
/* @@protoc_insertion_point(eof) */

#endif
