/* Automatically generated nanopb header */
/* Generated by nanopb-0.3.7-dev at Mon Aug  6 15:29:51 2018. */

#ifndef PB_RESPONSEMESSAGETYPE_RESPONSE_USER_FRAME_PB_H_INCLUDED
#define PB_RESPONSEMESSAGETYPE_RESPONSE_USER_FRAME_PB_H_INCLUDED
#include <pb.h>

#include "protocal/response_header.pb.h"

#include "protocal/comm.pb.h"

#include "message_type/user_frame.pb.h"

#include "message_type/base.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Struct definitions */
typedef struct _ResponseMessageType_Bool_UserInfo {
    Response_Header header;
    Comm_Property property;
    MessageType_Bool success;
    MessageType_UserInfo data;
/* @@protoc_insertion_point(struct:ResponseMessageType_Bool_UserInfo) */
} ResponseMessageType_Bool_UserInfo;

typedef struct _ResponseMessageType_UserSummaryList {
    Response_Header header;
    Comm_Property property;
    MessageType_UserSummaryList data;
/* @@protoc_insertion_point(struct:ResponseMessageType_UserSummaryList) */
} ResponseMessageType_UserSummaryList;

/* Default values for struct fields */

/* Initializer values for message structs */
#define ResponseMessageType_Bool_UserInfo_init_default {Response_Header_init_default, Comm_Property_init_default, MessageType_Bool_init_default, MessageType_UserInfo_init_default}
#define ResponseMessageType_UserSummaryList_init_default {Response_Header_init_default, Comm_Property_init_default, MessageType_UserSummaryList_init_default}
#define ResponseMessageType_Bool_UserInfo_init_zero {Response_Header_init_zero, Comm_Property_init_zero, MessageType_Bool_init_zero, MessageType_UserInfo_init_zero}
#define ResponseMessageType_UserSummaryList_init_zero {Response_Header_init_zero, Comm_Property_init_zero, MessageType_UserSummaryList_init_zero}

/* Field tags (for use in manual encoding/decoding) */
#define ResponseMessageType_Bool_UserInfo_header_tag 1
#define ResponseMessageType_Bool_UserInfo_property_tag 2
#define ResponseMessageType_Bool_UserInfo_success_tag 3
#define ResponseMessageType_Bool_UserInfo_data_tag 4
#define ResponseMessageType_UserSummaryList_header_tag 1
#define ResponseMessageType_UserSummaryList_property_tag 2
#define ResponseMessageType_UserSummaryList_data_tag 3

/* Struct field encoding specification for nanopb */
extern const pb_field_t ResponseMessageType_Bool_UserInfo_fields[5];
extern const pb_field_t ResponseMessageType_UserSummaryList_fields[4];

/* Maximum encoded size of messages (where known) */
#define ResponseMessageType_Bool_UserInfo_size   (370 + MessageType_PoseEuler_size)
#define ResponseMessageType_UserSummaryList_size 5130

/* Message IDs (where set with "msgid" option) */
#ifdef PB_MSGID

#define RESPONSE_USER_FRAME_MESSAGES \


#endif

#ifdef __cplusplus
} /* extern "C" */
#endif
/* @@protoc_insertion_point(eof) */

#endif
