io_info:
    coil:
        addr: 0
        nb: 1024
    discrepte_input:
        addr: 0
        nb: 1024
    holding_register:
        addr: 0
        nb: 0
    input_register:
        addr: 0
        nb: 0
#END