ip: local_host 

name: ModbusServer
is_enable: false
response_delay: 0

reg_info:
    coil:
        addr: 1
        max_nb: 256
    discrepte_input:
        addr: 1
        max_nb: 256
    input_register:
        addr: 1
        max_nb: 120
    holding_register:
        addr: 1
        max_nb: 120
#END