name: axis_application_1001
param_model_id: 
    operation_value: 1001
    default_value: 1001
    upper_limit_value: 0 
    lower_limit_value: 0
    unit: NULL
    attr: 1
    validity: 0
model_class: 
    operation_value: 2
    default_value: 2
    upper_limit_value: 2 
    lower_limit_value: 0
    unit: NULL
    attr: 1
    validity: 0
model_gear_ratio_numerator: 
    operation_value: 1
    default_value: 1
    upper_limit_value: 1000 
    lower_limit_value: 1
    unit: NULL
    attr: 1
    validity: 0
model_gear_ratio_denominator: 
    operation_value: 1
    default_value: 1
    upper_limit_value: 1000 
    lower_limit_value: 1
    unit: NULL
    attr: 1
    validity: 0
model_pitch: 
    operation_value: 5000
    default_value: 5000
    upper_limit_value: 0 
    lower_limit_value: 0
    unit: 0.001mm
    attr: 1
    validity: 0
model_linear_range: 
    operation_value: 213000
    default_value: 213000
    upper_limit_value: 0 
    lower_limit_value: 0
    unit: 0.001mm
    attr: 1
    validity: 0
model_direction: 
    operation_value: 1
    default_value: 1
    upper_limit_value: 1 
    lower_limit_value: 0
    unit: NULL
    attr: 3
    validity: 1
model_hw_limit_enable: 
    operation_value: 1
    default_value: 1
    upper_limit_value: 1 
    lower_limit_value: 0
    unit: NULL
    attr: 3
    validity: 1
model_hw_positive_limit: 
    operation_value: 121000
    default_value: 121000
    upper_limit_value: 0 
    lower_limit_value: 0
    unit: 0.001mm
    attr: 3
    validity: 1
model_hw_negative_limit: 
    operation_value: -92000
    default_value: -92000
    upper_limit_value: 0 
    lower_limit_value: 0
    unit: 0.001mm
    attr: 3
    validity: 1
encoder_pulse_per_revolution: 
    operation_value: 8388608
    default_value: 8388608
    upper_limit_value: 10000000 
    lower_limit_value: 1
    unit: NULL
    attr: 1
    validity: 0
motor_rated_torque:
    operation_value: 127
    default_value: 127
    upper_limit_value: 100000
    lower_limit_value: 0
    unit: 0.01N*m
    attr: 1
    validity: 0
app_max_vel: 
    operation_value: 50
    default_value: 50
    upper_limit_value: 1000000000 
    lower_limit_value: 0
    unit: rps
    attr: 3
    validity: 3
app_acc_time: 
    operation_value: 80
    default_value: 80
    upper_limit_value: 100000 
    lower_limit_value: 0
    unit: ms
    attr: 3
    validity: 3
app_dec_time: 
    operation_value: 80
    default_value: 80
    upper_limit_value: 100000 
    lower_limit_value: 0
    unit: ms
    attr: 3
    validity: 3
app_home_high_speed: 
    operation_value: 50
    default_value: 50
    upper_limit_value: 1000000000 
    lower_limit_value: 0
    unit: rps
    attr: 3
    validity: 3
app_home_low_speed: 
    operation_value: 50
    default_value: 50
    upper_limit_value: 1000000000 
    lower_limit_value: 0
    unit: rps
    attr: 3
    validity: 3
app_home_acc_time: 
    operation_value: 500
    default_value: 500
    upper_limit_value: 100000 
    lower_limit_value: 0
    unit: ms
    attr: 3
    validity: 3
app_sf_limit_enable: 
    operation_value: 1
    default_value: 1
    upper_limit_value: 1 
    lower_limit_value: 0
    unit: NULL
    attr: 3
    validity: 3
app_sf_positive_limit: 
    operation_value: 121000
    default_value: 121000
    upper_limit_value: 0
    lower_limit_value: 0
    unit: 0.001mm
    attr: 3
    validity: 3
app_sf_negative_limit:
    operation_value: -92000
    default_value: -92000
    upper_limit_value: 0
    lower_limit_value: 0
    unit: 0.001mm
    attr: 3
    validity: 3
app_home_position:
    operation_value: 0
    default_value: 0
    upper_limit_value: 0
    lower_limit_value: 0
    unit: 0.001mm
    attr: 3
    validity: 3