DH_parameter:
    j1:
        alpha:  0.0
        a:      0.0
        d:      365.0
        theta:  0.0
    j2:
        alpha:  1.5707963267948966192313216916398
        a:      30.0
        d:      0.0
        theta:  1.5707963267948966192313216916398
    j3:
        alpha:  0.0
        a:      340.0
        d:      0.0
        theta:  0.0
    j4:
        alpha:  1.5707963267948966192313216916398
        a:      35.0
        d:      350.0
        theta:  0.0
    j5:
        alpha:  -1.5707963267948966192313216916398
        a:      0.0
        d:      0.0
        theta:  0.0
    j6:
        alpha:  1.5707963267948966192313216916398
        a:      0.0
        d:      96.5
        theta:  0.0
    j7:
        alpha:  0.0
        a:      0.0
        d:      0.0
        theta:  0.0
    j8:
        alpha:  0.0
        a:      0.0
        d:      0.0
        theta:  0.0
    j9:
        alpha:  0.0
        a:      0.0
        d:      0.0
        theta:  0.0
#END
