hard_constraint:
    j1:
        upper: 3.0020
        lower: -3.0020
    j2:
        upper: 1.7977
        lower: -2.3911
    j3:
        upper: 3.4906
        lower: -1.2217
    j4:
        upper: 3.3161
        lower: -3.3161
    j5:
        upper: 2.0246
        lower: -2.0246
    j6:
        upper: 6.2832
        lower: -6.2832
    j7:
        upper: 0.0
        lower: 0.0
    j8:
        upper: 0.0
        lower: 0.0
    j9:
        upper: 0.0
        lower: 0.0
#END
