cycle_time: 0.001                           # s
cycle_distance: 1.0                         # mm
cycle_radian: 0.01                           # rad

cartesian:
    velocity:
        min: 1.0                            # mm/s
        max: 4000.0                         # mm/s
        default: 500.0                      # mm/s
        reference: 1000.0                   # mm/s
    acceleration:
        min: 1.0                            # mm/s^2
        max: 32000.0                        # mm/s^2
        default: 7000.0                     # mm/s^2
        reference: 4000.0                   # mm/s^2
    orientation:
        omega_reference: 1.0                # rad/s
        alpha_reference: 4.0                # rad/s^2
        linear_polation_threshold: 0.1      # rad

joint:
    omega:
        default: 1.0                        # 0% - 100%
        limit:
            - 5.5851
            - 6.2832
            - 6.9813
            - 6.2832
            - 4.1888
            - 12.5664
    alpha:
        default: 1.0                        # 0% - 100%
        limit:
            - 6.9813
            - 7.8504
            - 13.9626
            - 12.5664
            - 10.4720
            - 31.4159

manual:
    step_length:
        joint: 0.1                          # rad
        position: 1.0                       # mm
        orientation: 0.01                   # rad


#END
