log_level: 0
routine_cycle_time: 10000
planner_cycle_time: 10000
priority_cycle_time: 10000 
realtime_cycle_time: 2000 
rpc_cycle_time: 2000
online_traj_cycle_time: 2000
dev_process_cycle_time: 200000
routine_thread_priority: 50 
planner_thread_priority: 60 
priority_thread_priority: 70
realtime_thread_priority: 80 
rpc_thread_priority: 55 
online_traj_thread_priority: 55 
dev_process_thread_priority: 50 
dio_exist: false
safety_exist: true
fio_exist: true
#END
