log_level: 1
routine_cycle_time: 10000
heartbeat_cycle_time: 10000 
routine_thread_priority: 50 
reset_max_time: 4000000
robot_state_timeout: 1000000
enable_controller_heartbeat: true
heartbeat_thread_priority: 50 
enable_log_service: true
enable_virtual_core1: false 
virtual_core1_thread_priority: 50
max_reg_publish_number: 32
max_io_publish_number: 32
max_continuous_manual_move_timeout: 1000000
max_unknown_user_op_mode_timeout: 1000000
max_limited_global_vel_ratio: 0.1
max_limited_global_acc_ratio: 0.1 
enable_set_vel_in_auto: true
#END
