/**
 * @file common.h
 * @brief 
 * @author WangWei
 * @version 1.0.0
 * @date 2016-08-17
 */
#ifndef _COMMON_H_
#define _COMMON_H_


typedef enum _FST_ROBOT_MODE
{
	INIT_M					= 0,	
	PAUSE_M					= 1,
	AUTO_RUN_M				= 2,
	MANUAL_JOINT_MODE_M		= 3,
	MANUAL_CART_MODE_M		= 4,
	AUTO_RESET_M			= 5,

	AUTO_RUN_TO_PAUSE_T				= 201,
	PAUSE_TO_AUTO_RUN_T				= 102,
	PAUSE_TO_MANUAL_JOINT_T			= 103,
	PAUSE_TO_MANUAL_CART_T			= 104,
	MANUAL_CART_TO_PAUSE_T			= 401,
	MANUAL_JOINT_TO_PAUSE_T			= 301,
	MANUAL_CART_TO_MANUAL_JOINT_T	= 403,
	MANUAL_JOINT_MANUAL_CART_T		= 304
}FST_ROBOT_MODE;

typedef enum _FST_ROBOT_MODE_CMD
{
	GOTO_NONE_E					= -1,
	GOTO_PAUSE_E				= 1,
	GOTO_AUTO_RUN_E				= 2,
	GOTO_MANUAL_JOINT_MODE_E	= 3,
	GOTO_MANUAL_CART_MODE_E		= 4,
	GOTO_AUTO_RESET_E			= 5
}FST_ROBOT_MODE_CMD;

typedef enum _FST_ROBOT_STATE
{
	INIT_S			= 0,
	OFF_S			= 1,
	DISENGAGED		= 2,
	RETARCT_S		= 3,
	ENGAGED_S		= 4,
	CALIBRATE_S		= 5,

	OFF_TO_DISENGAGED_T		= 102,
	OFF_TO_CALIBRATE_T		= 105,
	DISENGAGED_TO_OFF_T		= 201,
	DISENGAGED_TO_RETRACT_T = 203,
	RETARCT_TO_DISENGAGED_T	= 302,
	DISENGAGED_TO_ENGAGED_T = 204,
	ENGAGED_TO_DISENGAGED_T = 402
}FST_ROBOT_STATE;

typedef enum _FST_ROBOT_STATE_CMD
{
	DO_NOTHING			= -1,
	GOTO_OFF			= 0,
	GOTO_DISENGAGED_E	= 1,
	GOTO_ENGAGED_E		= 2,
	GOTO_RETRACT_E		= 3,
	GOTO_CALIBRATE		= 4,
	FORCE_DISENGAGE_E	= 5
}FST_ROBOT_STATE_CMD;

#endif
