zero_offset:
    id: 256                 # ID = 0x0100
    data:
        - 0.0
        - 0.0
        - 0.0
        - 0.0
        - 0.0
        - 0.0
        - 0.0
        - 0.0

gear_ratio:
    id: 272                 # ID = 0x0110
    data:
        - -92.3023255813953
        - -121.0
        - 80.0
        - -53.6842105263158
        - 75.0
        - 42.8571428571428
        - 1.0
        - 1.0

coupling_coefficient:
    id: 288                 # ID = 0x0120
    data: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.02]

trajectory_delay:
    id: 304                 # ID = 0x0130
    data: [0.05]
#END
