last_time: 1970-01-01 00:00:00
last_joint:
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
flag:
    - 0 
    - 0 
    - 0 
    - 0 
    - 0 
    - 0 
    - 0 
    - 0 
    - 0 
#END
