log_level: 1
number_of_links: 6
acc_scale_factor: 0.5 #0.01~1.0
max_torque:
    - 677.16
    - 674.68
    - 361.26
    - 134.4
    - 74.0
    - 59.55
m_load: 0.0
lcx_load: 0.0
lcy_load: 0.0
lcz_load: 0.0
Ixx_load: 0.0
Iyy_load: 0.0
Izz_load: 0.0
Ixy_load: 0.0
Ixz_load: 0.0
Iyz_load: 0.0
link_0:
    XXR: 0.0
    XY: 0.0
    XYR: 0.0
    XZ: 0.0
    XZR: 0.0
    YZ: 0.0
    ZZ: 0.0
    ZZR: 3.422
    MX: 0.0
    MXR: 0.0
    MY: 0.0
    MYR: 0.0
    Im: 0.0
    FS: 15.2919
    FV: 17.377
link_1:
    XXR: 2.802
    XY:  1.529
    XYR: 0.0
    XZ: 0.0
    XZR: -0.332
    YZ: -0.034
    ZZ: 0.0
    ZZR: 6.125
    MX: 0.0
    MXR: -0.075
    MY: 6.0336
    MYR: 0.0
    Im: 0.0
    FS: 30.176
    FV: 41.193
link_2:
    XXR: 1.3088
    XY: 0.0
    XYR: -0.929
    XZ: -0.35
    XZR: 0.0
    YZ: -0.285
    ZZ: 0.0
    ZZR: 1.8847
    MX: 0.0
    MXR: 1.72
    MY: 0.0
    MYR: 0.4594
    Im: 0.085
    FS: 12.6059
    FV: 11.7846
link_3:
    XXR: -0.423
    XY: 0.348
    XYR: 0.0
    XZ: -0.497
    XZR: 0.0
    YZ: 0.3447
    ZZ: 0.0
    ZZR: 0.2317
    MX: 0.0344
    MXR: 0.0
    MY: 0.0
    MYR: -0.0078
    Im: 0.235
    FS: 5.787
    FV: 5.645
link_4:
    XXR: 0.203
    XY: 0.0428
    XYR: 0.0
    XZ: 0.0125
    XZR: 0.0
    YZ: 0.1029
    ZZ: 0.0
    ZZR: 0.00567
    MX: 0.015
    MXR: 0.0
    MY: 0.0
    MYR: 0.019
    Im: 0.1496
    FS: 3.7969
    FV: 4.5655
link_5:
    XXR: -0.0563
    XY: -0.0298
    XYR: 0.0
    XZ: 0.149
    XZR: 0.0
    YZ: -0.0885
    ZZ: 0.142
    ZZR: 0.0
    MX: -0.072
    MXR: 0.0
    MY: 0.0514
    MYR: 0.0
    Im: -0.0443
    FS: 3.6577
    FV: 2.4897
#END
