log_level: 1
number_of_links: 6
max_torque:
    - 1.1
    - 2.2
    - 3.3
    - 4.4
    - 5.5
    - 6.6
m_load: 0.0
lcx_load: 0.0
lcy_load: 0.0
lcz_load: 0.0
Ixx_load: 0.0
Iyy_load: 0.0
Izz_load: 0.0
Ixy_load: 0.0
Ixz_load: 0.0
Iyz_load: 0.0
link_0:
    XXR: 0.0
    XY: 0.0
    XYR: 0.0
    XZ: 0.0
    XZR: 0.0
    YZ: 0.0
    ZZ: 0.0
    ZZR: 4.4422
    MX: 0.0
    MXR: 0.0
    MY: 0.0
    MYR: 0.0
    Im: 0.0
    FS: 18.098
    FV: 20.904
link_1:
    XXR: 2.8681
    XY: -1.8825
    XYR: 0.0
    XZ: 0.0
    XZR: -2.766
    YZ: -0.30968
    ZZ: 0.0
    ZZR: 6.8069
    MX: 0.0
    MXR: -0.48049
    MY: -5.3694
    MYR: 0.0
    Im: 0.0
    FS: 9.8725
    FV: 48.124
link_2:
    XXR: 0.16869
    XY: 0.0
    XYR: -0.64756
    XZ: -1.2098
    XZR: 0.0
    YZ: -1.0284
    ZZ: 0.0
    ZZR: 1.8109
    MX: 0.0
    MXR: -1.5038
    MY: 0.0
    MYR: -1.0835
    Im: 0.11902
    FS: 6.2768
    FV: 18.144
link_3:
    XXR: 0.75468
    XY: 0.77181
    XYR: 0.0
    XZ: -0.096175
    XZR: 0.0
    YZ: -1.0139
    ZZ: 0.0
    ZZR: -1.5587
    MX: -0.049204
    MXR: 0.0
    MY: 0.0
    MYR: -0.59913
    Im: 1.0685
    FS: 1.6369
    FV: 7.2242
link_4:
    XXR: 2.011
    XY: 0.16856
    XYR: 0.0
    XZ: -0.16502
    XZR: 0.0
    YZ: 0.65657
    ZZ: 0.0
    ZZR: 1.892
    MX: 0.74715
    MXR: 0.0
    MY: 0.0
    MYR: 0.7456
    Im: 1.3378
    FS: 3.0259
    FV: 10.963
link_5:
    XXR: -0.3696
    XY: -0.26786
    XYR: 0.0
    XZ: -0.28879
    XZR: 0.0
    YZ: -0.26229
    ZZ: 0.61266
    ZZR: 0.0
    MX: 0.16604
    MXR: 0.0
    MY: -0.0917
    MYR: 0.0
    Im: -0.33699
    FS: 3.4088
    FV: 3.8218
#END
