max_comment_length: 32
max_number_of_payloads: 10
payload1:
    id: 1
    is_valid: true
    comment: default
    m_load: 1.0
    lcx_load: 1.1
    lcy_load: 1.2
    lcz_load: 1.3
    Ixx_load: 1.4
    Iyy_load: 1.5
    Izz_load: 0.0
payload2:
    id: 2
    is_valid: true
    comment: default
    m_load: 2.0
    lcx_load: 2.1
    lcy_load: 2.2
    lcz_load: 0.0
    Ixx_load: 0.0
    Iyy_load: 0.0
    Izz_load: 0.0
payload3:
    id: 3
    is_valid: true
    comment: default
    m_load: 3.0
    lcx_load: 3.1
    lcy_load: 3.2
    lcz_load: 3.3
    Ixx_load: 0.0
    Iyy_load: 0.0
    Izz_load: 0.0
payload4:
    id: 4
    is_valid: false
    comment: default
    m_load: 0.0
    lcx_load: 0.0
    lcy_load: 0.0
    lcz_load: 0.0
    Ixx_load: 0.0
    Iyy_load: 0.0
    Izz_load: 0.0
payload5:
    id: 5
    is_valid: false
    comment: default
    m_load: 0.0
    lcx_load: 0.0
    lcy_load: 0.0
    lcz_load: 0.0
    Ixx_load: 0.0
    Iyy_load: 0.0
    Izz_load: 0.0
payload6:
    id: 6
    is_valid: false
    comment: default
    m_load: 0.0
    lcx_load: 0.0
    lcy_load: 0.0
    lcz_load: 0.0
    Ixx_load: 0.0
    Iyy_load: 0.0
    Izz_load: 0.0
payload7:
    id: 7
    is_valid: false
    comment: default
    m_load: 0.0
    lcx_load: 0.0
    lcy_load: 0.0
    lcz_load: 0.0
    Ixx_load: 0.0
    Iyy_load: 0.0
    Izz_load: 0.0
payload8:
    id: 8
    is_valid: false
    comment: default
    m_load: 0.0
    lcx_load: 0.0
    lcy_load: 0.0
    lcz_load: 0.0
    Ixx_load: 0.0
    Iyy_load: 0.0
    Izz_load: 0.0
payload9:
    id: 9
    is_valid: false
    comment: default
    m_load: 0.0
    lcx_load: 0.0
    lcy_load: 0.0
    lcz_load: 0.0
    Ixx_load: 0.0
    Iyy_load: 0.0
    Izz_load: 0.0
payload10:
    id: 10
    is_valid: false
    comment: default
    m_load: 0.0
    lcx_load: 0.0
    lcy_load: 0.0
    lcz_load: 0.0
    Ixx_load: 0.0
    Iyy_load: 0.0
    Izz_load: 0.0
#END
