/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.7-dev at Thu Jul 19 16:17:04 2018. */

#include "protocal/publish.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t CommPublish_PublishElement_fields[3] = {
    PB_FIELD(  1, UINT32  , REQUIRED, STATIC  , FIRST, CommPublish_PublishElement, hash, hash, 0),
    PB_FIELD(  2, BYTES   , REQUIRED, CALLBACK, OTHER, CommPublish_PublishElement, data, hash, 0),
    PB_LAST_FIELD
};

const pb_field_t CommPublish_Publish_fields[3] = {
    PB_FIELD(  1, UINT64  , REQUIRED, STATIC  , FIRST, CommPublish_Publish, time_stamp, time_stamp, 0),
    PB_FIELD(  2, MESSAGE , REPEATED, STATIC  , OTHER, CommPublish_Publish, element, time_stamp, &CommPublish_PublishElement_fields),
    PB_LAST_FIELD
};


/* Check that field information fits in pb_field_t */
#if !defined(PB_FIELD_32BIT)
/* If you get an error here, it means that you need to define PB_FIELD_32BIT
 * compile-time option. You can do that in pb.h or on compiler command line.
 * 
 * The reason you need to do this is that some of your messages contain tag
 * numbers or field sizes that are larger than what can fit in 8 or 16 bit
 * field descriptors.
 */
PB_STATIC_ASSERT((pb_membersize(CommPublish_Publish, element[0]) < 65536), YOU_MUST_DEFINE_PB_FIELD_32BIT_FOR_MESSAGES_CommPublish_PublishElement_CommPublish_Publish)
#endif

#if !defined(PB_FIELD_16BIT) && !defined(PB_FIELD_32BIT)
#error Field descriptor for CommPublish_Publish.element is too large. Define PB_FIELD_16BIT to fix this.
#endif


/* @@protoc_insertion_point(eof) */
