coord1:
    id: 1
    is_valid: false
    name: default
    comment: default
    group_id: -1
    point:
        x: 0
        y: 0
        z: 0
    euler:
        a: 0
        b: 0
        c: 0
coord2:
    id: 2
    is_valid: false
    name: default
    comment: default
    group_id: -1
    point:
        x: 0
        y: 0
        z: 0
    euler:
        a: 0
        b: 0
        c: 0
coord3:
    id: 3
    is_valid: false
    name: default
    comment: default
    group_id: -1
    point:
        x: 0
        y: 0
        z: 0
    euler:
        a: 0
        b: 0
        c: 0
coord4:
    id: 4
    is_valid: false
    name: default
    comment: default
    group_id: -1
    point:
        x: 0
        y: 0
        z: 0
    euler:
        a: 0
        b: 0
        c: 0
coord5:
    id: 5
    is_valid: false
    name: default
    comment: default
    group_id: -1
    point:
        x: 0
        y: 0
        z: 0
    euler:
        a: 0
        b: 0
        c: 0
coord6:
    id: 6
    is_valid: false
    name: default
    comment: default
    group_id: -1
    point:
        x: 0
        y: 0
        z: 0
    euler:
        a: 0
        b: 0
        c: 0
coord7:
    id: 7
    is_valid: false
    name: default
    comment: default
    group_id: -1
    point:
        x: 0
        y: 0
        z: 0
    euler:
        a: 0
        b: 0
        c: 0
coord8:
    id: 8
    is_valid: false
    name: default
    comment: default
    group_id: -1
    point:
        x: 0
        y: 0
        z: 0
    euler:
        a: 0
        b: 0
        c: 0
coord9:
    id: 9
    is_valid: false
    name: default
    comment: default
    group_id: -1
    point:
        x: 0
        y: 0
        z: 0
    euler:
        a: 0
        b: 0
        c: 0
coord10:
    id: 10
    is_valid: false
    name: default
    comment: default
    group_id: -1
    point:
        x: 0
        y: 0
        z: 0
    euler:
        a: 0
        b: 0
        c: 0
#END
