/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.7 at Thu Sep 19 11:38:02 2019. */

#include "base.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t MessageType_Bool_fields[2] = {
    PB_FIELD(  1, BOOL    , REQUIRED, STATIC  , FIRST, MessageType_Bool, data, data, 0),
    PB_LAST_FIELD
};

const pb_field_t MessageType_Int32_fields[2] = {
    PB_FIELD(  1, INT32   , REQUIRED, STATIC  , FIRST, MessageType_Int32, data, data, 0),
    PB_LAST_FIELD
};

const pb_field_t MessageType_Uint32_fields[2] = {
    PB_FIELD(  1, UINT32  , REQUIRED, STATIC  , FIRST, MessageType_Uint32, data, data, 0),
    PB_LAST_FIELD
};

const pb_field_t MessageType_Int64_fields[2] = {
    PB_FIELD(  1, INT64   , REQUIRED, STATIC  , FIRST, MessageType_Int64, data, data, 0),
    PB_LAST_FIELD
};

const pb_field_t MessageType_Uint64_fields[2] = {
    PB_FIELD(  1, UINT64  , REQUIRED, STATIC  , FIRST, MessageType_Uint64, data, data, 0),
    PB_LAST_FIELD
};

const pb_field_t MessageType_Double_fields[2] = {
    PB_FIELD(  1, DOUBLE  , REQUIRED, STATIC  , FIRST, MessageType_Double, data, data, 0),
    PB_LAST_FIELD
};

const pb_field_t MessageType_Float_fields[2] = {
    PB_FIELD(  1, FLOAT   , REQUIRED, STATIC  , FIRST, MessageType_Float, data, data, 0),
    PB_LAST_FIELD
};

const pb_field_t MessageType_Bytes_fields[2] = {
    PB_FIELD(  1, BYTES   , REQUIRED, STATIC  , FIRST, MessageType_Bytes, data, data, 0),
    PB_LAST_FIELD
};

const pb_field_t MessageType_String_fields[2] = {
    PB_FIELD(  1, STRING  , REQUIRED, STATIC  , FIRST, MessageType_String, data, data, 0),
    PB_LAST_FIELD
};

const pb_field_t MessageType_BoolList_fields[2] = {
    PB_FIELD(  1, BOOL    , REPEATED, STATIC  , FIRST, MessageType_BoolList, data, data, 0),
    PB_LAST_FIELD
};

const pb_field_t MessageType_Int32List_fields[2] = {
    PB_FIELD(  1, INT32   , REPEATED, STATIC  , FIRST, MessageType_Int32List, data, data, 0),
    PB_LAST_FIELD
};

const pb_field_t MessageType_Uint32List_fields[2] = {
    PB_FIELD(  1, UINT32  , REPEATED, STATIC  , FIRST, MessageType_Uint32List, data, data, 0),
    PB_LAST_FIELD
};

const pb_field_t MessageType_Int64List_fields[2] = {
    PB_FIELD(  1, INT64   , REPEATED, STATIC  , FIRST, MessageType_Int64List, data, data, 0),
    PB_LAST_FIELD
};

const pb_field_t MessageType_Uint64List_fields[2] = {
    PB_FIELD(  1, UINT64  , REPEATED, STATIC  , FIRST, MessageType_Uint64List, data, data, 0),
    PB_LAST_FIELD
};

const pb_field_t MessageType_FloatList_fields[2] = {
    PB_FIELD(  1, FLOAT   , REPEATED, STATIC  , FIRST, MessageType_FloatList, data, data, 0),
    PB_LAST_FIELD
};

const pb_field_t MessageType_DoubleList_fields[2] = {
    PB_FIELD(  1, DOUBLE  , REPEATED, STATIC  , FIRST, MessageType_DoubleList, data, data, 0),
    PB_LAST_FIELD
};


/* Check that field information fits in pb_field_t */
#if !defined(PB_FIELD_32BIT)
#error Field descriptor for MessageType_Bytes.data is too large. Define PB_FIELD_32BIT to fix this.
#endif


/* On some platforms (such as AVR), double is really float.
 * These are not directly supported by nanopb, but see example_avr_double.
 * To get rid of this error, remove any double fields from your .proto.
 */
PB_STATIC_ASSERT(sizeof(double) == 8, DOUBLE_MUST_BE_8_BYTES)

/* @@protoc_insertion_point(eof) */
