number_of_axis: 6
step:
    axis:
        - 0.1
        - 0.1
        - 0.1
        - 0.1
        - 0.1
        - 0.1
    position: 0.1
    orientation: 0.1
reference:
    axis:
        move_to_point_velocity:
            - 0.174533
            - 0.174533
            - 0.174533
            - 0.174533
            - 0.174533
            - 0.174533
        velocity:
            - 1.0
            - 1.0
            - 1.0
            - 1.0
            - 1.0
            - 1.0
        acceleration:
            - 10.0
            - 10.0
            - 10.0
            - 10.0
            - 10.0
            - 10.0
    position:
        velocity: 200.0
        acceleration: 2000.0
    orientation:
        omega: 0.5
        alpha: 5.0


#END
