firm_constraint:
    lower:
        - -2.9020
        - -2.2911
        - -1.1217
        - -3.216
        - -1.9246
        - -6.1832
        - 0.0
        - 0.0
        - 0.0
    upper:
        - 2.9020
        - 1.6977
        - 3.3906
        - 3.2161
        - 1.9246
        - 6.1832
        - 0.0
        - 0.0
        - 0.0
#END