firm_constraint:
    lower:
        - -572.0
        - -1.97
        - -2.68
        - -2.12
        - 0.0
        - 0.0
        - 0.0
        - 0.0
        - 0.0
    upper:
        - 572.0
        - 1.97
        - 2.68
        - 2.12
        - 0.0
        - 0.0
        - 0.0
        - 0.0
        - 0.0
#END
