number_of_point: 0
point_0:
    - 0.0
    - 0.0
    - 0.0
    - 0.0
point_1:
    - 0.0
    - 0.0
    - 0.0
    - 0.0
point_2:
    - 0.0
    - 0.0
    - 0.0
    - 0.0
point_3:
    - 0.0
    - 0.0
    - 0.0
    - 0.0
point_4:
    - 0.0
    - 0.0
    - 0.0
    - 0.0
point_5:
    - 0.0
    - 0.0
    - 0.0
    - 0.0
point_6:
    - 0.0
    - 0.0
    - 0.0
    - 0.0
point_7:
    - 0.0
    - 0.0
    - 0.0
    - 0.0
point_8:
    - 0.0
    - 0.0
    - 0.0
    - 0.0
point_9:
    - 0.0
    - 0.0
    - 0.0
    - 0.0
#END
