hard_constraint:
    lower:
        - -575.0
        - -1.9722
        - -2.6878
        - -2.1293
        - 0.0
        - 0.0
        - 0.0
        - 0.0
        - 0.0
    upper:
        - 575.0
        - 1.9722
        - 2.6878
        - 2.1293
        - 0.0
        - 0.0
        - 0.0
        - 0.0
        - 0.0
#END