hard_constraint:
    lower:
        - -3.0020
        - -2.3911
        - -1.2217
        - -3.3161
        - -2.0246
        - -6.2832
        - 0.0
        - 0.0
        - 0.0
    upper:
        - 3.0020
        - 1.7977
        - 3.4906
        - 3.3161
        - 2.0246
        - 6.2832
        - 0.0
        - 0.0
        - 0.0
#END