model_name: "SCARA"
#model: "PUMA"
realtime_task:
    cycle_time: 2       # ms
non_realtime_task:
    cycle_time: 2      # ms
simulator:
    enable: false
    cycle_per_publish: 25
log_level: 1

#END
