number_of_axis: 4
type_of_axis:
    - 1
    - 0
    - 0
    - 0
joint:
    omega:
        - 1200.0
        - 5.77
        - 6.15
        - 54.54
    alpha:
        - 3600.0
        - 16.0
        - 18.0
        - 160.0

#END
