number_of_axis: 4
step:
    axis:
        - 1.0
        - 0.1
        - 0.1
        - 0.1
    position: 0.1
    orientation: 0.1
reference:
    axis:
        move_to_point_velocity:
            - 20.0
            - 0.174533
            - 0.174533
            - 0.174533
            - 0.174533
            - 0.174533
        velocity:
            - 200.0
            - 2.5
            - 2.5
            - 2.5
        acceleration:
            - 1500.0
            - 18.0
            - 18.0
            - 18.0
    position:
        velocity: 100.0
        acceleration: 2000.0
    orientation:
        omega: 0.5
        alpha: 10.0


#END
