soft_constraint:
    lower:
        - -2.9670
        - -2.3561
        - -1.1867
        - -3.2811
        - -1.9896
        - -6.2482
        - 0.0
        - 0.0
        - 0.0
    upper:
        - 2.9670
        - 1.7627
        - 3.4556
        - 3.2811
        - 1.9896
        - 6.2482
        - 0.0
        - 0.0
        - 0.0

#END
