soft_constraint:
    lower:
        - -2.8
        - -2.2
        - -1.0
        - -3.1
        - -1.8
        - -6.0
        - 0.0
        - 0.0
        - 0.0
    upper:
        - 2.8
        - 1.6
        - 3.3
        - 3.1
        - 1.8
        - 6.0
        - 0.0
        - 0.0
        - 0.0
#END