soft_constraint:
    lower:
        - -0.81
        - -0.94
        - -0.77
        - -3.14
        - -1.57
        - -3.14
        - 0.0
        - 0.0
        - 0.0
    upper:
        - 1.37
        - 1.63
        - 1.5
        - 1.41
        - 1.57
        - 3.14
        - 0.0
        - 0.0
        - 0.0
#END
