/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.7 at Wed Dec 18 15:09:47 2019. */

#include "protocol/event_header.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t Event_Header_fields[4] = {
    PB_FIELD(  1, UINT64  , REQUIRED, STATIC  , FIRST, Event_Header, time_stamp, time_stamp, 0),
    PB_FIELD(  2, INT32   , REQUIRED, STATIC  , OTHER, Event_Header, type, time_stamp, 0),
    PB_FIELD(  3, INT32   , REQUIRED, STATIC  , OTHER, Event_Header, id, type, 0),
    PB_LAST_FIELD
};


/* @@protoc_insertion_point(eof) */
