#ifndef MIDDLEWARE_TO_MEM_SERVICE_ID_H_
#define MIDDLEWARE_TO_MEM_SERVICE_ID_H_

enum ServiceID
{
    VERSIONINFO_SID = 0x10,
    HEARTBEAT_SID = 0x11,
    RESET_SID = 0x12,
};



#endif //MIDDLEWARE_TO_MEM_SERVICE_ID_H_
