/* Automatically generated nanopb header */
/* Generated by nanopb-0.3.7-dev at Wed Aug 22 10:47:25 2018. */

#ifndef PB_MESSAGETYPE_BASE_PB_H_INCLUDED
#define PB_MESSAGETYPE_BASE_PB_H_INCLUDED
#include <pb.h>

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Struct definitions */
typedef struct _MessageType_Bool {
    bool data;
/* @@protoc_insertion_point(struct:MessageType_Bool) */
} MessageType_Bool;

typedef struct _MessageType_BoolList {
    pb_size_t data_count;
    bool data[128];
/* @@protoc_insertion_point(struct:MessageType_BoolList) */
} MessageType_BoolList;

typedef PB_BYTES_ARRAY_T(1024) MessageType_Bytes_data_t;
typedef struct _MessageType_Bytes {
    MessageType_Bytes_data_t data;
/* @@protoc_insertion_point(struct:MessageType_Bytes) */
} MessageType_Bytes;

typedef struct _MessageType_Double {
    double data;
/* @@protoc_insertion_point(struct:MessageType_Double) */
} MessageType_Double;

typedef struct _MessageType_DoubleList {
    pb_size_t data_count;
    double data[128];
/* @@protoc_insertion_point(struct:MessageType_DoubleList) */
} MessageType_DoubleList;

typedef struct _MessageType_Float {
    float data;
/* @@protoc_insertion_point(struct:MessageType_Float) */
} MessageType_Float;

typedef struct _MessageType_FloatList {
    pb_size_t data_count;
    float data[128];
/* @@protoc_insertion_point(struct:MessageType_FloatList) */
} MessageType_FloatList;

typedef struct _MessageType_Int32 {
    int32_t data;
/* @@protoc_insertion_point(struct:MessageType_Int32) */
} MessageType_Int32;

typedef struct _MessageType_Int32List {
    pb_size_t data_count;
    int32_t data[128];
/* @@protoc_insertion_point(struct:MessageType_Int32List) */
} MessageType_Int32List;

typedef struct _MessageType_Int64 {
    int64_t data;
/* @@protoc_insertion_point(struct:MessageType_Int64) */
} MessageType_Int64;

typedef struct _MessageType_Int64List {
    pb_size_t data_count;
    int64_t data[128];
/* @@protoc_insertion_point(struct:MessageType_Int64List) */
} MessageType_Int64List;

typedef struct _MessageType_String {
    char data[1024];
/* @@protoc_insertion_point(struct:MessageType_String) */
} MessageType_String;

typedef struct _MessageType_Uint32 {
    uint32_t data;
/* @@protoc_insertion_point(struct:MessageType_Uint32) */
} MessageType_Uint32;

typedef struct _MessageType_Uint32List {
    pb_size_t data_count;
    uint32_t data[128];
/* @@protoc_insertion_point(struct:MessageType_Uint32List) */
} MessageType_Uint32List;

typedef struct _MessageType_Uint64 {
    uint64_t data;
/* @@protoc_insertion_point(struct:MessageType_Uint64) */
} MessageType_Uint64;

typedef struct _MessageType_Uint64List {
    pb_size_t data_count;
    uint64_t data[128];
/* @@protoc_insertion_point(struct:MessageType_Uint64List) */
} MessageType_Uint64List;

/* Default values for struct fields */

/* Initializer values for message structs */
#define MessageType_Bool_init_default            {0}
#define MessageType_Int32_init_default           {0}
#define MessageType_Uint32_init_default          {0}
#define MessageType_Int64_init_default           {0}
#define MessageType_Uint64_init_default          {0}
#define MessageType_Double_init_default          {0}
#define MessageType_Float_init_default           {0}
#define MessageType_Bytes_init_default           {{0, {0}}}
#define MessageType_String_init_default          {""}
#define MessageType_BoolList_init_default        {0, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}}
#define MessageType_Int32List_init_default       {0, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}}
#define MessageType_Uint32List_init_default      {0, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}}
#define MessageType_Int64List_init_default       {0, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}}
#define MessageType_Uint64List_init_default      {0, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}}
#define MessageType_FloatList_init_default       {0, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}}
#define MessageType_DoubleList_init_default      {0, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}}
#define MessageType_Bool_init_zero               {0}
#define MessageType_Int32_init_zero              {0}
#define MessageType_Uint32_init_zero             {0}
#define MessageType_Int64_init_zero              {0}
#define MessageType_Uint64_init_zero             {0}
#define MessageType_Double_init_zero             {0}
#define MessageType_Float_init_zero              {0}
#define MessageType_Bytes_init_zero              {{0, {0}}}
#define MessageType_String_init_zero             {""}
#define MessageType_BoolList_init_zero           {0, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}}
#define MessageType_Int32List_init_zero          {0, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}}
#define MessageType_Uint32List_init_zero         {0, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}}
#define MessageType_Int64List_init_zero          {0, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}}
#define MessageType_Uint64List_init_zero         {0, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}}
#define MessageType_FloatList_init_zero          {0, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}}
#define MessageType_DoubleList_init_zero         {0, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}}

/* Field tags (for use in manual encoding/decoding) */
#define MessageType_Bool_data_tag                1
#define MessageType_BoolList_data_tag            1
#define MessageType_Bytes_data_tag               1
#define MessageType_Double_data_tag              1
#define MessageType_DoubleList_data_tag          1
#define MessageType_Float_data_tag               1
#define MessageType_FloatList_data_tag           1
#define MessageType_Int32_data_tag               1
#define MessageType_Int32List_data_tag           1
#define MessageType_Int64_data_tag               1
#define MessageType_Int64List_data_tag           1
#define MessageType_String_data_tag              1
#define MessageType_Uint32_data_tag              1
#define MessageType_Uint32List_data_tag          1
#define MessageType_Uint64_data_tag              1
#define MessageType_Uint64List_data_tag          1

/* Struct field encoding specification for nanopb */
extern const pb_field_t MessageType_Bool_fields[2];
extern const pb_field_t MessageType_Int32_fields[2];
extern const pb_field_t MessageType_Uint32_fields[2];
extern const pb_field_t MessageType_Int64_fields[2];
extern const pb_field_t MessageType_Uint64_fields[2];
extern const pb_field_t MessageType_Double_fields[2];
extern const pb_field_t MessageType_Float_fields[2];
extern const pb_field_t MessageType_Bytes_fields[2];
extern const pb_field_t MessageType_String_fields[2];
extern const pb_field_t MessageType_BoolList_fields[2];
extern const pb_field_t MessageType_Int32List_fields[2];
extern const pb_field_t MessageType_Uint32List_fields[2];
extern const pb_field_t MessageType_Int64List_fields[2];
extern const pb_field_t MessageType_Uint64List_fields[2];
extern const pb_field_t MessageType_FloatList_fields[2];
extern const pb_field_t MessageType_DoubleList_fields[2];

/* Maximum encoded size of messages (where known) */
#define MessageType_Bool_size                    2
#define MessageType_Int32_size                   11
#define MessageType_Uint32_size                  6
#define MessageType_Int64_size                   11
#define MessageType_Uint64_size                  11
#define MessageType_Double_size                  9
#define MessageType_Float_size                   5
#define MessageType_Bytes_size                   1027
#define MessageType_String_size                  1027
#define MessageType_BoolList_size                256
#define MessageType_Int32List_size               1408
#define MessageType_Uint32List_size              768
#define MessageType_Int64List_size               1408
#define MessageType_Uint64List_size              1408
#define MessageType_FloatList_size               640
#define MessageType_DoubleList_size              1152

/* Message IDs (where set with "msgid" option) */
#ifdef PB_MSGID

#define BASE_MESSAGES \


#endif

#ifdef __cplusplus
} /* extern "C" */
#endif
/* @@protoc_insertion_point(eof) */

#endif
