/* Automatically generated nanopb header */
/* Generated by nanopb-0.3.7-dev at Wed Sep 12 13:42:17 2018. */

#ifndef PB_MESSAGETYPE_FILE_PB_H_INCLUDED
#define PB_MESSAGETYPE_FILE_PB_H_INCLUDED
#include <pb.h>

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Struct definitions */
typedef struct _MessageType_File {
    char file_path[1024];
    char data[50000];
/* @@protoc_insertion_point(struct:MessageType_File) */
} MessageType_File;

/* Default values for struct fields */

/* Initializer values for message structs */
#define MessageType_File_init_default            {"", ""}
#define MessageType_File_init_zero               {"", ""}

/* Field tags (for use in manual encoding/decoding) */
#define MessageType_File_file_path_tag           1
#define MessageType_File_data_tag                2

/* Struct field encoding specification for nanopb */
extern const pb_field_t MessageType_File_fields[3];

/* Maximum encoded size of messages (where known) */
#define MessageType_File_size                    51031

/* Message IDs (where set with "msgid" option) */
#ifdef PB_MSGID

#define FILE_MESSAGES \


#endif

#ifdef __cplusplus
} /* extern "C" */
#endif
/* @@protoc_insertion_point(eof) */

#endif
