/* Automatically generated nanopb header */
/* Generated by nanopb-0.3.7-dev at Mon Aug 27 13:40:10 2018. */

#ifndef PB_MESSAGETYPE_IO_TYPE_PB_H_INCLUDED
#define PB_MESSAGETYPE_IO_TYPE_PB_H_INCLUDED
#include <pb.h>

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Enum definitions */
typedef enum _MessageType_IoType {
    MessageType_IoType_INPUT = 0,
    MessageType_IoType_OUTPUT = 1
} MessageType_IoType;
#define _MessageType_IoType_MIN MessageType_IoType_INPUT
#define _MessageType_IoType_MAX MessageType_IoType_OUTPUT
#define _MessageType_IoType_ARRAYSIZE ((MessageType_IoType)(MessageType_IoType_OUTPUT+1))

#ifdef __cplusplus
} /* extern "C" */
#endif
/* @@protoc_insertion_point(eof) */

#endif
