/* Automatically generated nanopb header */
/* Generated by nanopb-0.3.7-dev at Fri Dec 28 10:08:34 2018. */

#ifndef PB_MESSAGETYPE_MODBUS_FUNCTION_PB_H_INCLUDED
#define PB_MESSAGETYPE_MODBUS_FUNCTION_PB_H_INCLUDED
#include <pb.h>

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Enum definitions */
typedef enum _MessageType_ModbusFunctionType {
    MessageType_ModbusFunctionType_COIL = 1,
    MessageType_ModbusFunctionType_DISCREPTE_INPUT = 2,
    MessageType_ModbusFunctionType_HOLDING_REGISTER = 3,
    MessageType_ModbusFunctionType_INPUT_REGISTER = 4
} MessageType_ModbusFunctionType;
#define _MessageType_ModbusFunctionType_MIN MessageType_ModbusFunctionType_COIL
#define _MessageType_ModbusFunctionType_MAX MessageType_ModbusFunctionType_INPUT_REGISTER
#define _MessageType_ModbusFunctionType_ARRAYSIZE ((MessageType_ModbusFunctionType)(MessageType_ModbusFunctionType_INPUT_REGISTER+1))

/* Struct definitions */
typedef struct _MessageType_ModbusFunctionAddrInfo {
    int32_t address;
    int32_t number;
/* @@protoc_insertion_point(struct:MessageType_ModbusFunctionAddrInfo) */
} MessageType_ModbusFunctionAddrInfo;

typedef struct _MessageType_ModbusAllFucntionAddrInfo {
    MessageType_ModbusFunctionAddrInfo coil;
    MessageType_ModbusFunctionAddrInfo discrepte_input;
    MessageType_ModbusFunctionAddrInfo holding_reg;
    MessageType_ModbusFunctionAddrInfo input_reg;
/* @@protoc_insertion_point(struct:MessageType_ModbusAllFucntionAddrInfo) */
} MessageType_ModbusAllFucntionAddrInfo;

typedef struct _MessageType_ModbusFunctionInfo {
    MessageType_ModbusFunctionType func_type;
    MessageType_ModbusFunctionAddrInfo func_addr_info;
/* @@protoc_insertion_point(struct:MessageType_ModbusFunctionInfo) */
} MessageType_ModbusFunctionInfo;

/* Default values for struct fields */

/* Initializer values for message structs */
#define MessageType_ModbusFunctionAddrInfo_init_default {0, 0}
#define MessageType_ModbusAllFucntionAddrInfo_init_default {MessageType_ModbusFunctionAddrInfo_init_default, MessageType_ModbusFunctionAddrInfo_init_default, MessageType_ModbusFunctionAddrInfo_init_default, MessageType_ModbusFunctionAddrInfo_init_default}
#define MessageType_ModbusFunctionInfo_init_default {(MessageType_ModbusFunctionType)0, MessageType_ModbusFunctionAddrInfo_init_default}
#define MessageType_ModbusFunctionAddrInfo_init_zero {0, 0}
#define MessageType_ModbusAllFucntionAddrInfo_init_zero {MessageType_ModbusFunctionAddrInfo_init_zero, MessageType_ModbusFunctionAddrInfo_init_zero, MessageType_ModbusFunctionAddrInfo_init_zero, MessageType_ModbusFunctionAddrInfo_init_zero}
#define MessageType_ModbusFunctionInfo_init_zero {(MessageType_ModbusFunctionType)0, MessageType_ModbusFunctionAddrInfo_init_zero}

/* Field tags (for use in manual encoding/decoding) */
#define MessageType_ModbusFunctionAddrInfo_address_tag 1
#define MessageType_ModbusFunctionAddrInfo_number_tag 2
#define MessageType_ModbusAllFucntionAddrInfo_coil_tag 1
#define MessageType_ModbusAllFucntionAddrInfo_discrepte_input_tag 2
#define MessageType_ModbusAllFucntionAddrInfo_holding_reg_tag 3
#define MessageType_ModbusAllFucntionAddrInfo_input_reg_tag 4
#define MessageType_ModbusFunctionInfo_func_type_tag 1
#define MessageType_ModbusFunctionInfo_func_addr_info_tag 2

/* Struct field encoding specification for nanopb */
extern const pb_field_t MessageType_ModbusFunctionAddrInfo_fields[3];
extern const pb_field_t MessageType_ModbusAllFucntionAddrInfo_fields[5];
extern const pb_field_t MessageType_ModbusFunctionInfo_fields[3];

/* Maximum encoded size of messages (where known) */
#define MessageType_ModbusFunctionAddrInfo_size  22
#define MessageType_ModbusAllFucntionAddrInfo_size 96
#define MessageType_ModbusFunctionInfo_size      26

/* Message IDs (where set with "msgid" option) */
#ifdef PB_MSGID

#define MODBUS_FUNCTION_MESSAGES \


#endif

#ifdef __cplusplus
} /* extern "C" */
#endif
/* @@protoc_insertion_point(eof) */

#endif
