/* Automatically generated nanopb header */
/* Generated by nanopb-0.3.7-dev at Mon Dec  3 15:24:30 2018. */

#ifndef PB_MESSAGETYPE_MODBUS_SERVER_FUNCTION_PB_H_INCLUDED
#define PB_MESSAGETYPE_MODBUS_SERVER_FUNCTION_PB_H_INCLUDED
#include <pb.h>

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Enum definitions */
typedef enum _MessageType_ModbusServerFunctionType {
    MessageType_ModbusServerFunctionType_COIL = 1,
    MessageType_ModbusServerFunctionType_DISCREPTE_INPUT = 2,
    MessageType_ModbusServerFunctionType_INPUT_REGISTER = 3,
    MessageType_ModbusServerFunctionType_HOLDING_REGISTER = 4
} MessageType_ModbusServerFunctionType;
#define _MessageType_ModbusServerFunctionType_MIN MessageType_ModbusServerFunctionType_COIL
#define _MessageType_ModbusServerFunctionType_MAX MessageType_ModbusServerFunctionType_HOLDING_REGISTER
#define _MessageType_ModbusServerFunctionType_ARRAYSIZE ((MessageType_ModbusServerFunctionType)(MessageType_ModbusServerFunctionType_HOLDING_REGISTER+1))

#ifdef __cplusplus
} /* extern "C" */
#endif
/* @@protoc_insertion_point(eof) */

#endif
