/* Automatically generated nanopb header */
/* Generated by nanopb-0.3.7-dev at Wed Jan  2 15:26:38 2019. */

#ifndef PB_MESSAGETYPE_MODBUS_CLIENT_START_INFO_PB_H_INCLUDED
#define PB_MESSAGETYPE_MODBUS_CLIENT_START_INFO_PB_H_INCLUDED
#include <pb.h>

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Struct definitions */
typedef struct _MessageType_ModbusClientStartInfo {
    int32_t id;
    char name[128];
    char ip[128];
    int32_t port;
    int32_t scan_rate;
    int32_t response_timeout;
/* @@protoc_insertion_point(struct:MessageType_ModbusClientStartInfo) */
} MessageType_ModbusClientStartInfo;

/* Default values for struct fields */

/* Initializer values for message structs */
#define MessageType_ModbusClientStartInfo_init_default {0, "", "", 0, 0, 0}
#define MessageType_ModbusClientStartInfo_init_zero {0, "", "", 0, 0, 0}

/* Field tags (for use in manual encoding/decoding) */
#define MessageType_ModbusClientStartInfo_id_tag 1
#define MessageType_ModbusClientStartInfo_name_tag 2
#define MessageType_ModbusClientStartInfo_ip_tag 3
#define MessageType_ModbusClientStartInfo_port_tag 4
#define MessageType_ModbusClientStartInfo_scan_rate_tag 5
#define MessageType_ModbusClientStartInfo_response_timeout_tag 6

/* Struct field encoding specification for nanopb */
extern const pb_field_t MessageType_ModbusClientStartInfo_fields[7];

/* Maximum encoded size of messages (where known) */
#define MessageType_ModbusClientStartInfo_size   306

/* Message IDs (where set with "msgid" option) */
#ifdef PB_MSGID

#define MODBUS_CLIENT_START_INFO_MESSAGES \


#endif

#ifdef __cplusplus
} /* extern "C" */
#endif
/* @@protoc_insertion_point(eof) */

#endif
