/* Automatically generated nanopb header */
/* Generated by nanopb-0.3.7-dev at Mon Dec  3 15:24:30 2018. */

#ifndef PB_MESSAGETYPE_MODBUS_CLIENT_PB_H_INCLUDED
#define PB_MESSAGETYPE_MODBUS_CLIENT_PB_H_INCLUDED
#include <pb.h>

#include "message_type/timeval.pb.h"

#include "message_type/modbus_server.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Struct definitions */
typedef struct _MessageType_ModbusClientConfig {
    MessageType_ModbusServerConfig server_config;
    uint32_t id;
    char name[128];
    char ip[128];
    int32_t port;
    uint32_t response_timeout;
    uint32_t bytes_timeout;
/* @@protoc_insertion_point(struct:MessageType_ModbusClientConfig) */
} MessageType_ModbusClientConfig;

/* Default values for struct fields */

/* Initializer values for message structs */
#define MessageType_ModbusClientConfig_init_default {MessageType_ModbusServerConfig_init_default, 0, "", "", 0, 0, 0}
#define MessageType_ModbusClientConfig_init_zero {MessageType_ModbusServerConfig_init_zero, 0, "", "", 0, 0, 0}

/* Field tags (for use in manual encoding/decoding) */
#define MessageType_ModbusClientConfig_server_config_tag 1
#define MessageType_ModbusClientConfig_id_tag    2
#define MessageType_ModbusClientConfig_name_tag  3
#define MessageType_ModbusClientConfig_ip_tag    4
#define MessageType_ModbusClientConfig_port_tag  5
#define MessageType_ModbusClientConfig_response_timeout_tag 6
#define MessageType_ModbusClientConfig_bytes_timeout_tag 7

/* Struct field encoding specification for nanopb */
extern const pb_field_t MessageType_ModbusClientConfig_fields[8];

/* Maximum encoded size of messages (where known) */
#define MessageType_ModbusClientConfig_size      393

/* Message IDs (where set with "msgid" option) */
#ifdef PB_MSGID

#define MODBUS_CLIENT_MESSAGES \


#endif

#ifdef __cplusplus
} /* extern "C" */
#endif
/* @@protoc_insertion_point(eof) */

#endif
