/* Automatically generated nanopb header */
/* Generated by nanopb-0.3.7-dev at Mon Jul  8 16:05:54 2019. */

#ifndef PB_MESSAGETYPE_PAYLOAD_INFO_PB_H_INCLUDED
#define PB_MESSAGETYPE_PAYLOAD_INFO_PB_H_INCLUDED
#include <pb.h>

#include "message_type/base.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Struct definitions */
typedef struct _MessageType_PayloadInfo {
    uint32_t id;
    char comment[256];
    double weight;
    MessageType_DoubleList mass_center;
    MessageType_DoubleList inertia_moment;
/* @@protoc_insertion_point(struct:MessageType_PayloadInfo) */
} MessageType_PayloadInfo;

typedef struct _MessageType_PayloadSummaryInfo {
    uint32_t id;
    char comment[256];
/* @@protoc_insertion_point(struct:MessageType_PayloadSummaryInfo) */
} MessageType_PayloadSummaryInfo;

typedef struct _MessageType_PayloadSummaryList {
    pb_size_t payload_summary_info_count;
    MessageType_PayloadSummaryInfo payload_summary_info[32];
/* @@protoc_insertion_point(struct:MessageType_PayloadSummaryList) */
} MessageType_PayloadSummaryList;

/* Default values for struct fields */

/* Initializer values for message structs */
#define MessageType_PayloadInfo_init_default     {0, "", 0, MessageType_DoubleList_init_default, MessageType_DoubleList_init_default}
#define MessageType_PayloadSummaryInfo_init_default {0, ""}
#define MessageType_PayloadSummaryList_init_default {0, {MessageType_PayloadSummaryInfo_init_default, MessageType_PayloadSummaryInfo_init_default, MessageType_PayloadSummaryInfo_init_default, MessageType_PayloadSummaryInfo_init_default, MessageType_PayloadSummaryInfo_init_default, MessageType_PayloadSummaryInfo_init_default, MessageType_PayloadSummaryInfo_init_default, MessageType_PayloadSummaryInfo_init_default, MessageType_PayloadSummaryInfo_init_default, MessageType_PayloadSummaryInfo_init_default, MessageType_PayloadSummaryInfo_init_default, MessageType_PayloadSummaryInfo_init_default, MessageType_PayloadSummaryInfo_init_default, MessageType_PayloadSummaryInfo_init_default, MessageType_PayloadSummaryInfo_init_default, MessageType_PayloadSummaryInfo_init_default, MessageType_PayloadSummaryInfo_init_default, MessageType_PayloadSummaryInfo_init_default, MessageType_PayloadSummaryInfo_init_default, MessageType_PayloadSummaryInfo_init_default, MessageType_PayloadSummaryInfo_init_default, MessageType_PayloadSummaryInfo_init_default, MessageType_PayloadSummaryInfo_init_default, MessageType_PayloadSummaryInfo_init_default, MessageType_PayloadSummaryInfo_init_default, MessageType_PayloadSummaryInfo_init_default, MessageType_PayloadSummaryInfo_init_default, MessageType_PayloadSummaryInfo_init_default, MessageType_PayloadSummaryInfo_init_default, MessageType_PayloadSummaryInfo_init_default, MessageType_PayloadSummaryInfo_init_default, MessageType_PayloadSummaryInfo_init_default}}
#define MessageType_PayloadInfo_init_zero        {0, "", 0, MessageType_DoubleList_init_zero, MessageType_DoubleList_init_zero}
#define MessageType_PayloadSummaryInfo_init_zero {0, ""}
#define MessageType_PayloadSummaryList_init_zero {0, {MessageType_PayloadSummaryInfo_init_zero, MessageType_PayloadSummaryInfo_init_zero, MessageType_PayloadSummaryInfo_init_zero, MessageType_PayloadSummaryInfo_init_zero, MessageType_PayloadSummaryInfo_init_zero, MessageType_PayloadSummaryInfo_init_zero, MessageType_PayloadSummaryInfo_init_zero, MessageType_PayloadSummaryInfo_init_zero, MessageType_PayloadSummaryInfo_init_zero, MessageType_PayloadSummaryInfo_init_zero, MessageType_PayloadSummaryInfo_init_zero, MessageType_PayloadSummaryInfo_init_zero, MessageType_PayloadSummaryInfo_init_zero, MessageType_PayloadSummaryInfo_init_zero, MessageType_PayloadSummaryInfo_init_zero, MessageType_PayloadSummaryInfo_init_zero, MessageType_PayloadSummaryInfo_init_zero, MessageType_PayloadSummaryInfo_init_zero, MessageType_PayloadSummaryInfo_init_zero, MessageType_PayloadSummaryInfo_init_zero, MessageType_PayloadSummaryInfo_init_zero, MessageType_PayloadSummaryInfo_init_zero, MessageType_PayloadSummaryInfo_init_zero, MessageType_PayloadSummaryInfo_init_zero, MessageType_PayloadSummaryInfo_init_zero, MessageType_PayloadSummaryInfo_init_zero, MessageType_PayloadSummaryInfo_init_zero, MessageType_PayloadSummaryInfo_init_zero, MessageType_PayloadSummaryInfo_init_zero, MessageType_PayloadSummaryInfo_init_zero, MessageType_PayloadSummaryInfo_init_zero, MessageType_PayloadSummaryInfo_init_zero}}

/* Field tags (for use in manual encoding/decoding) */
#define MessageType_PayloadInfo_id_tag           1
#define MessageType_PayloadInfo_comment_tag      2
#define MessageType_PayloadInfo_weight_tag       3
#define MessageType_PayloadInfo_mass_center_tag  4
#define MessageType_PayloadInfo_inertia_moment_tag 5
#define MessageType_PayloadSummaryInfo_id_tag    1
#define MessageType_PayloadSummaryInfo_comment_tag 2
#define MessageType_PayloadSummaryList_payload_summary_info_tag 1

/* Struct field encoding specification for nanopb */
extern const pb_field_t MessageType_PayloadInfo_fields[6];
extern const pb_field_t MessageType_PayloadSummaryInfo_fields[3];
extern const pb_field_t MessageType_PayloadSummaryList_fields[2];

/* Maximum encoded size of messages (where known) */
#define MessageType_PayloadInfo_size             2584
#define MessageType_PayloadSummaryInfo_size      265
#define MessageType_PayloadSummaryList_size      8576

/* Message IDs (where set with "msgid" option) */
#ifdef PB_MSGID

#define PAYLOAD_INFO_MESSAGES \


#endif

#ifdef __cplusplus
} /* extern "C" */
#endif
/* @@protoc_insertion_point(eof) */

#endif
