/* Automatically generated nanopb header */
/* Generated by nanopb-0.3.7-dev at Fri Aug 10 13:55:07 2018. */

#ifndef PB_MESSAGETYPE_REG_HR_PB_H_INCLUDED
#define PB_MESSAGETYPE_REG_HR_PB_H_INCLUDED
#include <pb.h>

#include "message_type/base.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Struct definitions */
typedef struct _MessageType_HrRegData {
    int32_t id;
    char name[32];
    char comment[256];
    int32_t group_id;
    MessageType_DoubleList joints;
    MessageType_DoubleList diffs;
/* @@protoc_insertion_point(struct:MessageType_HrRegData) */
} MessageType_HrRegData;

/* Default values for struct fields */

/* Initializer values for message structs */
#define MessageType_HrRegData_init_default       {0, "", "", 0, MessageType_DoubleList_init_default, MessageType_DoubleList_init_default}
#define MessageType_HrRegData_init_zero          {0, "", "", 0, MessageType_DoubleList_init_zero, MessageType_DoubleList_init_zero}

/* Field tags (for use in manual encoding/decoding) */
#define MessageType_HrRegData_id_tag             1
#define MessageType_HrRegData_name_tag           2
#define MessageType_HrRegData_comment_tag        3
#define MessageType_HrRegData_group_id_tag       4
#define MessageType_HrRegData_joints_tag         5
#define MessageType_HrRegData_diffs_tag          6

/* Struct field encoding specification for nanopb */
extern const pb_field_t MessageType_HrRegData_fields[7];

/* Maximum encoded size of messages (where known) */
#define MessageType_HrRegData_size               2625

/* Message IDs (where set with "msgid" option) */
#ifdef PB_MSGID

#define REG_HR_MESSAGES \


#endif

#ifdef __cplusplus
} /* extern "C" */
#endif
/* @@protoc_insertion_point(eof) */

#endif
