/* Automatically generated nanopb header */
/* Generated by nanopb-0.3.7-dev at Wed Nov 28 15:41:09 2018. */

#ifndef PB_MESSAGETYPE_TIMEVAL_PB_H_INCLUDED
#define PB_MESSAGETYPE_TIMEVAL_PB_H_INCLUDED
#include <pb.h>

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Struct definitions */
typedef struct _MessageType_Timeval {
    uint32_t sec;
    uint32_t usec;
/* @@protoc_insertion_point(struct:MessageType_Timeval) */
} MessageType_Timeval;

/* Default values for struct fields */

/* Initializer values for message structs */
#define MessageType_Timeval_init_default         {0, 0}
#define MessageType_Timeval_init_zero            {0, 0}

/* Field tags (for use in manual encoding/decoding) */
#define MessageType_Timeval_sec_tag              1
#define MessageType_Timeval_usec_tag             2

/* Struct field encoding specification for nanopb */
extern const pb_field_t MessageType_Timeval_fields[3];

/* Maximum encoded size of messages (where known) */
#define MessageType_Timeval_size                 12

/* Message IDs (where set with "msgid" option) */
#ifdef PB_MSGID

#define TIMEVAL_MESSAGES \


#endif

#ifdef __cplusplus
} /* extern "C" */
#endif
/* @@protoc_insertion_point(eof) */

#endif
