/* Automatically generated nanopb header */
/* Generated by nanopb-0.3.7 at Thu May  6 16:58:13 2021. */

#ifndef PB_MESSAGETYPE_UFTF_POSE_AND_POSTURE_PB_H_INCLUDED
#define PB_MESSAGETYPE_UFTF_POSE_AND_POSTURE_PB_H_INCLUDED
#include <pb.h>

#include "message_type/base.pb.h"

#include "message_type/pose_and_posture.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Struct definitions */
typedef struct _MessageType_UFTF_PoseAndPosture {
    MessageType_Uint32 uf_id;
    MessageType_Uint32 tf_id;
    MessageType_PoseAndPosture pose_and_posture;
/* @@protoc_insertion_point(struct:MessageType_UFTF_PoseAndPosture) */
} MessageType_UFTF_PoseAndPosture;

/* Default values for struct fields */

/* Initializer values for message structs */
#define MessageType_UFTF_PoseAndPosture_init_default {MessageType_Uint32_init_default, MessageType_Uint32_init_default, MessageType_PoseAndPosture_init_default}
#define MessageType_UFTF_PoseAndPosture_init_zero {MessageType_Uint32_init_zero, MessageType_Uint32_init_zero, MessageType_PoseAndPosture_init_zero}

/* Field tags (for use in manual encoding/decoding) */
#define MessageType_UFTF_PoseAndPosture_uf_id_tag 1
#define MessageType_UFTF_PoseAndPosture_tf_id_tag 2
#define MessageType_UFTF_PoseAndPosture_pose_and_posture_tag 3

/* Struct field encoding specification for nanopb */
extern const pb_field_t MessageType_UFTF_PoseAndPosture_fields[4];

/* Maximum encoded size of messages (where known) */
#define MessageType_UFTF_PoseAndPosture_size     (1183 + MessageType_Posture_size)

/* Message IDs (where set with "msgid" option) */
#ifdef PB_MSGID

#define UFTF_POSE_AND_POSTURE_MESSAGES \


#endif

#ifdef __cplusplus
} /* extern "C" */
#endif
/* @@protoc_insertion_point(eof) */

#endif
