/* Automatically generated hashes for nanopb types */
/* Generated by proto_hashgen fromUNDEFINED at Fri Apr 21 08:51:24 2017. */
#ifndef BASE_TYPES_HASH_H_INCLUDED
#define BASE_TYPES_HASH_H_INCLUDED
#include "base_types.pb.h"

template <class T>
inline const unsigned char* get_hash()
{
    return NULL;
}

template <>
inline const unsigned char* get_hash<BaseTypes_ParameterCmdListMsg>()
{
    static unsigned char type[] = {169, 69, 128, 147, 35, 43, 45, 21, 134, 128, 141, 20, 145, 213, 83, 182};
    return type;
}

template <>
inline const unsigned char* get_hash<BaseTypes_ConsoleCmdListMsg>()
{
    static unsigned char type[] = {54, 147, 64, 82, 68, 116, 120, 128, 87, 23, 210, 191, 179, 20, 40, 221};
    return type;
}

template <>
inline const unsigned char* get_hash<BaseTypes_ParamInfo>()
{
    static unsigned char type[] = {72, 170, 34, 22, 135, 245, 74, 139, 99, 241, 161, 68, 251, 10, 159, 137};
    return type;
}

template <>
inline const unsigned char* get_hash<BaseTypes_ParameterCmdMsg>()
{
    static unsigned char type[] = {200, 215, 210, 138, 128, 189, 8, 35, 240, 36, 169, 133, 240, 139, 45, 183};
    return type;
}

template <>
inline const unsigned char* get_hash<BaseTypes_ParameterOverwriteMsg>()
{
    static unsigned char type[] = {206, 150, 184, 94, 230, 6, 192, 209, 90, 202, 191, 210, 160, 69, 227, 131};
    return type;
}

template <>
inline const unsigned char* get_hash<BaseTypes_DataType>()
{
    static unsigned char type[] = {64, 26, 158, 34, 206, 239, 30, 158, 70, 113, 241, 135, 106, 218, 243, 4};
    return type;
}

template <>
inline const unsigned char* get_hash<BaseTypes_ConsoleCmdMsg>()
{
    static unsigned char type[] = {114, 157, 66, 187, 135, 133, 76, 124, 109, 21, 91, 59, 5, 193, 185, 27};
    return type;
}

template <>
inline const unsigned char* get_hash<BaseTypes_ParameterGetListMsg>()
{
    static unsigned char type[] = {228, 76, 231, 98, 101, 253, 18, 42, 22, 182, 12, 38, 97, 18, 253, 43};
    return type;
}

template <>
inline const unsigned char* get_hash<BaseTypes_UserLevel>()
{
    static unsigned char type[] = {126, 188, 158, 245, 223, 229, 229, 63, 28, 99, 100, 171, 59, 206, 231, 126};
    return type;
}

template <>
inline const unsigned char* get_hash<BaseTypes_ParameterGetMsg>()
{
    static unsigned char type[] = {188, 19, 3, 216, 76, 163, 5, 252, 148, 35, 61, 123, 38, 8, 134, 75};
    return type;
}

template <>
inline const unsigned char* get_hash<BaseTypes_LogMsg>()
{
    static unsigned char type[] = {221, 59, 245, 15, 40, 212, 178, 40, 110, 91, 33, 222, 248, 1, 154, 76};
    return type;
}

template <>
inline const unsigned char* get_hash<BaseTypes_ParameterSetListMsg>()
{
    static unsigned char type[] = {26, 178, 173, 177, 175, 82, 113, 170, 169, 46, 253, 177, 138, 99, 160, 210};
    return type;
}

template <>
inline const unsigned char* get_hash<BaseTypes_ParameterSetMsg>()
{
    static unsigned char type[] = {25, 44, 161, 112, 246, 187, 180, 183, 213, 136, 138, 2, 25, 144, 109, 114};
    return type;
}

template <>
inline const unsigned char* get_hash<BaseTypes_ParamType>()
{
    static unsigned char type[] = {155, 85, 29, 105, 135, 135, 13, 132, 40, 120, 77, 8, 70, 126, 74, 182};
    return type;
}

template <>
inline const unsigned char* get_hash<BaseTypes_CommandType>()
{
    static unsigned char type[] = {45, 114, 29, 206, 151, 217, 133, 116, 217, 147, 116, 146, 36, 220, 42, 179};
    return type;
}

template <>
inline const unsigned char* get_hash<BaseTypes_StatusMsg>()
{
    static unsigned char type[] = {152, 167, 75, 117, 101, 229, 188, 210, 186, 169, 64, 81, 156, 67, 25, 244};
    return type;
}

template <>
inline const unsigned char* get_hash<BaseTypes_StatusCode>()
{
    static unsigned char type[] = {97, 227, 19, 209, 118, 107, 74, 239, 77, 54, 82, 231, 212, 21, 155, 44};
    return type;
}

template <>
inline const unsigned char* get_hash<BaseTypes_LogListMsg>()
{
    static unsigned char type[] = {22, 148, 71, 26, 240, 23, 42, 144, 238, 93, 29, 228, 195, 40, 200, 220};
    return type;
}

template <>
inline const unsigned char* get_hash<BaseTypes_Header>()
{
    static unsigned char type[] = {79, 186, 91, 108, 115, 166, 239, 69, 14, 178, 99, 218, 4, 61, 113, 196};
    return type;
}

template <>
inline const unsigned char* get_hash<BaseTypes_Unit>()
{
    static unsigned char type[] = {127, 61, 218, 196, 141, 155, 191, 104, 19, 198, 125, 132, 132, 191, 98, 228};
    return type;
}

template <>
inline const unsigned char* get_hash<BaseTypes_Permission>()
{
    static unsigned char type[] = {88, 70, 150, 183, 89, 47, 18, 34, 252, 249, 251, 199, 8, 121, 92, 181};
    return type;
}

template <>
inline const unsigned char* get_hash<BaseTypes_ParameterMsg>()
{
    static unsigned char type[] = {116, 85, 33, 168, 167, 21, 55, 142, 180, 82, 245, 189, 30, 232, 83, 243};
    return type;
}

template <>
inline const unsigned char* get_hash<BaseTypes_ParameterListMsg>()
{
    static unsigned char type[] = {194, 212, 69, 109, 190, 208, 8, 63, 228, 237, 89, 195, 77, 232, 56, 143};
    return type;
}

inline int get_hash_size()
{
    return 16;
}

#endif
